### ISSUE TITLE
Can't run any test (Gradle project)

### ISSUE THREAD

**Issue by Cotel** [kotest/kotest#1082]
I just added kotlintest to my Gradle project:

```
test {
  useJUnitPlatform()
}

...

dependencies {
...
  testImplementation "io.kotlintest:kotlintest-runner-junit5:3.4.2"
}
```

And when I try to run any test it fails with the following exception, although it finds tests and display them correctly at the Run tab in the IDE.

```
~~~ Project Configuration ~~~
-> Parallelism: 1 thread
-> Test order: LexicographicSpecExecutionOrder
-> Soft assertations: False
-> Write spec failure file: False
-> Fail on ignored tests: False
-> Extensions
  - io.kotlintest.extensions.SystemPropertyTagExtension
  - io.kotlintest.extensions.RuntimeTagExtension

java.lang.NoSuchMethodError: kotlinx.coroutines.ExecutorsKt.from(Ljava/util/concurrent/ExecutorService;)Lkotlinx/coroutines/ExecutorCoroutineDispatcher;
	at io.kotlintest.runner.jvm.TestCaseExecutor.execute(TestCaseExecutor.kt:48)
	at io.kotlintest.runner.jvm.spec.SingleInstanceSpecRunner$execute$1$1.invokeSuspend(SingleInstanceSpecRunner.kt:57)
	at io.kotlintest.runner.jvm.spec.SingleInstanceSpecRunner$execute$1$1.invoke(SingleInstanceSpecRunner.kt)
	at io.kotlintest.runner.jvm.spec.SpecRunner.interceptSpec(SpecRunner.kt:27)
	at io.kotlintest.runner.jvm.spec.SpecRunner.interceptSpec(SpecRunner.kt:53)
	at io.kotlintest.runner.jvm.spec.SingleInstanceSpecRunner$execute$1.invokeSuspend(SingleInstanceSpecRunner.kt:53)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask$DefaultImpls.run(Dispatched.kt:146)
	at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:13)
	at kotlinx.coroutines.EventLoopBase.processNextEvent(EventLoop.kt:140)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:70)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:46)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotlintest.runner.jvm.spec.SingleInstanceSpecRunner.execute(SingleInstanceSpecRunner.kt:52)
	at io.kotlintest.runner.jvm.spec.SpecExecutor$execute$$inlined$invoke$lambda$1.invoke(SpecExecutor.kt:54)
	at io.kotlintest.runner.jvm.spec.SpecExecutor$execute$$inlined$invoke$lambda$1.invoke(SpecExecutor.kt:20)
	at io.kotlintest.runner.jvm.spec.SpecExecutor.withExecutor(SpecExecutor.kt:31)
	at io.kotlintest.runner.jvm.spec.SpecExecutor.execute(SpecExecutor.kt:37)
	at io.kotlintest.runner.jvm.TestEngine$submitSpec$1.run(TestEngine.kt:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

*EDIT*:

I've tried to disable other dependencies to see if there is any conflict and this exception pops up if I use `arrow-ank`.

**Comment by sksamuel** [comment]
Looks like a version mismatch on coroutines.

**Comment by sksamuel** [comment]
Can you see if you're using a 1.3+ version of coroutines in the build ?

**Comment by Cotel** [comment]
I am not using coroutines in the project but I can confirm Ank brings kotlinx-coroutines-core 1.1.1 and even 0.26.1-eap13. I think we can close this issue as it is not a problem in this library.

Thank you for your time 😄

**Comment by LeoColman** [comment]
Thanks for the heads-up, Cotel!

**Comment by meenakshi-dhanani** [comment]
I ran all tests with the following: 
./gradlew jvmTest
./gradlew allTests
None of these are creating a test report for all tests. 

I've also tried running tests with IntelliJ, that doesn't work too, but that's a different issue. Could someone please help me get these tests running via command line?

**Comment by LeoColman** [comment]
Could you please open an issue for your problem? Please make sure to include the version you're running and the errors you're getting
