### ISSUE TITLE
Exception when getting annotations in gradle < 6

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1232]
```
23:09:31.474 [DEBUG] [TestEventLogger] Gradle Test Executor 1 STANDARD_ERROR
23:09:31.474 [DEBUG] [TestEventLogger]     java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
23:09:31.474 [DEBUG] [TestEventLogger]          at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
23:09:31.474 [DEBUG] [TestEventLogger]          at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
23:09:31.474 [DEBUG] [TestEventLogger]          at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
23:09:31.474 [DEBUG] [TestEventLogger]          at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
23:09:31.474 [DEBUG] [TestEventLogger]          at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
23:09:31.474 [DEBUG] [TestEventLogger]          at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
23:09:31.474 [DEBUG] [TestEventLogger]          at java.lang.Class.createAnnotationData(Class.java:3521)
23:09:31.474 [DEBUG] [TestEventLogger]          at java.lang.Class.annotationData(Class.java:3510)
23:09:31.474 [DEBUG] [TestEventLogger]          at java.lang.Class.getDeclaredAnnotations(Class.java:3477)
23:09:31.474 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectClassStructure.loadClassAnnotations(ReflectKotlinClass.kt:83)
23:09:31.474 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectKotlinClass$Factory.create(ReflectKotlinClass.kt:55)
23:09:31.474 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectKotlinClassFinder.findKotlinClass(ReflectKotlinClassFinder.kt:30)
23:09:31.475 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectKotlinClassFinder.findKotlinClassOrContent(ReflectKotlinClassFinder.kt:33)
23:09:31.475 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaPackageScope$classes$1.invoke(LazyJavaPackageScope.kt:62)
23:09:31.475 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaPackageScope$classes$1.invoke(LazyJavaPackageScope.kt:42)
23:09:31.475 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:446)
23:09:31.475 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaPackageScope.findClassifier(LazyJavaPackageScope.kt:142)
23:09:31.475 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaPackageScope.getContributedClassifier(LazyJavaPackageScope.kt:132)
23:09:31.475 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.JvmPackageScope.getContributedClassifier(JvmPackageScope.kt:52)
23:09:31.475 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.resolve.scopes.ChainedMemberScope.getContributedClassifier(ChainedMemberScope.kt:33)
23:09:31.475 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.resolve.scopes.AbstractScopeAdapter.getContributedClassifier(AbstractScopeAdapter.kt:44)
23:09:31.475 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.descriptors.FindClassInModuleKt.findClassifierAcrossModuleDependencies(findClassInModule.kt:25)
23:09:31.475 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.descriptors.FindClassInModuleKt.findClassAcrossModuleDependencies(findClassInModule.kt:40)
23:09:31.475 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.descriptors.FindClassInModuleKt.findNonGenericClassAcrossDependencies(findClassInModule.kt:45)
23:09:31.475 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.load.kotlin.BinaryClassAnnotationAndConstantLoaderImpl.resolveClass(BinaryClassAnnotationAndConstantLoaderImpl.kt:146)
23:09:31.475 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.load.kotlin.BinaryClassAnnotationAndConstantLoaderImpl.loadAnnotation(BinaryClassAnnotationAndConstantLoaderImpl.kt:79)
23:09:31.475 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader.loadAnnotationIfNotSpecial(AbstractBinaryClassAnnotationAndConstantLoader.kt:67)
23:09:31.476 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader.access$loadAnnotationIfNotSpecial(AbstractBinaryClassAnnotationAndConstantLoader.kt:40)
23:09:31.476 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader$loadClassAnnotations$1.visitAnnotation(AbstractBinaryClassAnnotationAndConstantLoader.kt:82)
23:09:31.476 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectClassStructure.processAnnotation(ReflectKotlinClass.kt:164)
23:09:31.476 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectClassStructure.loadClassAnnotations(ReflectKotlinClass.kt:84)
23:09:31.476 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectKotlinClass.loadClassAnnotations(ReflectKotlinClass.kt:67)
23:09:31.476 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader.loadClassAnnotations(AbstractBinaryClassAnnotationAndConstantLoader.kt:80)
23:09:31.476 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$annotations$1.invoke(DeserializedClassDescriptor.kt:82)
23:09:31.476 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$annotations$1.invoke(DeserializedClassDescriptor.kt:34)
23:09:31.476 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:352)
23:09:31.476 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:408)
23:09:31.476 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.storage.StorageKt.getValue(storage.kt:42)
23:09:31.476 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedAnnotations.getAnnotations(DeserializedAnnotations.kt)
23:09:31.476 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedAnnotations.iterator(DeserializedAnnotations.kt:32)
23:09:31.476 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.UtilKt.computeAnnotations(util.kt:208)
23:09:31.476 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.KClassImpl$Data$annotations$2.invoke(KClassImpl.kt:56)
23:09:31.476 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.KClassImpl$Data$annotations$2.invoke(KClassImpl.kt:44)
23:09:31.477 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
23:09:31.477 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
23:09:31.477 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.KClassImpl$Data.getAnnotations(KClassImpl.kt)
23:09:31.477 [DEBUG] [TestEventLogger]          at kotlin.reflect.jvm.internal.KClassImpl.getAnnotations(KClassImpl.kt:181)
23:09:31.477 [DEBUG] [TestEventLogger]          at io.kotest.mpp.FqnKt.annotations(fqn.kt:10)
23:09:31.477 [DEBUG] [TestEventLogger]          at io.kotest.core.spec.DescriptionsKt.description(descriptions.kt:28)
23:09:31.477 [DEBUG] [TestEventLogger]          at io.kotest.core.engine.IsolationTestEngineListener.specStarted(IsolationTestEngineListener.kt:87)
23:09:31.477 [DEBUG] [TestEventLogger]          at io.kotest.core.engine.SpecExecutor.notifySpecStarted(SpecExecutor.kt:46)
23:09:31.477 [DEBUG] [TestEventLogger]          at io.kotest.core.engine.SpecExecutor.execute(SpecExecutor.kt:29)
23:09:31.477 [DEBUG] [TestEventLogger]          at io.kotest.core.engine.KotestEngine$submitBatch$$inlined$forEach$lambda$1$1.invokeSuspend(KotestEngine.kt:68)
23:09:31.477 [DEBUG] [TestEventLogger]          at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
23:09:31.477 [DEBUG] [TestEventLogger]          at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
23:09:31.477 [DEBUG] [TestEventLogger]          at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:271)
23:09:31.477 [DEBUG] [TestEventLogger]          at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
23:09:31.477 [DEBUG] [TestEventLogger]          at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
23:09:31.477 [DEBUG] [TestEventLogger]          at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
23:09:31.478 [DEBUG] [TestEventLogger]          at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
23:09:31.478 [DEBUG] [TestEventLogger]          at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
23:09:31.478 [DEBUG] [TestEventLogger]          at io.kotest.core.engine.KotestEngine$submitBatch$$inlined$forEach$lambda$1.run(KotestEngine.kt:67)
23:09:31.478 [DEBUG] [TestEventLogger]          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
23:09:31.478 [DEBUG] [TestEventLogger]          at java.util.concurrent.FutureTask.run(FutureTask.java:266)
23:09:31.478 [DEBUG] [TestEventLogger]          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
23:09:31.478 [DEBUG] [TestEventLogger]          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
23:09:31.478 [DEBUG] [TestEventLogger]          at java.lang.Thread.run(Thread.java:748)
```

**Comment by sksamuel** [comment]
Fixed in master and will be included in beta3.
