### ISSUE TITLE
Kotest fails with 

### ISSUE THREAD

**Issue by imanushin** [kotest/kotest#1257]
**Steps to reproduce:**
1. Create gradle project with ~30 subprojects
2. Add 10-100 tests into the each subproject.
3. Start testing via ```.\gradlew.bat build --parallel```

As the result, the following callstack is received (please check below).

Actually this is flacky issue: it isn't reproduces on some machines, however it is stable on other.
```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996)
	at io.kotest.runner.junit5.JUnitTestEngineListener.findChildFailure(JUnitTestEngineListener.kt:252)
	at io.kotest.runner.junit5.JUnitTestEngineListener.testFinished(JUnitTestEngineListener.kt:193)
	at io.kotest.core.engine.IsolationTestEngineListener.testFinished(IsolationTestEngineListener.kt:78)
	at io.kotest.core.engine.SingleInstanceSpecRunner$runTest$testExecutor$1.testFinished(SingleInstanceSpecRunner.kt:59)
	at io.kotest.core.runtime.TestExecutor.execute(TestExecutor.kt:57)
	at io.kotest.core.runtime.TestExecutor$execute$1.invokeSuspend(TestExecutor.kt)
	at    (Coroutine boundary. ( )
	at io.kotest.core.runtime.ReplayKt.replay(replay.kt:18)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996)
	at io.kotest.runner.junit5.JUnitTestEngineListener.findChildFailure(JUnitTestEngineListener.kt:252)
	at io.kotest.runner.junit5.JUnitTestEngineListener.testFinished(JUnitTestEngineListener.kt:193)
	at io.kotest.core.engine.IsolationTestEngineListener.testFinished(IsolationTestEngineListener.kt:78)
	at io.kotest.core.engine.SingleInstanceSpecRunner$runTest$testExecutor$1.testFinished(SingleInstanceSpecRunner.kt:59)
	at io.kotest.core.runtime.TestExecutor.execute(TestExecutor.kt:57)
	at io.kotest.core.runtime.TestExecutor$execute$1.invokeSuspend(TestExecutor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:271)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.core.runtime.ExecutorExecutionContext$executeWithTimeoutInterruption$$inlined$suspendCoroutine$lambda$2.run(ExecutorExecutionContext.kt:61)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sksamuel** [comment]
Fixed in master.
