### ISSUE TITLE
Data-driven tests: `row` fails when using unsigned integer types

### ISSUE THREAD

**Issue by krzema12** [kotest/kotest#1287]
Such test:

```kotlin
"two parameters per row" {
    forAll(
        row(0x00u, 0x00)
    ) { inputByte, someNumber ->
        // some assertions
    }
}
```

fails with

```
Test failed for (inputByte, 0), (someNumber, 0) with error java.lang.ClassCastException: kotlin.UInt cannot be cast to java.lang.Number
java.lang.AssertionError: Test failed for (inputByte, 0), (someNumber, 0) with error java.lang.ClassCastException: kotlin.UInt cannot be cast to java.lang.Number
	at it.krzeminski.kotlin.midi.VariableLengthQuantityReadingTest$1$3.invokeSuspend(VariableLengthQuantityReadingTest.kt:37)
	at it.krzeminski.kotlin.midi.VariableLengthQuantityReadingTest$1$3.invoke(VariableLengthQuantityReadingTest.kt)
	at io.kotest.core.runtime.ExecutionsKt$executeWithTimeout$2$2.invokeSuspend(executions.kt:18)
	at io.kotest.core.runtime.ExecutionsKt$executeWithTimeout$2$2.invoke(executions.kt)
	at io.kotest.core.AsserterKt.executeWithGlobalAssertSoftlyCheck(Asserter.kt:37)
	at io.kotest.core.AsserterKt.executeWithAssertionsCheck(Asserter.kt:18)
	at io.kotest.core.runtime.ExecutionsKt$executeWithTimeout$2.invokeSuspend(executions.kt:17)
	at io.kotest.core.runtime.ExecutionsKt$executeWithTimeout$2.invoke(executions.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:78)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:31)
	at io.kotest.core.runtime.ExecutionsKt.executeWithTimeout--MKxnPQ(executions.kt:13)
	at io.kotest.core.runtime.TestExecutor$invokeTestCase$$inlined$invoke$lambda$1$1$4.invokeSuspend(TestExecutor.kt:184)
	at io.kotest.core.runtime.TestExecutor$invokeTestCase$$inlined$invoke$lambda$1$1$4.invoke(TestExecutor.kt)
	at io.kotest.core.runtime.ReplayKt.replay(replay.kt:18)
	at io.kotest.core.runtime.TestExecutor$invokeTestCase$$inlined$invoke$lambda$1$1.invokeSuspend(TestExecutor.kt:179)
	at io.kotest.core.runtime.TestExecutor$invokeTestCase$$inlined$invoke$lambda$1$1.invoke(TestExecutor.kt)
	at io.kotest.core.runtime.ExecutorExecutionContext$executeWithTimeoutInterruption$$inlined$suspendCoroutine$lambda$2$1.invokeSuspend(ExecutorExecutionContext.kt:61)
	(Coroutine boundary)
	at io.kotest.core.runtime.ReplayKt.replay(replay.kt:18)
Caused by: java.lang.AssertionError: Test failed for (inputByte, 0), (someNumber, 0) with error java.lang.ClassCastException: kotlin.UInt cannot be cast to java.lang.Number
	at it.krzeminski.kotlin.midi.VariableLengthQuantityReadingTest$1$3.invokeSuspend(VariableLengthQuantityReadingTest.kt:37)
	at it.krzeminski.kotlin.midi.VariableLengthQuantityReadingTest$1$3.invoke(VariableLengthQuantityReadingTest.kt)
	at io.kotest.core.runtime.ExecutionsKt$executeWithTimeout$2$2.invokeSuspend(executions.kt:18)
	at io.kotest.core.runtime.ExecutionsKt$executeWithTimeout$2$2.invoke(executions.kt)
	at io.kotest.core.AsserterKt.executeWithGlobalAssertSoftlyCheck(Asserter.kt:37)
	at io.kotest.core.AsserterKt.executeWithAssertionsCheck(Asserter.kt:18)
	at io.kotest.core.runtime.ExecutionsKt$executeWithTimeout$2.invokeSuspend(executions.kt:17)
	at io.kotest.core.runtime.ExecutionsKt$executeWithTimeout$2.invoke(executions.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:78)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:31)
	at io.kotest.core.runtime.ExecutionsKt.executeWithTimeout--MKxnPQ(executions.kt:13)
	at io.kotest.core.runtime.TestExecutor$invokeTestCase$$inlined$invoke$lambda$1$1$4.invokeSuspend(TestExecutor.kt:184)
	at io.kotest.core.runtime.TestExecutor$invokeTestCase$$inlined$invoke$lambda$1$1$4.invoke(TestExecutor.kt)
	at io.kotest.core.runtime.ReplayKt.replay(replay.kt:18)
	at io.kotest.core.runtime.TestExecutor$invokeTestCase$$inlined$invoke$lambda$1$1.invokeSuspend(TestExecutor.kt:179)
	at io.kotest.core.runtime.TestExecutor$invokeTestCase$$inlined$invoke$lambda$1$1.invoke(TestExecutor.kt)
	at io.kotest.core.runtime.ExecutorExecutionContext$executeWithTimeoutInterruption$$inlined$suspendCoroutine$lambda$2$1.invokeSuspend(ExecutorExecutionContext.kt:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.core.runtime.ExecutorExecutionContext$executeWithTimeoutInterruption$$inlined$suspendCoroutine$lambda$2.run(ExecutorExecutionContext.kt:61)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I checked that these variants work fine:
* when `0x00u` changed to a regular integer `0x00`
* when just one element per row, of type `UByte`

Unsigned integer types are experimental since Kotlin 1.3, so I don't expect them to work perfectly. However, this issue is a blocker for me to try out kotest in my new project.

Kotlin version: 1.3.70
Kotest version: `io.kotest:kotest-runner-junit5-jvm:4.0.0-BETA2`
A runnable example: https://github.com/krzema12/kotlin-midi/blob/kotest-unsigned-int-issue/src/jvmTest/kotlin/KotestUnsignedIntegersIssueTest.kt#L6

Thanks,
Piotr

**Comment by krzema12** [comment]
After stepping through kotest code with the debugger:

```kotlin
inline fun <A, B> Table2<A, B>.forAll(fn: (A, B) -> Unit) {
   val collector = ErrorCollector()
   for (row in rows) {
      try {
         fn(row.a, row.b) // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<< it throws here
      } catch (e: Throwable) {
         collector += error(e, headers.values(), row.values())
      }
   }
   collector.assertAll()
}
```

Something remotely related (the same exception message) was already reported in https://youtrack.jetbrains.com/issue/KT-27948 - see the comments.

I suspect it's actually Kotlin's fault. If we manage to create a simple, self-contained example that proves Kotlin failing on its own, I'll report a bug for Kotlin. I just need to wrap my head around the issue and isolate it properly. Not sure yet if it's strictly related to e.g. coroutines or not.

**Comment by krzema12** [comment]
Got such minimal example so far:

```kotlin
import kotlinx.coroutines.runBlocking

fun main() {
    runBlocking {
        forAll(Pair(0xFFFFFFu, 0x00)) { _, _  -> }
    }
}

suspend fun <A, B> forAll(row: Pair<A, B>, fn: suspend (A, B) -> Unit) {
    fn(row.first, row.second)
}
```

Works fine if either no coroutines, no unsigned int types or no generics are used. Looks like coroutines + unsigned types + generics = `ClassCastException`.

Reproducible in Kotlin Playground: https://pl.kotl.in/hTengAsjX
Reported as a bug in Kotlin: https://youtrack.jetbrains.com/issue/KT-37500

Even though it seems like a bug in Kotlin, I suggest keeping this issue open until the bug is fixed, to avoid confusion like mine when using kotest.

**Comment by sksamuel** [comment]
Ok good find.

**Comment by krzema12** [comment]
It's a known bug, see https://youtrack.jetbrains.com/issue/KT-32793. I encourage you to +1 it.

**Comment by sksamuel** [comment]
Upvoted.

**Comment by sksamuel** [comment]
Closing as not a kotest issue.
