### ISSUE TITLE
Assertion diff not appearing in intellij

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1310]
```kotlin
io.kotest.assertions.MultiAssertionError: 
The following 2 assertions failed:
1) expected:<<empty string>> but was:<InStock>
	at xxxxx$1$1.invokeSuspend(yyy.kt:67)
2) expected:<<empty string>> but was:<OutOfStock>
	at xxxxx$1$1.invokeSuspend(yyy.kt:91)
```

**Comment by sksamuel** [comment]
Seems to work for strings ok.
