### ISSUE TITLE
Cannot use Kotest with modules from Java 9 

### ISSUE THREAD

**Issue by Patresss** [kotest/kotest#1495]
Kotest version: 4.0.6

I cannot use Kotest with modules from Java 9. Could you rename the packages from modules:
- io.kotest.matchers
- - kotest.assertions.core.jvm
- - kotest.assertions.jvm
- io.kotlintest
- - kotest.core.jvm 
- - kotest.assertions.jvm

I also create a question on stackoverflow: https://stackoverflow.com/questions/62237354/external-modules-a-and-b-export-package-some-package-to-module-c-in-java-9?noredirect=1#comment110077541_62237354

I am able to run tests using Intellij (run button), but I cannot using glradew test

Logs:
```
P:\Programowanie\Projekty\AutomationBoot>gradlew build

> Configure project :
Found module name 'automationBoot'

> Task :compileJava FAILED
error: the unnamed module reads package io.kotest.matchers from both kotest.assertions.core.jvm and kotest.assertions.jvm
error: the unnamed module reads package io.kotlintest from both kotest.core.jvm and kotest.assertions.jvm
error: module kotlin.stdlib reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module kotlin.stdlib reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module commons.lang3 reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module commons.lang3 reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module jnativehook reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module jnativehook reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module opencv reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module opencv reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module javafx.controlsEmpty reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module javafx.controlsEmpty reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module javafx.graphicsEmpty reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module javafx.graphicsEmpty reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module javafx.baseEmpty reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module javafx.baseEmpty reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module kotest.runner.junit5.jvm reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module kotest.runner.junit5.jvm reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module kotest.assertions.core.jvm reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module kotest.assertions.core.jvm reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module kotlinx.coroutines.core reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module kotlinx.coroutines.core reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module kotest.core.jvm reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module kotest.core.jvm reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module kotlin.stdlib.jdk8 reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module kotlin.stdlib.jdk8 reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module kotlin.stdlib.jdk7 reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module kotlin.stdlib.jdk7 reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module slf4j.log4j12 reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module slf4j.log4j12 reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module log4j reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module log4j reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module org.apache.commons.io reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module org.apache.commons.io reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module kotest.extensions.jvm reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module kotest.extensions.jvm reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module kotest.assertions.jvm reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module kotest.assertions.jvm reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module kotlin.stdlib.common reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module kotlin.stdlib.common reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module annotations reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module annotations reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module kotest.fp.jvm reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module kotest.fp.jvm reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module jackson.module.kotlin reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module jackson.module.kotlin reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module kotlin.reflect reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module kotlin.reflect reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
error: module slf4j.api reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
error: module slf4j.api reads package io.kotlintest from both kotest.assertions.jvm and kotest.core.jvm
P:\Programowanie\Projekty\AutomationBoot\src\main\java\module-info.java:1: error: module automationBoot reads package io.kotest.matchers from both kotest.assertions.jvm and kotest.assertions.core.jvm
module automationBoot {
^
51 errors

FAILURE: Build failed with an exception.
```

**Comment by sksamuel** [comment]
I use java 11 fine. Have you tried that?

**Comment by Patresss** [comment]
Yes, I also use Java 11. I put Java 9 because it introduced modules

**Comment by sksamuel** [comment]
Can you try master. The io.kotlintest packages are gone from master.

**Comment by Patresss** [comment]
I think that I used master 4.0.6 when I just run `gradlew build` I get:
```
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module kotest.assertions.core.jvm contains package io.kotest.matchers, module kotest.assertions.jvm exports package io.kotest.matchers to kotest.assertions.core.jvm
Process 'Gradle Test Executor 151' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 151' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:396)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:139)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:42)
        at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:92)
        at jdk.internal.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy77.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:212)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:341)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:109)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:83)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:834)
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module kotest.assertions.core.jvm contains package io.kotest.matchers, module kotest.assertions.jvm exports package io.kotest.matchers to kotest.assertions.core.jvm

```

**Comment by Patresss** [comment]
@sksamuel I prepared a repository to reproduce: https://github.com/Patresss/KotestModule
Please just run the build task from the gradle. When I remove module-info.java it works.

**Comment by sksamuel** [comment]
I get this:

```
sam@sam-linux:~/development/workspace/KotestModule$ ./gradlew check
Downloading https://services.gradle.org/distributions/gradle-6.3-bin.zip
.........10%..........20%..........30%.........40%..........50%..........60%.........70%..........80%..........90%..........100%
Starting a Gradle Daemon, 7 incompatible Daemons could not be reused, use --status for details

> Configure project :
Found module name 'kotestModule'

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> The value for task ':compileJava' property 'destinationDirectory' is final and cannot be changed any further.

```

**Comment by Patresss** [comment]
Please use gradle version max 6.0.1 (I use 6.0.1) due to https://github.com/beryx/badass-jlink-plugin/issues/116

**Comment by Patresss** [comment]
@sksamuel Please ignore the above comment - I updated the badass-jlink-plugin version so the gradle issue should be fixed. 
`The value for task ':compileJava' property 'destinationDirectory' is final and cannot be changed any further.`
https://github.com/beryx/badass-jlink-plugin/issues/116#issuecomment-640283892

**Comment by sksamuel** [comment]
I get the same error as you now.
I'm not sure how to fix this, because I believe this is caused by kotlin multiplatform projects.

**Comment by Patresss** [comment]
I do not think that it is related to the kotlin multiplatform projects. As I understand, when we use modules we can not use packages with the same name.

![image](https://user-images.githubusercontent.com/14001334/83982146-5c427f00-a924-11ea-821e-620638b6b483.png)

https://stackoverflow.com/a/46278159/4952942
> two modules (module-a and module-b in your case) contain the same package (some.package). The module system does not allow that. If you place both modules on the module path, you will get this error regardless of whether the package is exported or whether a third module depends on the other two.

So, I would suggest renaming one of the packages (however, this may result in a lack of backward compatibility)

**Comment by sksamuel** [comment]
Yeah but with Kotlin MPP you can't just rename them because you implement platform specific code by use of actual / expect keywords for functions in the same package.

For example:

Inside commonMain

![image](https://user-images.githubusercontent.com/743706/83983589-3782e300-a8f5-11ea-8040-7081264d6136.png)

Inside jsMain
![image](https://user-images.githubusercontent.com/743706/83983574-2b972100-a8f5-11ea-924d-68d6ca399cf8.png)

**Comment by Patresss** [comment]
Oh, I see what you mean. Thank you for looking at this! Is there a chance to fix it in a known future? I'm asking because I don't know what to do with my project (wait or temporarily remove the library)

**Comment by sksamuel** [comment]
I guess the fix is more with jetbrains to make mpp work with modules.

**Comment by sksamuel** [comment]
Reading up on it we might be able to make it work. It seems with modules you can't have packages split across multiple modules.

**Comment by Burtan** [comment]
This issue is still valid. However you can now use gradle 6.6.1 with gradle plugin de.jjohannes.extra-java-module-info. You just have to add the needed module infos:

```
extraJavaModuleInfo {
    automaticModule("kotest-runner-junit5-jvm-4.3.0.jar", "")
    automaticModule("kotest-assertions-api-jvm-4.3.0.jar", "")
    automaticModule("kotest-assertions-core-jvm-4.3.0.jar", "")
    automaticModule("kotest-assertions-shared-jvm-4.3.0.jar", "")
    automaticModule("kotest-common-jvm-4.3.0.jar", "")
    automaticModule("kotest-framework-engine-jvm-4.3.0.jar", "")
    automaticModule("kotest-framework-api-jvm-4.3.0.jar", "")
    automaticModule("kotest-framework-discovery-jvm-4.3.0.jar", "")
    automaticModule("kotest-extensions-jvm-4.3.0.jar", "")
    automaticModule("kotlinx-coroutines-core-jvm-1.3.9.jar", "")
}
```

It would still be much better when the jars would contain module-info.class or at least an automaticModule name.
