### ISSUE TITLE
java.lang.NoSuchMethodError: 'double kotlin.time.Duration$Companion.getZERO-UwyO8pc()'

### ISSUE THREAD

**Issue by overfullstack** [kotest/kotest#1509]
I have been getting this exception `java.lang.NoSuchMethodError: 'double kotlin.time.Duration$Companion.getZERO-UwyO8pc()'` when running any test with Kotest. 
I am on Gradle 6.5, Kotlin 1.4-M2, and using the latest snapshots of Kotest (4.1.0-324-SNAPSHOT).

**Comment by sksamuel** [comment]
Do you have a full stack trace? Would be handy to know where in the kotest
codebase this occurs.

**Comment by overfullstack** [comment]
java.lang.NoSuchMethodError: 'double kotlin.time.Duration$Companion.getZERO-UwyO8pc()'
          at kotlinx.coroutines.DelayKt.toDelayMillis-LRDsOJo(Delay.kt:101)
          at kotlinx.coroutines.TimeoutKt.withTimeout-lwyi7ZQ(Timeout.kt:58)
          at io.kotest.core.runtime.TestExecutor.executeAndWait(TestExecutor.kt:180)
          at io.kotest.core.runtime.TestExecutor.invokeTestCase(TestExecutor.kt:149)
          at io.kotest.core.runtime.TestExecutor.executeActiveTest(TestExecutor.kt:118)
          at io.kotest.core.runtime.TestExecutor$intercept$2.invokeSuspend(TestExecutor.kt:75)
          at io.kotest.core.runtime.TestExecutor$intercept$2.invoke(TestExecutor.kt)
          at io.kotest.core.runtime.TestExecutor.executeIfActive(TestExecutor.kt:87)
          at io.kotest.core.runtime.TestExecutor.intercept(TestExecutor.kt:75)
          at io.kotest.core.runtime.TestExecutor.execute(TestExecutor.kt:56)
          at io.kotest.core.engine.SingleInstanceSpecRunner.runTest(SingleInstanceSpecRunner.kt:59)
          at io.kotest.core.engine.SingleInstanceSpecRunner$execute$2$invokeSuspend$$inlined$invoke$lambda$1.invokeSuspend(SingleInstanceSpecRunner.kt:69)
          at io.kotest.core.engine.SingleInstanceSpecRunner$execute$2$invokeSuspend$$inlined$invoke$lambda$1.invoke(SingleInstanceSpecRunner.kt)
          at io.kotest.core.engine.SpecRunner$runParallel$$inlined$map$lambda$1$1.invokeSuspend(SpecRunner.kt:51)
          at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
          at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
          at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
          at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
          at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
          at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
          at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
          at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
          at io.kotest.core.engine.SpecRunner$runParallel$$inlined$map$lambda$1.run(SpecRunner.kt:50)
          at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
          at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
          at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
          at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
          at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by sksamuel** [comment]
Great thank you

**Comment by sksamuel** [comment]
Fixed in master.
