### ISSUE TITLE
TestEngine with ID 'kotest' failed to execute tests

### ISSUE THREAD

**Issue by niraj8** [kotest/kotest#1541]
**Which version of Kotest are you using**
4.1.1

**kotlin version**
1.3.72

<details>
<summary>Stack trace</summary>

```
TestEngine with ID 'kotest' failed to execute tests
org.junit.platform.commons.JUnitException: TestEngine with ID 'kotest' failed to execute tests
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:254)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: io.kotest.runner.junit.platform.JUnitTestEngineListener.<init>(Lorg/junit/platform/engine/EngineExecutionListener;Lorg/junit/platform/engine/support/descriptor/EngineDescriptor;)V
	at io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine.execute(KotestJunitPlatformTestEngine.kt:39)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	... 33 more

```
</details>

**Comment by niraj8** [comment]
Switching to kotest 4.0.3 fixed this for me

**Comment by sksamuel** [comment]
This looks like a junit version mismatch. Are you specifying junit platform anywhere in your build?

**Comment by niraj8** [comment]
I thought so too, but just downgrading fixed the error
Here are all the JUnit related dependencies in the project

![image](https://user-images.githubusercontent.com/8666468/86478652-33b57580-bd68-11ea-89fc-2e8157f4a2a6.png)

**Comment by sksamuel** [comment]
junit-jupiter-engine needs to be 5.6 which is what kotest declares.
Something is bringing in that 5.1 version and causing this error.
Perhaps the micronaut test.

**Comment by niraj8** [comment]
Upgrading jupiter to 5.6.0 and kotest to 4.1.1 resulted in the same error

**Comment by sksamuel** [comment]
Can you check your dependencies list and take another screenshot. I suspect
there's an old version still lurking.

**Comment by niraj8** [comment]
- `micronaut-test-kotest:1.2.0` depends on `io.kotest:kotest-runner-junit5-jvm:4.0.3`
- As you said earlier, this seems to be the problem as the modules where the tests are running fine have the version in dependency list as 4.1.1

- I have tried adding `testImplementaton "io.kotest:kotest-runner-junit5-jvm:4.1.1"` explicitly, but for some reason the version mentioned in micronaut-test takes precedence.

- `gradle dependencies` for the module lists this for the dependency
`io.kotest:kotest-runner-junit5-jvm:4.1.1 -> 4.0.3`

- Do you think this is related to this issue in gradle(https://github.com/gradle/gradle/issues/7317)?

![image](https://user-images.githubusercontent.com/8666468/86496250-1b5e4e80-bd9a-11ea-99cb-21cb93b6d5e8.png)

**Comment by sksamuel** [comment]
Yes could be that. You can do version overrides in gradle manually, which
would fix it for you.

**Comment by sksamuel** [comment]
https://stackoverflow.com/a/46404627/2048448

**Comment by niraj8** [comment]
> [stackoverflow.com/a/46404627/2048448](https://stackoverflow.com/a/46404627/2048448)

Didn't know about this, it did the trick.
Thank you!
