### ISSUE TITLE
There are transaction error logs when `@DataJpaTest` runs

### ISSUE THREAD

**Issue by veluxer62** [kotest/kotest#1643]
When I runs Spring Data JPA tests, I can see some error logs like below.

```
java.lang.IllegalStateException: Cannot start new transaction without ending existing transaction
	at org.springframework.util.Assert.state(Assert.java:76) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.test.context.transaction.TransactionalTestExecutionListener.beforeTestMethod(TransactionalTestExecutionListener.java:180) ~[spring-test-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.test.context.TestContextManager.beforeTestMethod(TestContextManager.java:289) ~[spring-test-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at io.kotest.spring.SpringListener.beforeAny(SpringListener.kt:38) ~[kotest-extensions-spring-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.CallbacksKt.invokeAllBeforeTestCallbacks(callbacks.kt:77) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor.executeActiveTest(TestCaseExecutor.kt:112) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor$intercept$2.invokeSuspend(TestCaseExecutor.kt:63) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor$intercept$2.invoke(TestCaseExecutor.kt) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor.executeIfActive(TestCaseExecutor.kt:77) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor.intercept(TestCaseExecutor.kt:63) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor.execute(TestCaseExecutor.kt:44) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.engine.InstancePerTestSpecRunner$run$2.invokeSuspend(InstancePerTestSpecRunner.kt:139) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.engine.InstancePerTestSpecRunner$run$2.invoke(InstancePerTestSpecRunner.kt) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at io.kotest.core.engine.InstancePerTestSpecRunner.run(InstancePerTestSpecRunner.kt:104) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.engine.InstancePerTestSpecRunner.interceptAndRun(InstancePerTestSpecRunner.kt:98) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.engine.InstancePerTestSpecRunner.executeInCleanSpec(InstancePerTestSpecRunner.kt:88) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.engine.InstancePerTestSpecRunner$run$2$context$1.registerTestCase(InstancePerTestSpecRunner.kt:120) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor$executeAndWait$2$1$1$3$1$contextp$1.registerTestCase(TestCaseExecutor.kt:187) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.test.TestContext.registerTestCase(TestContext.kt:42) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.spec.style.scopes.ContainerScope$DefaultImpls.addTest(ContainerScope.kt:58) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.spec.style.scopes.FreeScope.addTest(FreeScope.kt:10) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.spec.style.scopes.ContainerScope$DefaultImpls.addContainerTest(ContainerScope.kt:37) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.spec.style.scopes.FreeScope.addContainerTest(FreeScope.kt:10) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.spec.style.scopes.FreeScope.minus(FreeScope.kt:19) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at net.class101.sku.infrastructure.persistence.repository.PackRepositoryTest$1.invokeSuspend(PackRepositoryTest.kt:25) ~[classes/:na]
	at net.class101.sku.infrastructure.persistence.repository.PackRepositoryTest$1.invoke(PackRepositoryTest.kt) ~[classes/:na]
	at io.kotest.core.spec.style.scopes.FreeSpecRootScope$minus$1.invokeSuspend(FreeSpecRootScope.kt:17) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.spec.style.scopes.FreeSpecRootScope$minus$1.invoke(FreeSpecRootScope.kt) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.ExecutionsKt$executeWithBehaviours$2$1.invokeSuspend(executions.kt:15) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.ExecutionsKt$executeWithBehaviours$2$1.invoke(executions.kt) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.ExecutionsKt.wrapTestWithGlobalAssert(executions.kt:41) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.ExecutionsKt$executeWithBehaviours$2.invokeSuspend(executions.kt:14) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.ExecutionsKt$executeWithBehaviours$2.invoke(executions.kt) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.ExecutionsKt.wrapTestWithAssertionModeCheck(executions.kt:25) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.ExecutionsKt.executeWithBehaviours(executions.kt:13) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor$executeAndWait$2$1$1$3$1.invokeSuspend(TestCaseExecutor.kt:190) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor$executeAndWait$2$1$1$3$1.invoke(TestCaseExecutor.kt) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor$executeAndWait$2$1$1$3.invokeSuspend(TestCaseExecutor.kt:184) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor$executeAndWait$2$1$1$3.invoke(TestCaseExecutor.kt) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.ReplayKt.replay(replay.kt:19) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor$executeAndWait$2$1$1.invokeSuspend(TestCaseExecutor.kt:179) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor$executeAndWait$2$1$1.invoke(TestCaseExecutor.kt) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:120) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:37) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor$executeAndWait$2$1.invokeSuspend(TestCaseExecutor.kt:178) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor$executeAndWait$2$1.invoke(TestCaseExecutor.kt) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.ExecutorExecutionContext$executeWithTimeoutInterruption$$inlined$suspendCoroutine$lambda$2.invokeSuspend(ExecutorExecutionContext.kt:44) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at io.kotest.core.runtime.ExecutorExecutionContext.executeWithTimeoutInterruption(ExecutorExecutionContext.kt:43) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor$executeAndWait$2.invokeSuspend(TestCaseExecutor.kt:177) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor$executeAndWait$2.invoke(TestCaseExecutor.kt) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:120) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:37) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor.executeAndWait(TestCaseExecutor.kt:175) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor.invokeTestCase(TestCaseExecutor.kt:144) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor.executeActiveTest(TestCaseExecutor.kt:113) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor$intercept$2.invokeSuspend(TestCaseExecutor.kt:63) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor$intercept$2.invoke(TestCaseExecutor.kt) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor.executeIfActive(TestCaseExecutor.kt:77) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor.intercept(TestCaseExecutor.kt:63) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.runtime.TestCaseExecutor.execute(TestCaseExecutor.kt:44) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.engine.InstancePerTestSpecRunner$run$2.invokeSuspend(InstancePerTestSpecRunner.kt:139) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.engine.InstancePerTestSpecRunner$run$2.invoke(InstancePerTestSpecRunner.kt) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at io.kotest.core.engine.InstancePerTestSpecRunner.run(InstancePerTestSpecRunner.kt:104) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.engine.InstancePerTestSpecRunner.interceptAndRun(InstancePerTestSpecRunner.kt:98) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.engine.InstancePerTestSpecRunner.executeInCleanSpec(InstancePerTestSpecRunner.kt:88) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.engine.InstancePerTestSpecRunner$execute$$inlined$invoke$lambda$1.invokeSuspend(InstancePerTestSpecRunner.kt:67) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.engine.InstancePerTestSpecRunner$execute$$inlined$invoke$lambda$1.invoke(InstancePerTestSpecRunner.kt) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at io.kotest.core.engine.SpecRunner$runParallel$$inlined$map$lambda$2$1.invokeSuspend(SpecRunner.kt:78) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.3.8-1.4.0-rc.jar:na]
	at io.kotest.core.engine.SpecRunner$runParallel$$inlined$map$lambda$2.run(SpecRunner.kt:77) ~[kotest-core-jvm-4.2.0.RC1.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
```

The code below is the one I wrote. And my

```
package com.spring.demo.infrastructure.persistence.repository

import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.shouldBe
import io.kotest.spring.SpringListener
import com.spring.demo.entityFixture
import com.spring.demo.infrastructure.persistence.entity.PackEntity
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager

@DataJpaTest
class PackRepositoryTest : FreeSpec() {

    override fun listeners() = listOf(SpringListener)

    @Autowired
    private lateinit var packRepository: PackRepository

    @Autowired
    private lateinit var testEntityManager: TestEntityManager

    init {
        "save method" - {
            "given entity" - {
                val entity = entityFixture<PackEntity>()
                packRepository.save(entity)
                "persist correctly" {
                    val expected = testEntityManager.find(PackEntity::class.java, entity.getId())
                    entity shouldBe expected
                }
            }
        }
    }
}

object KotestConfig : AbstractProjectConfig() {
    override val parallelism = 3
    override val isolationMode = IsolationMode.InstancePerTest
}
```

**Comment by sksamuel** [comment]
@DataJpaTest isn't something that Kotest understands. That annotation is probably something spring uses to pre-process tests for JPA.

**Comment by veluxer62** [comment]
> @DataJpaTest isn't something that Kotest understands. That annotation is probably something spring uses to pre-process tests for JPA.

Yes, I think so. But I think `SpringListener` should understand `@DataJpaTest`.

In addition, When I write code below.

```
"save test" {
    val entity = entityFixture<PackEntity>()
    packRepository.save(entity)
    val expected = testEntityManager.find(PackEntity::class.java, entity.getId())
    entity shouldBe expected
}
```

It runs without problem.

**Comment by sksamuel** [comment]
It probably needs some kind of reset to work on a second test.
We can leave this open as an enhancement.

**Comment by pauli2406** [comment]
I have experienced the same problem when using Describe Spec()
The following Code Snippet fails with the same exception @veluxer62 posted before.

```
package com.example.demo

import io.kotest.core.spec.IsolationMode
import io.kotest.core.spec.style.DescribeSpec
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.shouldBe
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest
import org.springframework.data.jpa.repository.JpaRepository
import java.util.*
import java.util.UUID.randomUUID

@DataJpaTest
internal class ShoppingOrderSpec : DescribeSpec() {
    @Autowired
    private lateinit var orderRepository: OrderRepository

    override fun listeners() = listOf(SpringListener)
    override fun isolationMode(): IsolationMode = IsolationMode.InstancePerTest

    init {
        describe("Order Entity") {
            it("store and retrieve") {
                val order = ShoppingOrder(randomUUID(), listOf(createOrderLine(), createOrderLine()))

                orderRepository.save(order)

                val saved = orderRepository.findById(order.id).get()

                saved.id shouldBe order.id
                saved.lines shouldHaveSize 2
            }
        }
    }

    private fun createOrderLine() = OrderLine(randomUUID())
}

interface OrderRepository : JpaRepository<ShoppingOrder, UUID>
```

Unfortunately when using describe spec, there is no workaround to avoid this expception. It seems like each layer opens a new transaction or somethin along these lines.

The only way I managed to get it to working was using FreeSpec() instead with only one layer.
Even though this works, it is not really a solution because we want to avoid using different styles of testing within our application.

**Comment by sksamuel** [comment]
Fix in master.
Once 4.2.4 is released this will only invoke the spring annotation magic at the leaf test level.
You can make it work like it is now (so broken for some scenarios) by
`listener(SpringTestListener(SpringTestLifecycleMode.Root))`
