### ISSUE TITLE
Koin extenstion + Behavior spec not working. but String spec working.

### ISSUE THREAD

**Issue by Xinkle** [kotest/kotest#1710]
**Which version of Kotest are you using**
KoTest : 4.2.4
Koin: 2.1.6

I have a unit test for some classes.
The class has koin injection internally

```
abstract class BaseUseCase<T> : KoinComponent {
    val debugLog: (tag: String, log: String) -> Unit by inject(ANDROID_LOGGER)
}
```

and I override the listener according to document
```
    override fun listeners() = listOf(KoinListener(module {
        factory(ANDROID_LOGGER) {
            { tag: String, log: String ->
                println("[$tag]: $log")
            }
        }
    }))
```

and I write test code with behavior spec
```
    init {
        Given("Test") {
            When("Test When") {
                Then("Test Then") {
                    val useCase = AppUpdateUseCase(
                        object : AppUpdateRepository {
                            override suspend fun updateApp(): DataModelResult<String> {
                                return DataModelResult.SUCCESS("test path")
                            }
                            override suspend fun isLatestVersionAvailable(): DataModelResult<Boolean> {
                                return DataModelResult.SUCCESS(false)
                            }
                        }
                    )
                    useCase.update {}
                }
            }
        }
    }
```

But test code not working
```

java.lang.IllegalStateException: A KoinContext is already started
	at org.koin.core.context.KoinContextHandler.register(KoinContextHandler.kt:49)
	at org.koin.core.context.ContextFunctionsKt.startKoin(ContextFunctions.kt:36)
	at org.koin.core.context.ContextFunctionsKt.startKoin$default(ContextFunctions.kt:35)
	at io.kotest.koin.KoinListener.beforeAny(KoinListener.kt:20)
	at io.kotest.core.spec.LifecycleKt.invokeAllBeforeTestCallbacks(lifecycle.kt:73)
	at io.kotest.core.internal.TestCaseExecutor.executeActiveTest(TestCaseExecutor.kt:129)
	at io.kotest.core.internal.TestCaseExecutor$intercept$2.invokeSuspend(TestCaseExecutor.kt:80)
	at io.kotest.core.internal.TestCaseExecutor$intercept$2.invoke(TestCaseExecutor.kt)
	at io.kotest.core.internal.TestCaseExecutor.executeIfActive(TestCaseExecutor.kt:94)
	at io.kotest.core.internal.TestCaseExecutor.intercept(TestCaseExecutor.kt:80)
	at io.kotest.core.internal.TestCaseExecutor.execute(TestCaseExecutor.kt:61)
	at io.kotest.engine.runners.SingleInstanceSpecRunner.runTest(SingleInstanceSpecRunner.kt:73)
	at io.kotest.engine.runners.SingleInstanceSpecRunner$Context.registerTestCase(SingleInstanceSpecRunner.kt:51)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3$1$contextp$1.registerTestCase(TestCaseExecutor.kt:204)
	at io.kotest.core.test.TestContext$DefaultImpls.registerTestCase(TestContext.kt:39)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3$1$contextp$1.registerTestCase(TestCaseExecutor.kt:202)
	at io.kotest.core.spec.style.scopes.ContainerScope$DefaultImpls.addTest(ContainerScope.kt:64)
	at io.kotest.core.spec.style.scopes.GivenScope.addTest(GivenScope.kt:28)
	at io.kotest.core.spec.style.scopes.ContainerScope$DefaultImpls.addContainerTest(ContainerScope.kt:43)
	at io.kotest.core.spec.style.scopes.GivenScope.addContainerTest(GivenScope.kt:28)
	at io.kotest.core.spec.style.scopes.GivenScope.addWhen(GivenScope.kt:61)
	at io.kotest.core.spec.style.scopes.GivenScope.When(GivenScope.kt:54)
	at com.samsung.android.runestone.domain.usecases.AppUpdateUseCaseTest$1.invokeSuspend(AppUpdateUseCaseTest.kt:24)
	at com.samsung.android.runestone.domain.usecases.AppUpdateUseCaseTest$1.invoke(AppUpdateUseCaseTest.kt)
	at io.kotest.core.spec.style.scopes.BehaviorSpecRootScope$addGiven$1.invokeSuspend(BehaviorSpecRootScope.kt:38)
	at io.kotest.core.spec.style.scopes.BehaviorSpecRootScope$addGiven$1.invoke(BehaviorSpecRootScope.kt)
	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2$1.invokeSuspend(executions.kt:13)
	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2$1.invoke(executions.kt)
	at io.kotest.core.internal.ExecutionsKt.wrapTestWithGlobalAssert(executions.kt:39)
	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2.invokeSuspend(executions.kt:12)
	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2.invoke(executions.kt)
	at io.kotest.core.internal.ExecutionsKt.wrapTestWithAssertionModeCheck(executions.kt:23)
	at io.kotest.core.internal.ExecutionsKt.executeWithBehaviours(executions.kt:11)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3$1.invokeSuspend(TestCaseExecutor.kt:207)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3$1.invoke(TestCaseExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:180)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3.invokeSuspend(TestCaseExecutor.kt:201)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3.invoke(TestCaseExecutor.kt)
	at io.kotest.mpp.ReplayKt.replay(replay.kt:18)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1.invokeSuspend(TestCaseExecutor.kt:196)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1.invoke(TestCaseExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:78)
	at kotlinx.coroutines.TimeoutKt.access$setupTimeout(Timeout.kt:1)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:31)

	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1.invokeSuspend(TestCaseExecutor.kt:195)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.ExecutorExecutionContext$executeWithTimeoutInterruption$$inlined$suspendCoroutine$lambda$2.invokeSuspend(ExecutorExecutionContext.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.engine.ExecutorExecutionContext.executeWithTimeoutInterruption(ExecutorExecutionContext.kt:45)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2.invokeSuspend(TestCaseExecutor.kt:194)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2.invoke(TestCaseExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:78)
	at kotlinx.coroutines.TimeoutKt.access$setupTimeout(Timeout.kt:1)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:31)
	at io.kotest.core.internal.TestCaseExecutor.executeAndWait(TestCaseExecutor.kt:192)
	at io.kotest.core.internal.TestCaseExecutor.invokeTestCase(TestCaseExecutor.kt:161)
	at io.kotest.core.internal.TestCaseExecutor.executeActiveTest(TestCaseExecutor.kt:130)
	at io.kotest.core.internal.TestCaseExecutor$intercept$2.invokeSuspend(TestCaseExecutor.kt:80)
	at io.kotest.core.internal.TestCaseExecutor$intercept$2.invoke(TestCaseExecutor.kt)
	at io.kotest.core.internal.TestCaseExecutor.executeIfActive(TestCaseExecutor.kt:94)
	at io.kotest.core.internal.TestCaseExecutor.intercept(TestCaseExecutor.kt:80)
	at io.kotest.core.internal.TestCaseExecutor.execute(TestCaseExecutor.kt:61)
	at io.kotest.engine.runners.SingleInstanceSpecRunner.runTest(SingleInstanceSpecRunner.kt:73)
	at io.kotest.engine.runners.SingleInstanceSpecRunner$execute$2$invokeSuspend$$inlined$invoke$lambda$1.invokeSuspend(SingleInstanceSpecRunner.kt:83)
	at io.kotest.engine.runners.SingleInstanceSpecRunner$execute$2$invokeSuspend$$inlined$invoke$lambda$1.invoke(SingleInstanceSpecRunner.kt)
	at io.kotest.engine.spec.SpecRunner$runParallel$$inlined$map$lambda$2$1.invokeSuspend(SpecRunner.kt:80)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.engine.spec.SpecRunner$runParallel$$inlined$map$lambda$2.run(SpecRunner.kt:79)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Process finished with exit code 255

A KoinContext is already started
```

But when i replace BehaviorSpec with StringSpec, it works.
```
    init {
        "test"{
            val useCase = AppUpdateUseCase(
                object : AppUpdateRepository {
                    override suspend fun updateApp(): DataModelResult<String> {
                        return DataModelResult.SUCCESS("test path")
                    }

                    override suspend fun isLatestVersionAvailable(): DataModelResult<Boolean> {
                        return DataModelResult.SUCCESS(false)
                    }
                }
            )

            useCase.update {}
        }
    }
```

and also success use the injected lambda function
```
[XK(AppUpdateUseCase.kt:28)#update]: : test
```

**Comment by LeoColman** [comment]
Could you try tweaking your isolation mode around to see if it changes this behavior? It seems to me that the way your test instances are being isolated is messing with Koin context

**Comment by sksamuel** [comment]
This is because, like the spring listener, it creates a new context for
every level of nesting.
We can just do what we did for spring here too.

**Comment by Xinkle** [comment]
@LeoColman How do I tweak isolation mode? sorry for I am a newbie to kotest.

**Comment by Xinkle** [comment]
@LeoColman
Above error message
`at com.samsung.android.runestone.domain.usecases.AppUpdateUseCaseTest$1.invokeSuspend(AppUpdateUseCaseTest.kt:24)`
pointing
`
            When("Test When") {
`

So I think the koin context started at `Given` first, and it is not removed on before `When`. so In conclusion, it will be started double.

And when I use not koinListener, start koin explicitly in the init block like below
```
    init {
        startKoin {
            printLogger()
            modules(
                listOf(
                    module {
                        factory(ANDROID_LOGGER) {
                            { tag: String, log: String ->
                                println("[$tag]: $log")
                            }
                        }
                    }
                )
            )

        }

        Given("Given") {
            When("When") {
                Then("Then") {

                    val useCase = AppUpdateUseCase(
                        object : AppUpdateRepository {
                            override suspend fun updateApp(): DataModelResult<String> {
                                return DataModelResult.SUCCESS("test path")
                            }

                            override suspend fun isLatestVersionAvailable(): DataModelResult<Boolean> {
                                return DataModelResult.SUCCESS(false)
                            }
                        }
                    )

                    useCase.update {}
                }
            }
        }
    }
```

It works successful

:: Update

I got failed whatever isolation mode I set

**Comment by sksamuel** [comment]
4.2.5 has been released which fixes this.
