### ISSUE TITLE
Wrong behavior when combining assertSoftly and shouldNotBe

### ISSUE THREAD

**Issue by PeekAndPoke** [kotest/kotest#1831]
**Which version of Kotest are you using**
4.3.1

**Desription**
Under 'certain' circumstances the combination of `assertSoftly` and `shouldNotBe` show a wrong behavior.

I have an example:

```
enum class SimpleEnum {
    First,
    Second
}
data class WithSimpleEnum(val enumValue: SimpleEnum = SimpleEnum.First)
class AssertSoftlySpec : StringSpec({
    "asserting me softly" {
        val source = WithSimpleEnum(enumValue = SimpleEnum.First)
        val result = WithSimpleEnum(enumValue = SimpleEnum.Second)
        assertSoftly {
            withClue("simple strings") {
                "a" shouldBe "b"
                "a" shouldNotBe "b"
            }
            withClue("more complex with data class and enums") {
                source shouldBe result
                source shouldNotBe result
            }
        }
    }
})
```

The will output:

```
The following 4 assertions failed:
1) simple strings
expected:<"b"> but was:<"a">
	at de.peekandpoke.ultra.AssertSoftlySpec$1$1.invokeSuspend(AssertMeSoftlySpec.kt:26)
2) more complex with data class and enums
expected:<Second> but was:<First>
	at de.peekandpoke.ultra.AssertSoftlySpec$1$1.invokeSuspend(AssertMeSoftlySpec.kt:31)
3) more complex with data class and enums
expected:<WithSimpleEnum(enumValue=Second)> but was:<WithSimpleEnum(enumValue=First)>
	at de.peekandpoke.ultra.AssertSoftlySpec$1$1.invokeSuspend(AssertMeSoftlySpec.kt:31)
4) more complex with data class and enums
expected:<Second> but was:<First>
	at de.peekandpoke.ultra.AssertSoftlySpec$1$1.invokeSuspend(AssertMeSoftlySpec.kt:32)
```

So the situation is: I was **not** able to produce the behaviour with scalar types like strings.

But as you can see, in this part **both assertions fail**, while this should be impossible (or my logic-chip is broken)

```
withClue("more complex with data class and enums") {
    source shouldBe result
    source shouldNotBe result
}
```

**Comment by ashishkujoy** [comment]
Fixed in master

**Comment by sksamuel** [comment]
4.3.2 is released with this fix.
