### ISSUE TITLE
Failure to init test case when using assertSoftly within a test within a context

### ISSUE THREAD

**Issue by ghost** [kotest/kotest#1872]
**Which version of Kotest are you using**
Version: kotest 4.4.0.750-SNAPSHOT

In the code below if the lines for `assertSoftly` are commented out the test will execute correctly.

`class SimpleTest : FunSpec() {

    init {
        defaultTestConfig = TestCaseConfig(enabled = true, tags = setOf(Prd, Stg, Wip, Local))

        val users = listOf("user1", "user2")
        val samplePermissions = mapOf("table" to listOf("SELECT", "UPDATE"))

        context("validate user permissions") {
            users.forEach { user ->
                test("$user should have specific permissions") {
                    assertSoftly {
                        samplePermissions.entries.forEach { (tableName, permissions) ->
                            withClue("$user should only have select access to ${tableName}") { 
                                permissions shouldContainExactlyInAnyOrder listOf("SELECT")
                            } 
                        }
                    }
                }
            }
        }

    }
}`

Error:
`java.lang.VerifyError: Call to wrong <init> method
Exception Details:
  Location:
    com/shoprunner/eddy/qa/api/db/SimpleTest$1$invokeSuspend$$inlined$forEach$lambda$1.invokeSuspend(Ljava/lang/Object;)Ljava/lang/Object; @459: invokespecial
  Reason:
    Type 'com/shoprunner/eddy/qa/api/db/SimpleTest$1$invokeSuspend$$inlined$forEach$lambda$1$3' (constant pool 167) is not assignable to 'com/shoprunner/eddy/qa/api/db/SimpleTest$1$invokeSuspend$$inlined$forEach$lambda$1$1' (constant pool 125)
  Bytecode:
    0000000: b800 294d 2ab4 002b aa00 0000 0000 0249
    0000010: 0000 0000 0000 0000 0000 0014 2bb8 0031
    0000020: 2ab4 0033 4e03 3604 b800 39b9 003f 0100
    0000030: b200 45a6 00fd 0336 052a b400 1ab4 0049
    0000040: b900 4f01 00c0 0051 3a06 0336 0719 06b9
    0000050: 0055 0100 3a08 1908 b900 5b01 0099 00ce
    0000060: 1908 b900 5e01 003a 0919 09c0 0060 3a0a
    0000070: 0336 0b19 0a3a 0c03 360d 190c b900 6301
    0000080: 00c0 0065 3a0e 190a 3a0c 0336 0d19 0cb9
    0000090: 0068 0100 c000 6a3a 0fbb 006c 59b7 006f
    00000a0: 2ab4 0016 b600 7312 75b6 0073 190e b600
    00000b0: 73b6 0079 3a0c 0336 0d19 0c3a 1003 3611
    00000c0: bb00 7b59 1910 b700 7dc0 007f b800 853a
    00000d0: 1203 3613 00b8 0039 bb00 8759 1912 b700
    00000e0: 8ac0 007f b900 8e02 0003 3614 1910 3a15
    00000f0: 0336 1603 3617 190f c000 9012 92b8 0098
    0000100: c000 90b8 009e c000 6a00 3a18 b800 39b9
    0000110: 00a1 0100 a700 103a 18b8 0039 b900 a101
    0000120: 0019 18bf 0000 0000 a7ff 2e00 00a7 011f
    0000130: b800 39b2 0045 b900 a502 0003 3605 2ab4
    0000140: 001a b400 49b9 004f 0100 c000 513a 0603
    0000150: 3607 1906 b900 5501 003a 0819 08b9 005b
    0000160: 0100 9900 ce19 08b9 005e 0100 3a09 1909
    0000170: c000 603a 0a03 360b 190a 3a0c 0336 0d19
    0000180: 0cb9 0063 0100 c000 653a 0e19 0a3a 0c03
    0000190: 360d 190c b900 6801 00c0 006a 3a0f bb00
    00001a0: 6c59 b700 6f2a b400 16b6 0073 1275 b600
    00001b0: 7319 0eb6 0073 b600 793a 0c03 360d 190c
    00001c0: 3a10 0336 11bb 00a7 5919 10b7 007d c000
    00001d0: 7fb8 0085 3a12 0336 1300 b800 39bb 00a9
    00001e0: 5919 12b7 008a c000 7fb9 008e 0200 0336
    00001f0: 1419 103a 1503 3616 0336 1719 0fc0 0090
    0000200: 1292 b800 98c0 0090 b800 9ec0 006a 003a
    0000210: 18b8 0039 b900 a101 00a7 0010 3a18 b800
    0000220: 39b9 00a1 0100 1918 bf00 0000 00a7 ff2e
    0000230: 0000 b200 af3a 1903 361a 0336 1b19 193a
    0000240: 1c03 361d b800 39b8 00b5 0000 00b2 00af
    0000250: b0bb 00b7 5912 b9b7 00bc bf            
  Exception Handler Table:
    bci [212, 268] => handler: 279
    bci [279, 281] => handler: 279
    bci [473, 529] => handler: 540
    bci [540, 542] => handler: 540
  Stackmap Table:
    append_frame(@28,Object[#219])
    full_frame(@86,{Object[#2],Object[#219],Object[#219],Object[#221],Integer,Integer,Object[#81],Integer,Object[#87]},{})
    full_frame(@279,{Object[#2],Object[#219],Object[#219],Object[#221],Integer,Integer,Object[#81],Integer,Object[#87],Object[#219],Object[#96],Integer,Object[#101],Integer,Object[#101],Object[#106],Object[#101],Integer,Object[#223],Integer},{Object[#225]})
    full_frame(@292,{Object[#2],Object[#219],Object[#219],Object[#221],Integer,Integer,Object[#81],Integer,Object[#87],Object[#219],Object[#96],Integer,Object[#101],Integer,Object[#101],Object[#106],Object[#101],Integer,Object[#223],Integer,Integer,Object[#101],Integer,Integer,Object[#106]},{})
    full_frame(@299,{Object[#2],Object[#219],Object[#219],Object[#221],Integer,Integer,Object[#81],Integer,Object[#87]},{})
    full_frame(@304,{Object[#2],Object[#219],Object[#219],Object[#221],Integer},{})
    full_frame(@347,{Object[#2],Object[#219],Object[#219],Object[#221],Integer,Integer,Object[#81],Integer,Object[#87]},{})
    full_frame(@540,{Object[#2],Object[#219],Object[#219],Object[#221],Integer,Integer,Object[#81],Integer,Object[#87],Object[#219],Object[#96],Integer,Object[#101],Integer,Object[#101],Object[#106],Object[#101],Integer,Object[#223],Integer},{Object[#225]})
    full_frame(@553,{Object[#2],Object[#219],Object[#219],Object[#221],Integer,Integer,Object[#81],Integer,Object[#87],Object[#219],Object[#96],Integer,Object[#101],Integer,Object[#101],Object[#106],Object[#101],Integer,Object[#223],Integer,Integer,Object[#101],Integer,Integer,Object[#106]},{})
    full_frame(@560,{Object[#2],Object[#219],Object[#219],Object[#221],Integer,Integer,Object[#81],Integer,Object[#87]},{})
    same_frame(@588)
    full_frame(@593,{Object[#2],Object[#219],Object[#219]},{})

	at com.shoprunner.eddy.qa.api.db.SimpleTest$1.invokeSuspend(SimpleTest.kt:23)
	at com.shoprunner.eddy.qa.api.db.SimpleTest$1.invoke(SimpleTest.kt)
	at io.kotest.core.spec.style.scopes.FunSpecRootScope$context$1.invokeSuspend(FunSpecRootScope.kt:15)
	at io.kotest.core.spec.style.scopes.FunSpecRootScope$context$1.invoke(FunSpecRootScope.kt)
	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2$1.invokeSuspend(executions.kt:13)
	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2$1.invoke(executions.kt)
	at io.kotest.core.internal.ExecutionsKt.wrapTestWithGlobalAssert(executions.kt:39)
	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2.invokeSuspend(executions.kt:12)
	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2.invoke(executions.kt)
	at io.kotest.core.internal.ExecutionsKt.wrapTestWithAssertionModeCheck(executions.kt:23)
	at io.kotest.core.internal.ExecutionsKt.executeWithBehaviours(executions.kt:11)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3$1.invokeSuspend(TestCaseExecutor.kt:222)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3$1.invoke(TestCaseExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3.invokeSuspend(TestCaseExecutor.kt:216)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3.invoke(TestCaseExecutor.kt)
	at io.kotest.mpp.ReplayKt.replay(replay.kt:18)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1.invokeSuspend(TestCaseExecutor.kt:211)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1.invoke(TestCaseExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:120)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:37)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1.invokeSuspend(TestCaseExecutor.kt:210)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.ExecutorExecutionContext$executeWithTimeoutInterruption$$inlined$suspendCoroutine$lambda$2.invokeSuspend(ExecutorExecutionContext.kt:56)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at io.kotest.engine.ExecutorExecutionContext.executeWithTimeoutInterruption(ExecutorExecutionContext.kt:55)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2.invokeSuspend(TestCaseExecutor.kt:209)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2.invoke(TestCaseExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:120)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:37)
	at io.kotest.core.internal.TestCaseExecutor.executeAndWait(TestCaseExecutor.kt:207)
	at io.kotest.core.internal.TestCaseExecutor.invokeTestCase(TestCaseExecutor.kt:176)
	at io.kotest.core.internal.TestCaseExecutor.executeActiveTest(TestCaseExecutor.kt:145)
	at io.kotest.core.internal.TestCaseExecutor$intercept$innerExecute$1$1.invokeSuspend(TestCaseExecutor.kt:83)
	at io.kotest.core.internal.TestCaseExecutor$intercept$innerExecute$1$1.invoke(TestCaseExecutor.kt)
	at io.kotest.core.internal.TestCaseExecutor.executeIfActive(TestCaseExecutor.kt:109)
	at io.kotest.core.internal.TestCaseExecutor$intercept$innerExecute$1.invokeSuspend(TestCaseExecutor.kt:83)
	at io.kotest.core.internal.TestCaseExecutor$intercept$innerExecute$1.invoke(TestCaseExecutor.kt)
	at io.kotest.core.internal.TestCaseExecutor.intercept(TestCaseExecutor.kt:97)
	at io.kotest.core.internal.TestCaseExecutor.execute(TestCaseExecutor.kt:63)
	at io.kotest.engine.runners.SingleInstanceSpecRunner.runTest(SingleInstanceSpecRunner.kt:73)
	at io.kotest.engine.runners.SingleInstanceSpecRunner$execute$2$invokeSuspend$$inlined$invoke$lambda$1.invokeSuspend(SingleInstanceSpecRunner.kt:83)
	at io.kotest.engine.runners.SingleInstanceSpecRunner$execute$2$invokeSuspend$$inlined$invoke$lambda$1.invoke(SingleInstanceSpecRunner.kt)
	at io.kotest.engine.spec.SpecRunner$runParallel$$inlined$map$lambda$1$1.invokeSuspend(SpecRunner.kt:53)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.engine.spec.SpecRunner$runParallel$$inlined$map$lambda$1.run(SpecRunner.kt:52)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

Spec failed
`

**Comment by ashishkujoy** [comment]
@slathropSR I am not able to reproduce the issue. https://github.com/ashishkujoy/kotest-playground/blob/master/src/test/kotlin/org/learning/AssertSoftlyWithInContextTest.kt

https://github.com/ashishkujoy/kotest-playground/runs/1466488914?check_suite_focus=true

With my setup my test are running and fail for proper assertion failure

**Comment by ashishkujoy** [comment]
@slathropSR Could you please help us to reproduce this issue or are we good to close this based above shared test reports and sample code.

**Comment by ghost** [comment]
@ashishkujoy Sorry for the lack of response previously.
I just pulled down your code fro GitHub and confirmed that it does work for me.
However, if I copy your test file into my repo I see my original problem.  I am using the same version of kotest so I suspect there is a library or configuration conflict causing this issue.

Since I'm not able to share my repo publicly maybe this issue can be closed until I find a way to reproduce in a repo that I can share.
