### ISSUE TITLE
Adding secondary module with Kotest as dependency to primary module leads to primary module JUnit4 tests not being run when running them from Android Studio folder

### ISSUE THREAD

**Issue by yaroslav-shlapak** [kotest/kotest#1912]
Kotest version: 4.2.5
### Given
1. An Android project with the next modules structure:
  +-`primary`
  +-`secondary`
2. The `secondary` module has Kotest configured like this (gradle.kts with correct kotest dependencies, here as constants):
  ```
  android {
      tasks.withType<Test>().all {
          useJUnitPlatform()
      }
  }
  ...
  testImplementation(kotestJunit5Runner)
  testImplementation(kotestAssertions)
  testImplementation(kotestProperty)
  testRuntimeOnly(junitVintage)
  ``` 
3. the `primary` module has the `secondary` module added as a dependency like this (gradle.kts):
   `implementation(project(secondary))`
4. the `primary` module has neither Kotest dependencies nor tests written using Kotest
### When 
running tests using Android Studio via right-click on a `primary` module package with tests -> select **Run 'Tests in 'primary''**
## Then
The tests are built but complete with error:
`No tests were found`
And the error message:
```
~~~ Kotest Configuration ~~~
-> Parallelization factor: 1
-> Default test timeout: 600000ms
-> Default test order: Sequential
-> Default isolation mode: SingleInstance
-> Global soft assertations: False
-> Write spec failure file: False
-> Fail on ignored tests: False
-> Spec execution order: SpecExecutionOrder
-> Extensions
  - io.kotest.engine.extensions.SystemPropertyTagExtension
  - io.kotest.core.extensions.RuntimeTagExtension
  - io.kotest.engine.extensions.RuntimeTagExpressionExtension


Process finished with exit code 0
```
## Expected result
The tests should work without error, there shouldn't be any mentions of Kotest in the  `primary` module during running
### Additional info
1. The issues don't depend on the state of Kotest IIntelliJ IDEA plugin (installed, not installed, installed but not enabled)
2. If running tests using Gradle it works without issues
3. Adding to the `primary` gradle.kts next configuration fixes the issue (given the plugin is unistalled)
`testRuntimeOnly(junitVintage)`
##

**Comment by yaroslav-shlapak** [comment]
Hey, any plans to fix this bug?

**Comment by yaroslav-shlapak** [comment]
Remove stale

**Comment by peebbv6364** [comment]
It operates normally by adding the dependency below.
Can't you solve the problem by adding the line below?
```
testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.2'
testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.2'
testRuntimeOnly 'org.junit.vintage:junit-vintage-engine:5.7.2'
```
with : https://github.com/kotest/kotest/issues/1911

**Comment by yaroslav-shlapak** [comment]
Still have an issue with no Junit4 tests being run in `primary` module (see the issue description).
The only workaround is to add `testRuntimeOnly "org.junit.vintage:junit-vintage-engine:5.7.2"` to the `primary` module.
Kotest version is `"5.1.0"`.
Android gradle plugin version is `"7.0.2"`.

However, the error is different this time
```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 13.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.junit.platform.commons.PreconditionViolationException: Cannot create Launcher without at least one TestEngine; consider adding an engine implementation JAR to the classpath
	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:296)
	at org.junit.platform.launcher.core.DefaultLauncher.<init>(DefaultLauncher.java:48)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:105)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:97)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	... 25 more
```

**Comment by sksamuel** [comment]
The error in that stack is because it can't find either jupiter or kotest.

**Comment by yaroslav-shlapak** [comment]
> The error in that stack is because it can't find either jupiter or kotest.

So why does it happen when the tests are run for a module which doesn't have any dependency neither from jupiter or kotest. This `primary` module does have a dependency on another module that has the dependency from jupiter or kotest, but I wouldn't expect that this affect the primary `module`.

**Comment by sksamuel** [comment]
I don't know why it's not picking the deps up, but that's the error. JUnit
platform is saying it can't find an engine implementation.
