### ISSUE TITLE
Koin extension broken for Koin 2.2.1

### ISSUE THREAD

**Issue by JoonasC** [kotest/kotest#1919]
I'm using Kotest version 4.3.2, and it seems like the Koin extension is broken for Koin version 2.2.1.

When I try to run my test cases I get the following error:
```
org/koin/core/context/ContextFunctionsKt
java.lang.NoClassDefFoundError: org/koin/core/context/ContextFunctionsKt
	at io.kotest.koin.KoinListener.beforeAny(KoinListener.kt:51)
	at io.kotest.core.spec.LifecycleKt.invokeAllBeforeTestCallbacks(lifecycle.kt:75)
	at io.kotest.core.spec.LifecycleKt$invokeAllBeforeTestCallbacks$1.invokeSuspend(lifecycle.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.engine.spec.SpecRunner$runParallel$$inlined$map$lambda$2.run(SpecRunner.kt:79)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.koin.core.context.ContextFunctionsKt
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 17 more
```

**Comment by ashishkujoy** [comment]
@JoonasC Could please help us with some sample code to reproduce this issue. Kotest Koin module itself uses Koin 2.2.1 and test related to that modules are working fine.

**Comment by JoonasC** [comment]
@ashishkujoy The following sample project reproduces the error for me with openjdk version 11: [https://drive.google.com/file/d/1HBr_X6njO5apc3YSoHLU7TPpNsIMtokC/view?usp=sharing](https://drive.google.com/file/d/1HBr_X6njO5apc3YSoHLU7TPpNsIMtokC/view?usp=sharing)

**Comment by LeoColman** [comment]
I'm honestly having a hard time with this one. I have no idea why the runner claims to be executing that function (and not finding it)

**Comment by LeoColman** [comment]
When I copy the listener to the project instead of using Kotest's it works as expected.

**Comment by LeoColman** [comment]
Ok, it's fixed on master.
Please use 4.4.0.20-SNAPSHOT if you need it quickly, it's the latest snapshot.
