### ISSUE TITLE
Roboeletric requiring java 9

### ISSUE THREAD

**Issue by jzeferino** [kotest/kotest#1923]
4.3.2 version

when trying to configure Roboelectric I followed the [docs](https://github.com/kotest/kotest/blob/master/doc/extensions.md#robolectric)

I'm getting this error output:

**java.lang.UnsupportedOperationException: Failed to create a Robolectric sandbox: Android SDK 29 requires Java 9 (have Java 8)**

------------------------------------------------------------------

Full exception here:
`java.lang.UnsupportedOperationException: Failed to create a Robolectric sandbox: Android SDK 29 requires Java 9 (have Java 8)
	at org.robolectric.plugins.DefaultSdkProvider$DefaultSdk.verifySupportedSdk(DefaultSdkProvider.java:156)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:278)
	at io.kotest.extensions.robolectric.ContainedRobolectricRunner.access$getSandbox(ContainedRobolectricRunner.kt:7)
	at io.kotest.extensions.robolectric.ContainedRobolectricRunner$sdkEnvironment$2.invoke(ContainedRobolectricRunner.kt:19)
	at io.kotest.extensions.robolectric.ContainedRobolectricRunner$sdkEnvironment$2.invoke(ContainedRobolectricRunner.kt:7)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.kotest.extensions.robolectric.ContainedRobolectricRunner.getSdkEnvironment(ContainedRobolectricRunner.kt)
	at io.kotest.extensions.robolectric.RobolectricExtension.instantiate(RobolectricExtension.kt:16)
	at io.kotest.engine.InstantiateSpecKt.createAndInitializeSpec(instantiateSpec.kt:21)
	at io.kotest.engine.spec.SpecExecutor.createInstance(SpecExecutor.kt:103)
	at io.kotest.engine.spec.SpecExecutor.execute(SpecExecutor.kt:43)
	at io.kotest.engine.KotestEngine$submitBatch$$inlined$forEach$lambda$1$1.invokeSuspend(KotestEngine.kt:139)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.engine.KotestEngine$submitBatch$$inlined$forEach$lambda$1.run(KotestEngine.kt:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by LordRaydenMK** [comment]
Have you tried the solutions from: https://stackoverflow.com/questions/56821193/does-robolectric-require-java-9
