### ISSUE TITLE
kotest-extensions-koin for Kotlin / JS

### ISSUE THREAD

**Issue by eugenio1590** [kotest/kotest#2316]
**Which version of Kotest are you using**
4.2.3

I am trying to use Koin with Kotest but I have gotten an issue running the test with Kotlin /JS.

````
Module not found: Error: Can't resolve 'core-koin-core' in 'E:\Workspace\Kotlin\HPlanner\build\js\node_modules\kotest-extensions-koin'
Module not found: Error: Can't resolve 'core-koin-test' in 'E:\Workspace\Kotlin\HPlanner\build\js\node_modules\kotest-extensions-koin'
Module not found: Error: Can't resolve 'kotest-kotest-assertions-api' in 'E:\Workspace\Kotlin\HPlanner\build\js\node_modules\kotest-kotest-assertions-core'
Module not found: Error: Can't resolve 'kotest-kotest-assertions-shared' in 'E:\Workspace\Kotlin\HPlanner\build\js\node_modules\kotest-kotest-assertions-core'
Module not found: Error: Can't resolve 'kotest-kotest-common' in 'E:\Workspace\Kotlin\HPlanner\build\js\node_modules\kotest-kotest-assertions-core'
Module not found: Error: Can't resolve 'kotest-kotest-assertions-shared' in 'E:\Workspace\Kotlin\HPlanner\build\js\packages\HPlanner-presentation-test\kotlin'
Module not found: Error: Can't resolve 'kotest-kotest-framework-api' in 'E:\Workspace\Kotlin\HPlanner\build\js\packages\HPlanner-presentation-test\kotlin'
  Uncaught Error: Cannot find module 'core-koin-test'
  at C:/Users/CASA/AppData/Local/Temp/_karma_webpack_677462/commons.js:14603:414
  Error: Cannot find module 'core-koin-test'
      at webpackMissingModule (C:/Users/CASA/AppData/Local/Temp/_karma_webpack_677462/commons.js:14603:335)
      at C:/Users/CASA/AppData/Local/Temp/_karma_webpack_677462/commons.js:14603:424
      at Object.../../node_modules/kotest-extensions-koin/kotest-extensions-koin.js (C:/Users/CASA/AppData/Local/Temp/_karma_webpack_677462/commons.js:14608:2)
      at __webpack_require__ (C:/Users/CASA/AppData/Local/Temp/_karma_webpack_677462/runtime.js:23:42)
      at C:/Users/CASA/AppData/Local/Temp/_karma_webpack_677462/commons.js:159666:232
      at Object../kotlin/HPlanner-presentation-test.js (C:/Users/CASA/AppData/Local/Temp/_karma_webpack_677462/commons.js:159671:2)
      at __webpack_require__ (C:/Users/CASA/AppData/Local/Temp/_karma_webpack_677462/runtime.js:23:42)
      at Object../adapter-browser.js (C:/Users/CASA/AppData/Local/Temp/_karma_webpack_677462/commons.js:159653:18)
      at __webpack_require__ (C:/Users/CASA/AppData/Local/Temp/_karma_webpack_677462/runtime.js:23:42)
      at __webpack_exec__ (adapter-browser.197343466.js:5:48)


java.lang.IllegalStateException: command 'C:\Users\CASA\.gradle\nodejs\node-v14.15.4-win-x64\node.exe' exited with errors (exit code: 1)
````

I only added the following dependency into common test dependencies:
`implementation("io.kotest.extensions:kotest-extensions-koin:1.0.0")`

But the tests run very well without this dependency. I start/stop the Koin application before/after each test but I am trying to use the Kotest extension for that.

This is my build.gradle.kts file
````
kotlin {
    js(LEGACY).browser()

    /* Targets configuration omitted.
    *  To find out how to configure the targets, please follow the link:
    *  https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#setting-up-targets */

    sourceSets {
        val kotestVersion: String by project
        val koinVersion: String by project

        val commonMain by getting {
            dependencies {
                implementation(project(":core"))
                implementation(kotlin("stdlib-common"))
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.1")
                compileOnly("io.insert-koin:koin-core:$koinVersion")
            }
        }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test-common"))
                implementation(kotlin("test-annotations-common"))
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.0")
                implementation("io.kotest:kotest-framework-api:$kotestVersion")
                implementation("io.kotest:kotest-assertions-core:$kotestVersion")
                implementation("io.kotest.extensions:kotest-extensions-koin:1.0.0")
                compileOnly("io.insert-koin:koin-test:$koinVersion")
            }
        }
        val jsTest by getting {
            dependencies {
                implementation(kotlin("test"))
            }
        }
    }
}
````

I found this dependency but this didn't work.
`implementation("io.kotest.extensions:kotest-extensions-koin-js:1.0.0")`

**Comment by sksamuel** [comment]
Do you have a standalone basic koin application for me to try ?

**Comment by eugenio1590** [comment]
sure, let me to push the changes and I'll let you know the link to the repo.

**Comment by sksamuel** [comment]
Do you have the repo ?

**Comment by sksamuel** [comment]
Closed without repro. Please reopen if still happening can you have a reproducer, thanks.
