### ISSUE TITLE
Unrelated test error -  java.lang.AssertionError: Test 'xyz' is incomplete

### ISSUE THREAD

**Issue by Ankit-Laddha** [kotest/kotest#2411]
Info:
Kotest = 4.2.6
SpecUsed = FunSpec
gradleVersion = Gradle 6.3
Kotlin =  1.3.70
Reporting Allure = 2.8.1

Hello,
I'm using gradle command line to run test on my local with specific tag. All my tests (assume A, B, C etc) are created using FunSpec style.
When i want to run only single test e.g. A, in console I see logs related to B and C also.

> <test path> STANDARD_ERROR
    java.lang.AssertionError: Test 'B' is incomplete
        at io.kotest.engine.spec.SpecExecutor.checkClosedTestCases(SpecExecutor.kt:58)
        at io.kotest.engine.spec.SpecExecutor.execute(SpecExecutor.kt:45)
        at io.kotest.engine.KotestEngine$submitBatch$$inlined$forEach$lambda$1$1.invokeSuspend(KotestEngine.kt:139)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at io.kotest.engine.KotestEngine$submitBatch$$inlined$forEach$lambda$1.run(KotestEngine.kt:138)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
    java.lang.AssertionError: Test 'B' is incomplete
        at io.kotest.engine.spec.SpecExecutor.checkClosedTestCases(SpecExecutor.kt:58)
        at io.kotest.engine.spec.SpecExecutor.execute(SpecExecutor.kt:45)
        at io.kotest.engine.KotestEngine$submitBatch$$inlined$forEach$lambda$1$1.invokeSuspend(KotestEngine.kt:139)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at io.kotest.engine.KotestEngine$submitBatch$$inlined$forEach$lambda$1.run(KotestEngine.kt:138)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 Gradle Test Executor 5 STANDARD_ERROR
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

And in also i see
> Task :test
3 tests completed, 2 failed

But the actual test A runs fine and Allure report shows only this test as expected.
While running directly from intelliJ, there is no errors in console. Test A runs fine.

Questions:
1. What does `Test is incomplete` means?
2. Why does gradle/kotest initializing/running other tests?

Any help in debugging is appreciated.

**Comment by sksamuel** [comment]
Sounds like you're not creating the test correctly in the DSL structure.
What does your test layout look like ?

**Comment by Ankit-Laddha** [comment]
This is what i also suspect. The structure my team is following might be incorrect. 

```
class A : FunSpec({
    withFun(ENUM.value) {

        tags(tagName)
        beforeTest {
        // 
        }

        test("Xyz")
            .config(...){
            // test code here
       }
   }
})
```

Here the `withFun` is a function which takes a enum value and then loads/reads certain env variables as per it. These env variable values are then used in different parts of code.

I believe since FunSpec content is run in init body, it "initialises" all classes. So the classes for which I have not defined any env variable fails, but for them the error is `io.kotest.engine.SpecInstantiationException: Could not create instance of class <className>`
 
This error is different. What does Test is incomplete means?
 >java.lang.AssertionError: Test 'B' is incomplete
at io.kotest.engine.spec.SpecExecutor.checkClosedTestCases(SpecExecutor.kt:58)
at io.kotest.engine.spec.SpecExecutor.execute(SpecExecutor.kt:45)

**Comment by sksamuel** [comment]
Test is incomplete means you've started adding a test but not completed it.

Like,

`test("asdas")`

Note no lambda And things like that.

You're running an old version of kotest, I would go to 4.6.1 and see if the error persists.

**Comment by Ankit-Laddha** [comment]
I upgraded kotest to 4.6.1, no longer see this problem w/o any code changes.
so definitely some problem with 4.2.6 version.
@sksamuel what we do with this issue then? let it be open for 4.2.6?

**Comment by sksamuel** [comment]
<4.6 versions are no longer seeing anything but the most critical fixes so I think we can close.
5.0 is the current focus.
