### ISSUE TITLE
Nest and indentation of inspectors.forAll

### ISSUE THREAD

**Issue by shwaka** [kotest/kotest#2446]
When we nest `inspectors.forAll`, the error message for failure is a little hard to read.
I think it will be better if the message is indented properly.

This is an example that includes nested `inspectors.forAll`:

```kotlin
import io.kotest.core.spec.style.FreeSpec
import io.kotest.inspectors.forAll
import io.kotest.matchers.booleans.shouldBeTrue

class MyTest : FreeSpec({
    "some test" {
        listOf("foo", "Bar", "BAz").forAll { string ->
            string.toList().forAll { char ->
                char.isLowerCase().shouldBeTrue() // fails for uppper case characters
            }
        }
    }
})
```

## Current behavior
Currently (version `4.6.2` of `kotest`), the error message is:

```
java.lang.AssertionError: 1 elements passed but expected 3

The following elements passed:
foo

The following elements failed:
"Bar" => 2 elements passed but expected 3

The following elements passed:
a
r

The following elements failed:
'B' => expected:<true> but was:<false>
"BAz" => 1 elements passed but expected 3

The following elements passed:
z

The following elements failed:
'B' => expected:<true> but was:<false>
'A' => expected:<true> but was:<false>
```

## Behavior which I request
I think it will be easier to read if it is indented according to the depth of the nest of `inspectors.forAll`:

```
java.lang.AssertionError: 1 elements passed but expected 3

The following elements passed:
foo

The following elements failed:
"Bar" => 2 elements passed but expected 3

  The following elements passed:
  a
  r

  The following elements failed:
  'B' => expected:<true> but was:<false>
"BAz" => 1 elements passed but expected 3

  The following elements passed:
  z

  The following elements failed:
  'B' => expected:<true> but was:<false>
  'A' => expected:<true> but was:<false>
```

## Implementation
If I'm understanding correctly, the above behavior can be achieved by editing the 41st line of [error.kt](https://github.com/kotest/kotest/blob/master/kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/inspectors/error.kt#L41) from

```kotlin
builder.append(
   failed.take(maxResults).joinToString("\n") {
      it.t.show().value + " => " + exceptionToMessage(it.throwable)
   }
)
```

to

```kotlin
builder.append(
   failed.take(maxResults).joinToString("\n") {
      it.t.show().value + " => " + exceptionToMessage(it.throwable).lines().joinToString("\n  ")
   }
)
```

Although this will affect all error messages with multiple lines inside `forAll` (without nest), I believe it is an acceptable change.

Note that the above code is not tested since I don't know how to test a fork of `kotest` locally.

**Comment by shwaka** [comment]
I have written a working example [shwaka/kotest-nest-forAll](https://github.com/shwaka/kotest-nest-forAll) of the above "implementation".
(I have reimplemented `io.kotest.inspectors.buildAssertionError` and `io.kotest.inspectors.forAll` in a different namespace `com.github.shwaka.kotest.inspectors`)

Here is the error message from it, which looks nice (at least for me).

```
MyTest > foo FAILED
    java.lang.AssertionError: 1 elements passed but expected 3

    The following elements passed:
    foo

    The following elements failed:
    "Bar" => 2 elements passed but expected 3

      The following elements passed:
      a
      r

      The following elements failed:
      'B' => expected:<true> but was:<false>
    "BAz" => 1 elements passed but expected 3

      The following elements passed:
      z

      The following elements failed:
      'B' => expected:<true> but was:<false>
      'A' => expected:<true> but was:<false>
        at com.github.shwaka.kotest.inspectors.ErrorKt.buildAssertionError(error.kt:51)
        at com.github.shwaka.kotest.inspectors.InspectorsKt.forAll(Inspectors.kt:10)
        at MyTest$1$1.invokeSuspend(MyTest.kt:8)
        at MyTest$1$1.invoke(MyTest.kt)

        Caused by:
        java.lang.AssertionError: 1 elements passed but expected 3

        The following elements passed:
        foo

        The following elements failed:
        "Bar" => 2 elements passed but expected 3

          The following elements passed:
          a
          r

          The following elements failed:
          'B' => expected:<true> but was:<false>
        "BAz" => 1 elements passed but expected 3

          The following elements passed:
          z

          The following elements failed:
          'B' => expected:<true> but was:<false>
          'A' => expected:<true> but was:<false>
            at com.github.shwaka.kotest.inspectors.ErrorKt.buildAssertionError(error.kt:51)
            ... 3 more

1 test completed, 1 failed
```
