### ISSUE TITLE
afterSpec is not called if beforeSpec fails

### ISSUE THREAD

**Issue by benjishults** [kotest/kotest#2451]
**Which version of Kotest are you using**  4.6.2

If `beforeSpec` exits with an exception, then `afterSpec` is not called.

Is this by design?  If so, it might be nice to have the docs call it out specifically.

```kotlin
import io.kotest.core.spec.Spec
import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.shouldBe

class TestTest : FreeSpec() {

    override fun beforeSpec(spec: Spec) {
        println("beforeSpec")
        check(false)
    }

    override fun afterSpec(spec: Spec) {
        println("afterSpec")
    }

    init {
        "test" - {
            "sammy".length shouldBe 5
        }
    }

}
```

```
beforeSpec
java.lang.IllegalStateException: Check failed.
	at smartthings.util.auth.TestTest.beforeSpec(TestTest.kt:11)
	at io.kotest.core.spec.ListenersKt$functionOverrideCallbacks$1.beforeSpec(listeners.kt:30)
	at io.kotest.core.spec.LifecycleKt.invokeBeforeSpec(lifecycle.kt:141)
	at io.kotest.engine.spec.runners.SingleInstanceSpecRunner$execute$3.invokeSuspend(SingleInstanceSpecRunner.kt:63)
	at io.kotest.engine.spec.runners.SingleInstanceSpecRunner$execute$3.invoke(SingleInstanceSpecRunner.kt)
	at io.kotest.engine.spec.runners.SingleInstanceSpecRunner$execute$3.invoke(SingleInstanceSpecRunner.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at io.kotest.engine.spec.runners.SingleInstanceSpecRunner.execute(SingleInstanceSpecRunner.kt:62)
	at io.kotest.engine.spec.SpecExecutor$runTests$run$1.invokeSuspend(SpecExecutor.kt:87)
	at io.kotest.engine.spec.SpecExecutor$runTests$run$1.invoke(SpecExecutor.kt)
	at io.kotest.engine.spec.SpecExecutor$runTests$run$1.invoke(SpecExecutor.kt)
	at io.kotest.engine.spec.SpecExecutor.interceptSpec(SpecExecutor.kt:101)
	at io.kotest.engine.spec.SpecExecutor.runTests(SpecExecutor.kt:92)
	at io.kotest.engine.spec.SpecExecutor.runTestsIfAtLeastOneEnabled(SpecExecutor.kt:72)
	at io.kotest.engine.spec.SpecExecutor.execute(SpecExecutor.kt:41)
	at io.kotest.engine.launchers.DefaultSpecLauncher$sequential$3$1$2.invokeSuspend(DefaultSpecLauncher.kt:56)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Check failed.
java.lang.IllegalStateException: Check failed.
	at smartthings.util.auth.TestTest.beforeSpec(TestTest.kt:11)
	at io.kotest.core.spec.ListenersKt$functionOverrideCallbacks$1.beforeSpec(listeners.kt:30)
	at io.kotest.core.spec.LifecycleKt.invokeBeforeSpec(lifecycle.kt:141)
	at io.kotest.engine.spec.runners.SingleInstanceSpecRunner$execute$3.invokeSuspend(SingleInstanceSpecRunner.kt:63)
	at io.kotest.engine.spec.runners.SingleInstanceSpecRunner$execute$3.invoke(SingleInstanceSpecRunner.kt)
	at io.kotest.engine.spec.runners.SingleInstanceSpecRunner$execute$3.invoke(SingleInstanceSpecRunner.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at io.kotest.engine.spec.runners.SingleInstanceSpecRunner.execute(SingleInstanceSpecRunner.kt:62)
	at io.kotest.engine.spec.SpecExecutor$runTests$run$1.invokeSuspend(SpecExecutor.kt:87)
	at io.kotest.engine.spec.SpecExecutor$runTests$run$1.invoke(SpecExecutor.kt)
	at io.kotest.engine.spec.SpecExecutor$runTests$run$1.invoke(SpecExecutor.kt)
	at io.kotest.engine.spec.SpecExecutor.interceptSpec(SpecExecutor.kt:101)
	at io.kotest.engine.spec.SpecExecutor.runTests(SpecExecutor.kt:92)
	at io.kotest.engine.spec.SpecExecutor.runTestsIfAtLeastOneEnabled(SpecExecutor.kt:72)
	at io.kotest.engine.spec.SpecExecutor.execute(SpecExecutor.kt:41)
	at io.kotest.engine.launchers.DefaultSpecLauncher$sequential$3$1$2.invokeSuspend(DefaultSpecLauncher.kt:56)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)


smartthings.util.auth.TestTest > executionError FAILED
    java.lang.IllegalStateException: Check failed.
        at smartthings.util.auth.TestTest.beforeSpec(TestTest.kt:11)
2 tests completed, 1 failed, 1 skipped
```

**Comment by sksamuel** [comment]
Yes as expected.
I will update the docs to clarify the lifecycle for 5.0
