### ISSUE TITLE
StackOverflow when using `checkAll` with property test config and 2 generators

### ISSUE THREAD

**Issue by jcornaz** [kotest/kotest#2513]
**Which version of Kotest are you using**: 4.6.2

The following test:

```kotlin
checkAll(PropTestConfig(), Arb.int(), Arb.int()) { }
```

leads to this exception:
```
Caused by: java.lang.StackOverflowError
	at io.kotest.property.PropertyTest2Kt.checkAll(propertyTest2.kt:20)
	at io.kotest.property.PropertyTest2Kt.checkAll(propertyTest2.kt:20)
	at io.kotest.property.PropertyTest2Kt.checkAll(propertyTest2.kt:20)
	at io.kotest.property.PropertyTest2Kt.checkAll(propertyTest2.kt:20)
	at io.kotest.property.PropertyTest2Kt.checkAll(propertyTest2.kt:20)
	at io.kotest.property.PropertyTest2Kt.checkAll(propertyTest2.kt:20)
	at io.kotest.property.PropertyTest2Kt.checkAll(propertyTest2.kt:20)
	at io.kotest.property.PropertyTest2Kt.checkAll(propertyTest2.kt:20)
	at io.kotest.property.PropertyTest2Kt.checkAll(propertyTest2.kt:20)
	at io.kotest.property.PropertyTest2Kt.checkAll(propertyTest2.kt:20)
	at io.kotest.property.PropertyTest2Kt.checkAll(propertyTest2.kt:20)
	at io.kotest.property.PropertyTest2Kt.checkAll(propertyTest2.kt:20)
	at io.kotest.property.PropertyTest2Kt.checkAll(propertyTest2.kt:20)
	at io.kotest.property.PropertyTest2Kt.checkAll(propertyTest2.kt:20)
	at io.kotest.property.PropertyTest2Kt.checkAll(propertyTest2.kt:20)
	at io.kotest.property.PropertyTest2Kt.checkAll(propertyTest2.kt:20)
```

**Comment by tmszdmsk** [comment]
It's the same for `PropertyTest3`.

**Comment by sksamuel** [comment]
And 5+

**Comment by sksamuel** [comment]
4.6.3 has been released which fixes this.
