### ISSUE TITLE
Maven Surefire Plugin throws an error when running raw JUnit tests after Kotest tests in a reactor build

### ISSUE THREAD

**Issue by Nimelrian** [kotest/kotest#2630]
**Which version of Kotest are you using**
4.6.3

I have a Maven project with multiple modules. One of these modules uses Kotest via the JUnit5 runner, all other modules use regular JUnit5 tests. If the Kotest module is built before another JUnit module is built, Surefire will throw a NoClassDefFoundError:
```
Please refer to G:\src\kotlin\kotest-conflict\junit-module\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
There was an error in the forked process
java.lang.NoClassDefFoundError: org/junit/platform/launcher/core/LauncherFactory
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
java.lang.NoClassDefFoundError: org/junit/platform/launcher/core/LauncherFactory
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:656)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

I have built a minimal reproduction repository over here: https://github.com/Nimelrian/kotest-junit-surefire-conflict

Changing the module order in the root pom can be used to replicate the issue.
With this order, the project builds fine:
```
<modules>
    <module>junit-module</module>
    <module>kotest-module</module>
</modules>
```

With this order, the error occurs
```
<modules>
    <module>kotest-module</module>
    <module>junit-module</module>
</modules>
```

I'm not sure whether this is a Kotest issue, or a Surefire issue...

**Comment by sksamuel** [comment]
Ok, so I have no idea why this fixes it, but if you add the junit launcher dependency to the junit module, it works.

```
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <version>1.7.2</version>
            <scope>test</scope>
        </dependency>
```

That's defined by both junit and kotest but it's like surefire only includes it once if you don't specify it explicity.

**Comment by sksamuel** [comment]
I'm going to close this as the workaround above seems good to me. If you still have issues please reopen this ticket.
