### ISSUE TITLE
Coroutine Debugging – code doesn't compile

### ISSUE THREAD

**Issue by jacekgajek** [kotest/kotest#2789]
**Which version of Kotest are you using**

The default version which is fetched with testRuntime("kotest") by micronaut 3.2.0, which is **4.6.0**

I don't know if it's a bug in documentation or kotest itself, but the code provided on 
https://kotest.io/docs/framework/coroutines/coroutine-debugging.html
**does not compile**.

The first example causes "no property coroutineDebugProbes", the second one "cannot reassign val", and the third one "nothing to override"

There is no information on how to enable stack-recovery coroutine feature so I assumed that it's enough to add dependencies, which I did:
```
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.6.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.0")
```

StackOverflow: https://stackoverflow.com/questions/70787244/micronaut-kotest-coroutines-httpclient-how-to-recover-stack-trace-and-er

**Comment by sksamuel** [comment]
This feature is available in 5.0.0 and above. I think if you just upgrade the kotest version then you're good.

**Comment by jacekgajek** [comment]
Definitely a bug in documentation then, especially since the default version fetched by the latest Micronaut is <5
Also need instructions how to setup the upgrade – kotest core is maxed at 4.1.3... 

So to find out which package I should update, I've checked where the `AbstractProjectConfig` is defined and added
```
    testImplementation("io.kotest:kotest-framework-api-jvm:5.1.0")
```
to gradle.

gradle clean build and then this happened...


```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 2.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:63)
	at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@15.0.1/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.util.ServiceConfigurationError: org.junit.platform.engine.TestEngine: Provider io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:584)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:806)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:724)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1396)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at org.junit.platform.launcher.core.LauncherFactory.collectTestEngines(LauncherFactory.java:145)
	at org.junit.platform.launcher.core.LauncherFactory.createDefaultLauncher(LauncherFactory.java:131)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:125)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:109)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:97)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: io/kotest/fp/OptionKt
	at io.kotest.engine.config.LoadConfigFromSystemPropertiesKt.isolationMode(loadConfigFromSystemProperties.kt:12)
	at io.kotest.engine.config.LoadConfigFromSystemPropertiesKt.loadConfigFromSystemProperties(loadConfigFromSystemProperties.kt:48)
	at io.kotest.engine.config.DetectConfigKt.detectConfig(detectConfig.kt:16)
	at io.kotest.engine.config.ConfigManager.init(init.kt:25)
	at io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine.<init>(KotestJunitPlatformTestEngine.kt:41)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:782)
	... 29 more
Caused by: java.lang.ClassNotFoundException: io.kotest.fp.OptionKt
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 40 more
```

**Comment by jacekgajek** [comment]
I've tried `kotest-framework-api-jvm:5.1.0`, `io.kotest:kotest-assertions-shared-jvm:5.1.0`, `io.kotest:kotest-common:5.1.0` and `io.kotest:kotest-property-jvm:5.1.0`, still the same error.

**Comment by jacekgajek** [comment]
My gradle script:
```
plugins {
    application
    id("org.jetbrains.kotlin.jvm") version "1.6.10"
    id("org.jetbrains.kotlin.kapt") version "1.6.10"
    id("org.jetbrains.kotlin.plugin.allopen") version "1.6.10"
    id("com.github.johnrengelman.shadow") version "7.1.2"
    id("io.micronaut.application") version "3.1.1"
    id("io.gitlab.arturbosch.detekt") version "1.19.0"
    id("org.jlleitschuh.gradle.ktlint") version "10.2.1"
    id("org.jlleitschuh.gradle.ktlint-idea") version "10.2.1"
    id("com.google.cloud.tools.jib") version "3.1.4"
    id("org.owasp.dependencycheck") version "6.5.1"
    jacoco
}

group = "com.foo"

val kotestVersion = "5.1.0"

repositories {
    mavenCentral()
}

micronaut {
    runtime("google_function")
    runtime("netty")
    testRuntime("kotest")
    processing {
        incremental(true)
        annotations("com.foo.*")
    }
}

dependencies {
    implementation("io.micronaut:micronaut-runtime")
    implementation("io.micronaut.kotlin:micronaut-kotlin-extension-functions")
    implementation("io.micronaut.kotlin:micronaut-kotlin-runtime")
    implementation("io.micronaut:micronaut-management")
    implementation("io.micronaut.gcp:micronaut-gcp-logging")
    implementation("io.micronaut.rxjava3:micronaut-rxjava3")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut.redis:micronaut-redis-lettuce")
    implementation("io.micronaut.cache:micronaut-cache-core")
    implementation("io.micronaut.jmx:micronaut-jmx")
    implementation("io.micronaut.openapi:micronaut-openapi")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-jdk8")

    implementation("io.swagger.core.v3:swagger-annotations")
    implementation("javax.annotation:javax.annotation-api")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("io.github.microutils:kotlin-logging-jvm:2.1.21")
    implementation("ch.qos.logback.contrib:logback-json-classic:0.1.5")

    implementation("com.google.cloud:google-cloud-secretmanager:2.0.5")
    implementation("com.google.cloud:google-cloud-logging-logback:0.122.5-alpha")

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-rx3")

    implementation("net.logstash.logback:logstash-logback-encoder:7.0.1")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.6.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.0")

    annotationProcessor("io.micronaut.openapi:micronaut-openapi")
    annotationProcessor("io.micronaut:micronaut-http-validation")
    annotationProcessor("io.micronaut:micronaut-management")

    runtimeOnly("com.fasterxml.jackson.module:jackson-module-kotlin")

    testImplementation("io.projectreactor:reactor-test:3.4.13")
    testImplementation("com.github.kstyrc:embedded-redis:0.6")

    // This is what I added:
    testImplementation("io.kotest:kotest-property-jvm:$kotestVersion")
    testImplementation("io.kotest:kotest-framework-api-jvm:$kotestVersion")
    testImplementation("io.kotest:kotest-assertions-core-jvm:$kotestVersion")
    runtimeOnly("io.kotest:kotest-assertions-shared-jvm:$kotestVersion")
    runtimeOnly("io.kotest:kotest-common:$kotestVersion")
    runtimeOnly("io.kotest:kotest-framework-api-jvm:$kotestVersion")
    runtimeOnly("io.kotest:kotest-assertions-core:$kotestVersion")
}

application {
    mainClass.set("com.foo.Application")
}
java {
    sourceCompatibility = JavaVersion.toVersion("17")
}

allOpen {
    annotation("io.micronaut.cache.annotation.Cacheable")
    annotation("io.micronaut.cache.annotation.CacheConfig")
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        jvmTarget = "17"
        freeCompilerArgs = listOf("-Xjsr305=strict")
    }
}
// (... )
```
Application.kt
```
object Application {
    @JvmStatic
    fun main(args: Array<String>) {
        build()
            .args(*args)
            .packages("com.foo")
            .start()
    }
}
```

**Comment by sksamuel** [comment]
Thanks I'll run your gradle script see what happens.

**Comment by jacekgajek** [comment]
"-Dkotlinx.coroutines.stacktrace.recovery=true" was just my attempt, but it doesn't work so you'd have to remove it.

**Comment by jacekgajek** [comment]
Also, a side note:
`AbstractProjectConfig.listeners()`
seems to be deprecated
"Overrides deprecated member in 'io.kotest.core.config.AbstractProjectConfig'. Use extensions. This will be removed in 6.0"
Please consider not removing it so soon – All Micronaut tutorials require adding this to tests:
```
package io.kotest.provided

import io.kotest.core.config.AbstractProjectConfig
import io.micronaut.test.extensions.kotest.MicronautKotestExtension

object ProjectConfig : AbstractProjectConfig() {
    override fun listeners() = listOf(MicronautKotestExtension)
    override fun extensions() = listOf(MicronautKotestExtension)
}
```
If you remove it, Micronaut will be stuck on the old version forever. Especially that the description isn't very useful: "use extensions", what does it even mean, I'm clearly using extensions here.

**Comment by sksamuel** [comment]
It wouldn't be removed for years.

**Comment by sksamuel** [comment]
Seems to work for me 
https://github.com/kotest/jacekexample/blob/master/src/test/kotlin/config.kt

**Comment by hanc1208** [comment]
@sksamuel I got a same error on my project. and jacekexample repository causes same error.

I've run `./gradlew test`

**Comment by sksamuel** [comment]
Can you paste the full output.

**Comment by hanc1208** [comment]
```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 1.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:63)
	at java.base@15.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@15.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base@15.0.5/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@15.0.5/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.util.ServiceConfigurationError: org.junit.platform.engine.TestEngine: Provider io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:584)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:806)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:724)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1396)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at org.junit.platform.launcher.core.LauncherFactory.collectTestEngines(LauncherFactory.java:145)
	at org.junit.platform.launcher.core.LauncherFactory.createDefaultLauncher(LauncherFactory.java:131)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:125)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:109)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:97)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: io/kotest/fp/OptionKt
	at io.kotest.engine.config.LoadConfigFromSystemPropertiesKt.isolationMode(loadConfigFromSystemProperties.kt:12)
	at io.kotest.engine.config.LoadConfigFromSystemPropertiesKt.loadConfigFromSystemProperties(loadConfigFromSystemProperties.kt:48)
	at io.kotest.engine.config.DetectConfigKt.detectConfig(detectConfig.kt:16)
	at io.kotest.engine.config.ConfigManager.init(init.kt:25)
	at io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine.<init>(KotestJunitPlatformTestEngine.kt:41)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:782)
	... 29 more
Caused by: java.lang.ClassNotFoundException: io.kotest.fp.OptionKt
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 40 more
```

@sksamuel  here it is. i've run only `git clone` and `./gradlew test` on the jacekexample repository.

**Comment by sksamuel** [comment]
Thisi s a different error. The versions are wrong if you are seeing Caused by: java.lang.NoClassDefFoundError: io/kotest/fp/OptionKt.
That class hasn't existed for a while in kotest, so you have old versions leaking in.

**Comment by fitzvinicius** [comment]
I tried to reproduce the jacekexample repository and got the same error too. Seems like Micronaut doesn't have support for Kotest 5+ yet, look at: micronaut-projects/micronaut-test#504.
