### ISSUE TITLE
TestEngine with ID 'kotest' failed to execute tests

### ISSUE THREAD

**Issue by aseria** [kotest/kotest#2819]
kotlin version : 1.6.10
kotest version: 5.1.0

Running the ./gradlew test task, the folowing exception is raised:
```
> Task :test

UnknownClass.Kotest > UnknownClass.initializationError FAILED
    org.junit.platform.commons.JUnitException at DefaultLauncher.java:254
        Caused by: java.lang.StackOverflowError at MainDispatchers.kt:128
```

Running the test  on intellij:
```

> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :compileTestKotlin
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test

TestEngine with ID 'kotest' failed to execute tests
org.junit.platform.commons.JUnitException: TestEngine with ID 'kotest' failed to execute test <25 internal lines>
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.StackOverflowError
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcherFactory.hintOnError(MainDispatchers.kt:128)
	at kotlinx.coroutines.internal.MainDispatchersKt.tryCreateDispatcher(MainDispatchers.kt:59)
	at kotlinx.coroutines.test.internal.TestMainDispatcher.getDelegate(MainTestDispatcher.kt:19)
	at kotlinx.coroutines.test.internal.TestMainDispatcher.getImmediate(MainTestDispatcher.kt:32)
	at kotlinx.coroutines.internal.MainDispatchersKt.isMissing(MainDispatchers.kt:66)
	at kotlinx.coroutines.test.internal.TestMainDispatcher.getDelegate(MainTestDispatcher.kt:21)
	at kotlinx.coroutines.test.internal.TestMainDispatcher.getImmediate(MainTestDispatcher.kt:32)
...
```
The last 3 sentences are repeated.

When version 5.0.3 was used, it worked well. But it doesn't work with 5.1.0.

**Comment by buzoherbert** [comment]
I encountered the same issue when upgrading from 4.3.1

**Comment by sksamuel** [comment]
Perhaps you have older coroutines. You should be on 1.6.

**Comment by buzoherbert** [comment]
Thanks, I updated coroutines before encountering the issue

implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0")

**Comment by sksamuel** [comment]
I can't see Kotest in the stack trace. What's going on at that line in
MainDispatcher.

**Comment by buzoherbert** [comment]
Ahh, when looking deeper into this issue, it seems like it is a problem when providing a MainDispatcher to the test environment rather than Kotest itself? I found that in this similar issue thread. https://github.com/Kotlin/kotlinx.coroutines/issues/3005

Still looking for a working solution in my case.

**Comment by buzoherbert** [comment]
Ok, for me what solved it is to add this dependency

   ` implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor:$coroutinesVersion")`

**Comment by sksamuel** [comment]
I will close this @buzoherbert since you found the solution.
