### ISSUE TITLE
withEnvironment from kotest-extensions-jvm fails on Java 17

### ISSUE THREAD

**Issue by zapodot** [kotest/kotest#2849]
**Which version of Kotest are you using**
5.1.0

In some of our tests we are using withEnvironment to set some system properties. This works well when we are building on JDK11 but with a JDK17 (and jvmTarget set to 17) it fails due to the use of reflection at https://github.com/kotest/kotest/blob/5b81fb0d8d5b15bf1956e678f80b9818237e73ba/kotest-extensions/src/jvmMain/kotlin/io/kotest/extensions/system/SystemEnvironmentExtensions.kt#L99

This failes with an InaccessibleObjectException

```
Unable to make field private final java.util.Map java.util.Collections$UnmodifiableMap.m accessible: module java.base does not "opens java.util" to unnamed module @78aab498
java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Map java.util.Collections$UnmodifiableMap.m accessible: module java.base does not "opens java.util" to unnamed module @78aab498
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at io.kotest.extensions.system.SystemEnvironmentExtensionsKt.asAccessible(SystemEnvironmentExtensions.kt:115)
	at io.kotest.extensions.system.SystemEnvironmentExtensionsKt.getEditableMapOfVariables(SystemEnvironmentExtensions.kt:99)
	at io.kotest.extensions.system.SystemEnvironmentExtensionsKt.setEnvironmentMap(SystemEnvironmentExtensions.kt:84)
```

**Comment by sksamuel** [comment]
This is because that API has been deprecated in 17 but no replacement has been given.

**Comment by OliverO2** [comment]
It seems that this one is [now biting us on GitHub CI with Windows](https://github.com/kotest/kotest/actions/runs/9514996248/job/26228399767#step:6:27702):

Failing tests in `com.sksamuel.kotest.engine.config.ApplyConfigTest`:
* log level can come from env vars with dots in name[jvm]
* log level can come from env vars with underscores in name[jvm]
* log level can come from sys props[jvm]

Stacktrace:
```
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.util.Map java.lang.ProcessEnvironment.theCaseInsensitiveEnvironment accessible: module java.base does not "opens java.lang" to unnamed module @740fb309
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at io.kotest.extensions.system.SystemEnvironmentExtensionsKt.asAccessible(SystemEnvironmentExtensions.kt:115)
	at io.kotest.extensions.system.SystemEnvironmentExtensionsKt.getCaseInsensitiveEnvironment(SystemEnvironmentExtensions.kt:107)
	at io.kotest.extensions.system.SystemEnvironmentExtensionsKt.setEnvironmentMap(SystemEnvironmentExtensions.kt:85)
	at com.sksamuel.kotest.engine.config.ApplyConfigTest$1$2.invokeSuspend(ApplyConfigTest.kt:84)
	at com.sksamuel.kotest.engine.config.ApplyConfigTest$1$2.invoke(ApplyConfigTest.kt)
	at com.sksamuel.kotest.engine.config.ApplyConfigTest$1$2.invoke(ApplyConfigTest.kt)
	at io.kotest.core.spec.style.scopes.RootScopeKt$addTest$1.invokeSuspend(RootScope.kt:36)
```

Reference: [Set an Environment Variable at Runtime in Java Using Reflection API | Baeldung](https://www.baeldung.com/java-set-environment-variable-runtime#1-using-reflection-api)

Possible resolution: add `--add-opens=java.base/java.lang=ALL-UNNAMED` to this line:
https://github.com/kotest/kotest/blob/176da420c243d361cc7d08efd7da0a32bd678bdb/kotest-framework/kotest-framework-engine/build.gradle.kts#L59
