### ISSUE TITLE
Can't upgrade from version 5.1.0 to 5.2.1 because of nested nullable in checkEqualityOfFieldsRecursively

### ISSUE THREAD

**Issue by hestad** [kotest/kotest#2874]
Can't upgrade from version 5.1.0 to 5.2.1 because of nested nullable: 
```
java.lang.NullPointerException
	at io.kotest.matchers.equality.ReflectionKt.checkEqualityOfFieldsRecursively(reflection.kt:469)
	at io.kotest.matchers.equality.ReflectionKt.checkEqualityOfFieldsRecursively(reflection.kt:490)
	at io.kotest.matchers.equality.ReflectionKt.checkEqualityOfFieldsRecursively$default(reflection.kt:455)
	at io.kotest.matchers.equality.ReflectionKt$beEqualComparingFields$1.test(reflection.kt:418)
	at io.kotest.matchers.ShouldKt.invokeMatcher(should.kt:43)
	at io.kotest.matchers.ShouldKt.should(should.kt:38)
	at io.kotest.matchers.equality.ReflectionKt.shouldBeEqualToComparingFields(reflection.kt:322)
	at io.kotest.matchers.equality.ReflectionKt.shouldBeEqualToComparingFields$default(reflection.kt:317)
```

**Which version of Kotest are you using**
Upgraded from 5.1.0 to 5.2.1

**Comment by ashishkujoy** [comment]
Thanks, @hestad, for reporting this issue, will try to fix this soon.

**Comment by ashishkujoy** [comment]
@hestad can you try the latest snapshot version.

**Comment by hestad** [comment]
@ashishkujoy Just tried it. This solves our problem.
