### ISSUE TITLE
Flaky java.lang.StackOverflowError using generators.

### ISSUE THREAD

**Issue by caeus** [kotest/kotest#2896]
**Which version of Kotest are you using**: 5.1.0

So I'm using generators not for property testing, but just to generate complex data classes for testing.

But from time to time it throws a `java.lang.StackOverflowError`:

```
java.lang.StackOverflowError
            at kotlin.coroutines.jvm.internal.RestrictedSuspendLambda.<init>(ContinuationImpl.kt:144)
            at io.kotest.property.arbitrary.BuildersKt$arbitrary$1.<init>(builders.kt)
            at io.kotest.property.arbitrary.BuildersKt$arbitrary$1.invoke(builders.kt)
            at io.kotest.property.arbitrary.BuildersKt$arbitrary$1.invoke(builders.kt)
            at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1$singleShotArb$restrictedContinuation$1.invokeSuspend(builders.kt:237)
            at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
            at io.kotest.property.arbitrary.SingleShotArbContinuation$bind$2$1.invoke(builders.kt:385)
            at io.kotest.property.arbitrary.SingleShotArbContinuation$bind$2$1.invoke(builders.kt:378)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1.edgecase(builders.kt:216)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:93)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:89)
            at io.kotest.property.arbitrary.BuildersKt$arbitrary$8.edgecase(builders.kt:103)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:28)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1.edgecase(builders.kt:216)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:28)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1.edgecase(builders.kt:216)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:93)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:89)
            at io.kotest.property.arbitrary.BuildersKt$arbitrary$8.edgecase(builders.kt:103)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:28)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1.edgecase(builders.kt:216)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:93)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:89)
            at io.kotest.property.arbitrary.BuildersKt$arbitrary$8.edgecase(builders.kt:103)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:89)
            at io.kotest.property.arbitrary.BuildersKt$arbitrary$8.edgecase(builders.kt:103)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:28)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1.edgecase(builders.kt:216)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:93)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:89)
            at io.kotest.property.arbitrary.BuildersKt$arbitrary$8.edgecase(builders.kt:103)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:28)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1.edgecase(builders.kt:216)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:93)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:89)
            at io.kotest.property.arbitrary.BuildersKt$arbitrary$8.edgecase(builders.kt:103)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:28)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1.edgecase(builders.kt:216)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:93)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:89)
            at io.kotest.property.arbitrary.BuildersKt$arbitrary$8.edgecase(builders.kt:103)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:28)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1.edgecase(builders.kt:216)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:93)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:89)
            at io.kotest.property.arbitrary.BuildersKt$arbitrary$8.edgecase(builders.kt:103)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:28)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1.edgecase(builders.kt:216)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:93)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:89)
            at io.kotest.property.arbitrary.BuildersKt$arbitrary$8.edgecase(builders.kt:103)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:28)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1.edgecase(builders.kt:216)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:93)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:89)
            at io.kotest.property.arbitrary.BuildersKt$arbitrary$8.edgecase(builders.kt:103)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:28)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1.edgecase(builders.kt:216)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:93)
            at io.kotest.property.arbitrary.CollectionsKt$list$1.invoke(collections.kt:89)
            at io.kotest.property.arbitrary.BuildersKt$arbitrary$8.edgecase(builders.kt:103)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:28)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.MapKt$flatMap$1.edgecase(map.kt:29)
            at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1.edgecase(builders.kt:216)
```

Maybe it's just a very complex structure, so it is not in an infinite loop, but just very very deep into some frame. If that were the case, how can it be solved?

**Comment by sksamuel** [comment]
Do you have example code ?

**Comment by caeus** [comment]
```kotlin 
object Generators {
    val kitchenGen = arbitrary {
        Accepted.Kitchen(
            id = Arb.string(5..10).bind(),
            name = Arb.string(10..15).bind(),
            warehouseId = Arb.string(5..10).bind()
        )
    }
    val brandGen = arbitrary {
        Accepted.Brand(
            id = Arb.string(5..10).bind(),
            name = Arb.string(10..15).bind(),
        )
    }
    val nullableCustomerGen: Arb<Accepted.Customer?> = arbitrary {
        kotlin.runCatching {
            Accepted.Customer(
                uniqueId = Arb.string(8..12).orNull().bind(),
                firstName = Arb.string(8..12).orNull().bind(),
                lastName = Arb.string(8..12).orNull().bind(),
                documentType = Arb.string(8..12).orNull().bind(),
                documentNumber = Arb.string(8..12).orNull().bind(),
                email = Arb.string(8..12).orNull().bind(),
                phone = Arb.string(8..12).orNull().bind(),
            )
        }.getOrNull()
    }
    val coordinatesGen = arbitrary {
        Accepted.Coordinates(
            lat = Arb.bigDecimal().bind().rem((180).toBigDecimal()).abs(),
            lng = Arb.bigDecimal().bind().rem((180).toBigDecimal()).abs(),
        )
    }
    val discountGen = arbitrary {
        Accepted.Discount(
            by = Accepted.AssumedBy.Restaurant,
            value = Arb.bigDecimal().bind().abs(),
            promoType = Arb.enum<Accepted.PromoType>().bind(),
            promoId = Arb.string(4..6).orNull().bind(),
        )
    }
    val priceGen = arbitrary {
        Accepted.Price(
            gross = Arb.bigDecimal().bind().abs(),
            discounts = Arb.list(discountGen, 0..2).bind()
        )
    }
    val locationGen = arbitrary {
        Accepted.Location(
            address = Arb.string(10..20).bind(),
            city = Arb.string(10..20).bind(),
            coordinates = coordinatesGen.orNull().bind(),
            notes = Arb.string(15..25).orNull().bind()
        )
    }
    val shippingDeliveryGen = arbitrary {
        when (Arb.enum<Accepted.AssumedBy>().bind()) {
            Accepted.AssumedBy.Restaurant -> Accepted.Shipping.Delivery.ByRestaurant(
                location = locationGen.bind(),
                price = priceGen.bind()
            )
            Accepted.AssumedBy.Platform -> Accepted.Shipping.Delivery.ByPlatform(
                location = locationGen.orNull().bind(),
                price = priceGen.bind()
            )
        }
    }

    val shippingGen = arbitrary {
        when (Arb.enum<Accepted.ShippingMethod>().bind()) {
            Accepted.ShippingMethod.Delivery -> shippingDeliveryGen.bind()
            Accepted.ShippingMethod.PickUp -> Accepted.Shipping.PickUp
        }
    }

    fun itemGen(): Arb<Accepted.Item> = arbitrary {
        Accepted.Item(
            sku = Arb.string(5..10).bind(),
            name = Arb.string(8..14).bind(),
            units = Arb.int(1..3).bind(),
            unitPrice = priceGen.bind(),
            comments = Arb.string(5..15).orNull().bind(),
            modifiers = Arb.list(itemGen(), 0..1).bind()
        )
    }

    val cartGen = arbitrary {
        Accepted.Cart(
            items = Arb.list(itemGen(), 1..3).bind(),
            discounts = Arb.list(discountGen, 0..2).bind()
        )
    }
    val storeGen = arbitrary {
        Accepted.Store(
            id = Arb.string(5..25).bind(),
            name = Arb.string(10..20).bind()
        )
    }
    val externalGen = arbitrary {
        Accepted.External(
            id = Arb.string(5..15).bind(),
            displayId = Arb.int(0..100).orNull().bind()?.toString(),
            store = storeGen.bind(),
            createdAt = Instant.now()
        )
    }
    val surchargeGen = arbitrary {
        Accepted.Surcharge(
            by = Arb.enum<Accepted.AssumedBy>().bind(),
            price = priceGen.bind()
        )
    }
    val incomingOrderGen = arbitrary {
        val country = Arb.enum<Country>().bind()
        Incoming.Order(
            uid = Arb.string(20).bind(),
            country = country,
            kitchen = kitchenGen.bind(),
            brand = brandGen.bind(),
            platform = Arb.enum<DeliveryPlatform>().bind(),
            customer = nullableCustomerGen.bind(),
            shipping = shippingGen.bind(),
            payment = Accepted.Payment(
                currency = country.paymentCurrency,
                method = Arb.enum<PaymentMethod>().orNull().bind()
            ),
            cart = cartGen.bind(),
            external = externalGen.bind(),
            surcharges = Arb.list(Arb.string(5..8), 0..1).bind().associateWith {
                surchargeGen.bind()
            },
            receivedAt = Instant.now(),
        )
    }
}
```
When I try to get 1 sample from incomingOrderGen, that happens (sometimes)

**Comment by caeus** [comment]
I'm trying replacing `.bind()` with more verbose `flatMap`.
so instead of 

```kotlin
val someGen = arbitrary{
  doSomething(someOtherGen1.bind(), someOtherGen2.bind())
}

```

I'll do

```kotlin
val someGen = someOtherGen1.flatMap{
  someOther1-> 
  someOtherGen1.map{ someOther2
   doSomething(someOther1, someOther2)
  }
  
}
```
It's super annoying, but I think it could solve the problem

**Comment by caeus** [comment]
It seems it's the `itemGen`... so basically, recursive generators. Is there a way to build them so that they don't do flakily end up in a stackoverflow?

**Comment by caeus** [comment]
So... I fixed it like this.

the flatMap idea didn't actually work. What worked (I don't understand why) is this:
I replaced 
```kotlin
Arb.list(itemGen(), 0..1).bind()
```
for
```kotlin
Arb.list(Arb.boolean(),0..1).bind().map{
  it.map{
    itemGen().bind()
  }
}
```

It can be further reduced, but it works...

**Comment by myuwono** [comment]
i see - we need to fix this. Arb.flatMap doesn't seem to be stack-safe. I'll look into this. I believe it's possible to implement a trampolined version of that.
