### ISSUE TITLE
`log()` with `KOTEST_DEBUG` breaks execution because of hard-coded, non-existing log file

### ISSUE THREAD

**Issue by njokipal** [kotest/kotest#3027]
**Which version of Kotest are you using** Version 5.0.2

I'm using version 5.0.2. Logging messages is possible using the `log()` (full path reference of method: `/<gradle cache dir>/io.kotest/kotest-common-jvm/5.0.2/82ca5e911148de83261c956bf591c27f0facc86c/kotest-common-jvm-5.0.2-sources.jar!/commonMain/io/kotest/mpp/logger.kt:28`) method. The method will however not log anything as it uses the `isLoggingEnabled()` (`/<...>/io.kotest/kotest-common-jvm/5.0.2/82ca5e911148de83261c956bf591c27f0facc86c/kotest-common-jvm-5.0.2-sources.jar!/commonMain/io/kotest/mpp/logger.kt:11`), which in turn checks for the `KOTEST_DEBUG` system variable.

When the variable is set as `true`, all tests will fail due to non-existing log file that is hard-coded into the code in `/<...>/io.kotest/kotest-common-jvm/5.0.2/82ca5e911148de83261c956bf591c27f0facc86c/kotest-common-jvm-5.0.2-sources.jar!/jvmMain/io/kotest/mpp/writeLog.kt`:7 (`/home/sam/development/workspace/kotest/kotest/kotest.log`)

```
failed to execute tests
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 4.
	...
Caused by: org.junit.platform.commons.JUnitException: TestEngine with ID 'kotest' failed to discover tests
	...
Caused by: java.io.FileNotFoundException: /home/sam/development/workspace/kotest/kotest/kotest.log (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:158)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:82)
	at io.kotest.mpp.WriteLogKt$file$2.invoke(writeLog.kt:7)
	at io.kotest.mpp.WriteLogKt$file$2.invoke(writeLog.kt:7)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.kotest.mpp.WriteLogKt.getFile(writeLog.kt:7)
	at io.kotest.mpp.WriteLogKt.writeLog(writeLog.kt:11)
	at io.kotest.mpp.LoggerKt.log(logger.kt:34)
	at io.kotest.mpp.LoggerKt.log(logger.kt:29)
	at io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine.discover(KotestJunitPlatformTestEngine.kt:97)
	at io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine.discover(KotestJunitPlatformTestEngine.kt:30)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:103)
	... 25 more
```

**Comment by sksamuel** [comment]
This log isn't intended for public use but kotest internally.
In a future release we'll rename it to internalLog so it's clearer.

**Comment by njokipal** [comment]
Ah, I see. Too bad, I thought I stroke some gold finding that function as I was in need for an engine-managed logger for my test cases. I'll migrate to another implementation then.

**Comment by sksamuel** [comment]
This might be what you want https://kotest.io/docs/framework/logging.html
