### ISSUE TITLE
Nested annotation doesn't work with inner class 

### ISSUE THREAD

**Issue by cjlee38** [kotest/kotest#3103]
**Which version of Kotest are you using**

5.2.3

Hi, I'm trying to migrate test framework from Junit5 to kotest. 

The test codes in my project are written in with DCI pattern using `Nested` annotation. To ensure compatibility, I simply added AnnotationSpec on my test classes, including inner class but it goes into failure with following messages

`java.lang.IllegalArgumentException: object is not an instance of declaring class`

I assume that this is because 'inner classes' are not instantiated.

I know there are other specs(styles) which are proper in DCI pattern, but I think this should be fixed if 'annotation spec' is originally intended for easy migration from Junit. thanks

**Comment by aSemy** [comment]
Basically the bug is here 

https://github.com/kotest/kotest/blob/4af10c624be33d39b88d7241765fdffb08758999/kotest-framework/kotest-framework-api/src/jvmMain/kotlin/io/kotest/core/spec/style/AnnotationSpec.kt#L139

Here's what I think is going on

1. `AnnotationSpec` finds all top-level `@Test`s no problem
2. It then finds all nested classes 
    https://github.com/kotest/kotest/blob/4af10c624be33d39b88d7241765fdffb08758999/kotest-framework/kotest-framework-api/src/jvmMain/kotlin/io/kotest/core/spec/style/AnnotationSpec.kt#L90
3. It then creates a lazy test-invocation for each `@Test` in each nested class
    https://github.com/kotest/kotest/blob/4af10c624be33d39b88d7241765fdffb08758999/kotest-framework/kotest-framework-api/src/jvmMain/kotlin/io/kotest/core/spec/style/AnnotationSpec.kt#L139
4. But it doesn't 'switch classes' - `this@AnnotationSpec` refers to the top level annotation spec, NOT the nested one. Therefore, when the test is executed, it fails.

```none
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at kotlin.reflect.full.KCallables.callSuspend(KCallables.kt:54)
	at io.kotest.core.spec.style.AnnotationSpec$callNotExpectingException$1.invokeSuspend(AnnotationSpec.kt:132)
	at io.kotest.core.spec.style.AnnotationSpec$callNotExpectingException$1.invoke(AnnotationSpec.kt)
	at io.kotest.core.spec.style.AnnotationSpec$callNotExpectingException$1.invoke(AnnotationSpec.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$innerExecute$1.invokeSuspend(TestCaseExecutor.kt:81)
	at io.kotest.engine.test.TestCaseExecutor$execute$innerExecute$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$innerExecute$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.interceptors.CoroutineDebugProbeInterceptor.intercept(CoroutineDebugProbeInterceptor.kt:29)
	at io.kotest.engine.test.TestCaseExecutor$execute$2$1.invokeSuspend(TestCaseExecutor.kt:90)
	at io.kotest.engine.test.TestCaseExecutor$execute$2$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$2$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.test.interceptors.InvocationTimeoutInterceptor$intercept$3.invokeSuspend(InvocationTimeoutInterceptor.kt:43)
...
```

I'm not sure how to fix this. Maybe add a `KClass` parameter to `callExpectingException(...)`? Or refactor `AnnotationSpec` so it inherits from something like `ContainerScope`, and `@Nested` will register a container? 

I've made a PR with a failing test, and a couple of tidy-ups. I'm not sure how to fix it, so I'll make the PR in case someone else finds my progress so far useful.

**Comment by aSemy** [comment]
This should not be closed, because `@Nested` tests are a support feature that should work as documented.

**Comment by cjlee38** [comment]
Is there any progress about this issue? I've debugged this and found some clues.

I think the problem is caused basically from this line.

https://github.com/kotest/kotest/blob/26f2c25079d33d34338f99479b52e04b2dafe9a6/kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/spec/Materializer.kt#L40

The descriptor of `TestCase` is class on outside, not inside(I mean, nested). Let's say I have tests as below

```kotlin
class OutsideTest : AnnotationSpec() {
    @Test
    fun foo() {
        println("foo")
    }

    @Nested
    class InsideTest : AnnotationSpec() {
        @Test
        fun bar() {
            println("bar")
        }
    }
}
```

Then, descriptor of `TestCase` for `bar` is looks like this.

```
SpecDescriptor(id=DescriptorId(value=kotest.nested.OutsideTest), kclass=class kotest.nested.OutsideTest)TestCase {
```

So, engine tries to to invoke `bar` with instance of `OutsideTest`, then it fails.

I found this, but it is hard to fix this to me. I hope anyone resolve this problem. thanks.

p.s. Current tests for annotation spec only test if `TestEngineLauncher` can find `TestCase` 
for example, `https://github.com/kotest/kotest/blob/master/kotest-framework/kotest-framework-engine/src/jvmTest/kotlin/com/sksamuel/kotest/engine/spec/annotation/AnnotationSpecTest.kt`

**Comment by jacekgajek** [comment]
I also faced this issue.

After switching to 6.0.0.M4 kotest version the exception changed to 

```
wrong number of arguments: 0 expected: 1
java.lang.IllegalArgumentException: wrong number of arguments: 0 expected: 1
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:59)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at io.kotest.core.spec.style.AnnotationSpec.findRootTests(AnnotationSpec.kt:101)
	at io.kotest.core.spec.style.AnnotationSpec.findNestedTests(AnnotationSpec.kt:115)
	at io.kotest.core.spec.style.AnnotationSpec.rootTests(AnnotationSpec.kt:88)
	at io.kotest.engine.spec.Materializer.materialize(Materializer.kt:42)
	at io.kotest.engine.spec.SpecExecutor$execute$6$1.invokeSuspend(SpecExecutor.kt:101)
	at io.kotest.engine.spec.SpecExecutor$execute$6$1.invoke(SpecExecutor.kt)
	at io.kotest.engine.spec.SpecExecutor$execute$6$1.invoke(SpecExecutor.kt)
	at io.kotest.engine.spec.SpecExecutor$runInstancePipeline$innerExecute$1.invoke-gIAlu-s(SpecExecutor.kt:179)
	at io.kotest.engine.spec.interceptor.instance.AfterSpecListenerInterceptor.intercept-0E7RQCE(AfterSpecListenerInterceptor.kt:31)
	at io.kotest.engine.spec.interceptor.SpecInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecInterceptorPipeline.kt:51)
	at io.kotest.engine.spec.interceptor.instance.BeforeSpecFailureInterceptor.intercept-0E7RQCE(BeforeSpecFailureInterceptor.kt:17)
	at io.kotest.engine.spec.interceptor.SpecInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecInterceptorPipeline.kt:51)
	at io.kotest.engine.spec.interceptor.instance.InlineTagSpecInterceptor.intercept-0E7RQCE(InlineTagSpecInterceptor.kt:36)
	at io.kotest.engine.spec.interceptor.SpecInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecInterceptorPipeline.kt:51)
	at io.kotest.engine.spec.interceptor.instance.SpecExtensionInterceptor$intercept$2.invokeSuspend(SpecExtensionInterceptor.kt:20)
	at io.kotest.engine.spec.interceptor.instance.SpecExtensionInterceptor$intercept$2.invoke(SpecExtensionInterceptor.kt)
	at io.kotest.engine.spec.interceptor.instance.SpecExtensionInterceptor$intercept$2.invoke(SpecExtensionInterceptor.kt)
	at io.kotest.engine.spec.SpecExtensions$intercept$initial$1.invokeSuspend(SpecExtensions.kt:145)
	at io.kotest.engine.spec.SpecExtensions$intercept$initial$1.invoke(SpecExtensions.kt)
	at io.kotest.engine.spec.SpecExtensions$intercept$initial$1.invoke(SpecExtensions.kt)
	at io.kotest.engine.spec.SpecExtensions.intercept(SpecExtensions.kt:154)
	at io.kotest.engine.spec.interceptor.instance.SpecExtensionInterceptor.intercept-0E7RQCE(SpecExtensionInterceptor.kt:20)
	at io.kotest.engine.spec.interceptor.SpecInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecInterceptorPipeline.kt:51)
	at io.kotest.engine.spec.interceptor.instance.ProjectContextInterceptor$intercept$2.invokeSuspend(ProjectContextInterceptor.kt:26)
	at io.kotest.engine.spec.interceptor.instance.ProjectContextInterceptor$intercept$2.invoke(ProjectContextInterceptor.kt)
	at io.kotest.engine.spec.interceptor.instance.ProjectContextInterceptor$intercept$2.invoke(ProjectContextInterceptor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndspatched(Undispatched.kt:66)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:43)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at io.kotest.engine.spec.interceptor.instance.ProjectContextInterceptor.intercept-0E7RQCE(ProjectContextInterceptor.kt:25)
	at io.kotest.engine.spec.interceptor.SpecInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecInterceptorPipeline.kt:51)
	at io.kotest.engine.spec.interceptor.instance.CoroutineDispatcherFactorySpecInterceptor.intercept-0E7RQCE(CoroutineDispatcherFactorySpecInterceptor.kt:39)
	at io.kotest.engine.spec.interceptor.SpecInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecInterceptorPipeline.kt:51)
	at io.kotest.engine.spec.interceptor.instance.ProjectConfigResolverSpecInterceptor$intercept$2.invokeSuspend(ProjectConfigResolverSpecInterceptor.kt:25)
	at io.kotest.engine.spec.interceptor.instance.ProjectConfigResolverSpecInterceptor$intercept$2.invoke(ProjectConfigResolverSpecInterceptor.kt)
	at io.kotest.engine.spec.interceptor.instance.ProjectConfigResolverSpecInterceptor$intercept$2.invoke(ProjectConfigResolverSpecInterceptor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndspatched(Undispatched.kt:66)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:43)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at io.kotest.engine.spec.interceptor.instance.ProjectConfigResolverSpecInterceptor.intercept-0E7RQCE(ProjectConfigResolverSpecInterceptor.kt:24)
	at io.kotest.engine.spec.interceptor.SpecInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecInterceptorPipeline.kt:51)
	at io.kotest.engine.spec.interceptor.instance.EngineContextInterceptor$intercept$2.invokeSuspend(EngineContextInterceptor.kt:24)
	at io.kotest.engine.spec.interceptor.instance.EngineContextInterceptor$intercept$2.invoke(EngineContextInterceptor.kt)
	at io.kotest.engine.spec.interceptor.instance.EngineContextInterceptor$intercept$2.invoke(EngineContextInterceptor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndspatched(Undispatched.kt:66)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:43)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at io.kotest.engine.spec.interceptor.instance.EngineContextInterceptor.intercept-0E7RQCE(EngineContextInterceptor.kt:23)
	at io.kotest.engine.spec.interceptor.SpecInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecInterceptorPipeline.kt:51)
	at io.kotest.engine.spec.interceptor.instance.CoroutineScopeInterceptor$intercept$2.invokeSuspend(CoroutineScopeInterceptor.kt:22)
	at io.kotest.engine.spec.interceptor.instance.CoroutineScopeInterceptor$intercept$2.invoke(CoroutineScopeInterceptor.kt)
	at io.kotest.engine.spec.interceptor.instance.CoroutineScopeInterceptor$intercept$2.invoke(CoroutineScopeInterceptor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndspatched(Undispatched.kt:66)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:43)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:286)
	at io.kotest.engine.spec.interceptor.instance.CoroutineScopeInterceptor.intercept-0E7RQCE(CoroutineScopeInterceptor.kt:20)
	at io.kotest.engine.spec.interceptor.SpecInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecInterceptorPipeline.kt:51)
	at io.kotest.engine.spec.interceptor.SpecInterceptorPipeline.execute-BWLJW6A(SpecInterceptorPipeline.kt:54)
	at io.kotest.engine.spec.SpecExecutor.runInstancePipeline-BWLJW6A(SpecExecutor.kt:182)
	at io.kotest.engine.spec.SpecExecutor.access$runInstancePipeline-BWLJW6A(SpecExecutor.kt:41)
	at io.kotest.engine.spec.SpecExecutor$execute$6.invokeSuspend(SpecExecutor.kt:100)
	at io.kotest.engine.spec.SpecExecutor$execute$6.invoke(SpecExecutor.kt)
	at io.kotest.engine.spec.SpecExecutor$execute$6.invoke(SpecExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndspatched(Undispatched.kt:66)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:43)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at io.kotest.engine.spec.SpecExecutor.execute-gIAlu-s(SpecExecutor.kt:98)
	at io.kotest.engine.spec.SpecExecutor.executeInDelegate-gIAlu-s(SpecExecutor.kt:65)
	at io.kotest.engine.spec.SpecExecutor.access$executeInDelegate-gIAlu-s(SpecExecutor.kt:41)
	at io.kotest.engine.spec.SpecExecutor$execute$innerExecute$1.invoke-gIAlu-s(SpecExecutor.kt:57)
	at io.kotest.engine.spec.interceptor.ref.callbacks.FinalizeSpecInterceptor.intercept-0E7RQCE(FinalizeSpecInterceptor.kt:19)
	at io.kotest.engine.spec.interceptor.SpecRefInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecRefInterceptorPipeline.kt:49)
	at io.kotest.engine.spec.interceptor.ref.callbacks.PrepareSpecInterceptor.intercept-0E7RQCE(PrepareSpecInterceptor.kt:20)
	at io.kotest.engine.spec.interceptor.SpecRefInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecRefInterceptorPipeline.kt:49)
	at io.kotest.engine.spec.interceptor.ref.callbacks.SpecFinishedInterceptor.intercept-0E7RQCE(SpecFinishedInterceptor.kt:19)
	at io.kotest.engine.spec.interceptor.SpecRefInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecRefInterceptorPipeline.kt:49)
	at io.kotest.engine.spec.interceptor.ref.callbacks.SpecStartedInterceptor.intercept-0E7RQCE(SpecStartedInterceptor.kt:19)
	at io.kotest.engine.spec.interceptor.SpecRefInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecRefInterceptorPipeline.kt:49)
	at io.kotest.engine.spec.interceptor.ref.SpecRefExtensionInterceptor.intercept-0E7RQCE(SpecRefExtensionInterceptor.kt:29)
	at io.kotest.engine.spec.interceptor.SpecRefInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecRefInterceptorPipeline.kt:49)
	at io.kotest.engine.spec.interceptor.ref.enabled.RequiresTagInterceptor.intercept-0E7RQCE(RequiresTagInterceptor.kt:31)
	at io.kotest.engine.spec.interceptor.SpecRefInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecRefInterceptorPipeline.kt:49)
	at io.kotest.engine.spec.interceptor.ref.enabled.TagsInterceptor.intercept-0E7RQCE(TagsInterceptor.kt:33)
	at io.kotest.engine.spec.interceptor.SpecRefInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecRefInterceptorPipeline.kt:49)
	at io.kotest.engine.spec.interceptor.ref.DescriptorFilterSpecRefInterceptor.intercept-0E7RQCE(DescriptorFilterSpecRefInterceptor.kt:40)
	at io.kotest.engine.spec.interceptor.SpecRefInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecRefInterceptorPipeline.kt:49)
	at io.kotest.engine.spec.interceptor.ref.ApplyExtensionsInterceptor.intercept-0E7RQCE(ApplyExtensionsInterceptor.kt:36)
	at io.kotest.engine.spec.interceptor.SpecRefInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecRefInterceptorPipeline.kt:49)
	at io.kotest.engine.spec.interceptor.ref.enabled.IgnoredSpecInterceptor.intercept-0E7RQCE(IgnoredSpecInterceptor.kt:47)
	at io.kotest.engine.spec.interceptor.SpecRefInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecRefInterceptorPipeline.kt:49)
	at io.kotest.engine.spec.interceptor.ref.enabled.DisabledIfInterceptor.intercept-0E7RQCE(DisabledIfInterceptor.kt:44)
	at io.kotest.engine.spec.interceptor.SpecRefInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecRefInterceptorPipeline.kt:49)
	at io.kotest.engine.spec.interceptor.ref.enabled.EnabledIfInterceptor.intercept-0E7RQCE(EnabledIfInterceptor.kt:39)
	at io.kotest.engine.spec.interceptor.SpecRefInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecRefInterceptorPipeline.kt:49)
	at io.kotest.engine.spec.interceptor.ref.enabled.RequiresPlatformInterceptor.intercept-0E7RQCE(RequiresPlatformInterceptor.kt:25)
	at io.kotest.engine.spec.interceptor.SpecRefInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecRefInterceptorPipeline.kt:49)
	at io.kotest.engine.spec.ClassVisibilitySpecRefInterceptor.intercept-0E7RQCE(ClassVisibilitySpecRefInterceptor.kt:29)
	at io.kotest.engine.spec.interceptor.SpecRefInterceptorPipeline$execute$3$1.invoke-gIAlu-s(SpecRefInterceptorPipeline.kt:49)
	at io.kotest.engine.spec.interceptor.SpecRefInterceptorPipeline.execute-0E7RQCE(SpecRefInterceptorPipeline.kt:52)
	at io.kotest.engine.spec.SpecExecutor.execute(SpecExecutor.kt:60)
	at io.kotest.engine.TestSuiteScheduler.executeIfNotFailedFast(TestSuiteScheduler.kt:96)
	at io.kotest.engine.TestSuiteScheduler.access$executeIfNotFailedFast(TestSuiteScheduler.kt:28)
	at io.kotest.engine.TestSuiteScheduler$schedule$11$1$2.invokeSuspend(TestSuiteScheduler.kt:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith$$$capture(ContinuationImpl.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:94)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:70)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.engine.RunBlockingKt.runBlocking(runBlocking.kt:3)
	at io.kotest.engine.launcher.MainKt.main(main.kt:97)
```

Flattening the test (removing inner classes and Nested annotations) "fixes" the issue
