### ISSUE TITLE
kotest-extensions-testcontainers seems to be incompatible with kotest 5.4.1

### ISSUE THREAD

**Issue by abendt** [kotest/kotest#3135]
**Which version of Kotest are you using**

i am using kotest with the kotest-extensions-testcontainers extension.
After upgrading to kotest version _5.4.1_ i am seeing this exception:

```
Caused by:
        java.lang.NoSuchMethodError: 'io.kotest.core.descriptors.TestPath io.kotest.core.descriptors.Descriptor$TestDescriptor.path(boolean)'
            at io.kotest.extensions.testcontainers.TestLifecycleAwareListenerKt$toTestDescription$1.getFilesystemFriendlyName(TestLifecycleAwareListener.kt:28)
            at org.testcontainers.containers.BrowserWebDriverContainer.afterTest(BrowserWebDriverContainer.java:346)
            at io.kotest.extensions.testcontainers.TestContainerExtension$lifecycleAfterTest$2.invokeSuspend(TestContainerExtension.kt:89)
            at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
            at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
            at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
            at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
            at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
            at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
            at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
            at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

I assume the extension must be released to be compatible with latest kotest?

**Comment by sksamuel** [comment]
Can you try kotest-extensions-testcontainers 1.3.4 ?

**Comment by abendt** [comment]
thanks @sksamuel that fixed the issue

**Comment by abendt** [comment]
@sksamuel small thing:

apparently the extension now requires jdk11. before it also worked with java8. this is not an issue for me, just might be an unexpected change for others when they are updating from 1.3.3 to 1.3.4

```
   > Could not resolve all files for configuration ':testCompileClasspath'.
      > Could not resolve io.kotest.extensions:kotest-extensions-testcontainers:1.3.4.
        Required by:
            project :
         > No matching variant of io.kotest.extensions:kotest-extensions-testcontainers:1.3.4 was found. The consumer was configured to find an API of a library compatible with Java 8, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'apiElements' capability io.kotest.extensions:kotest-extensions-testcontainers:1.3.4 declares an API of a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
             - Variant 'javadocElements' capability io.kotest.extensions:kotest-extensions-testcontainers:1.3.4 declares a runtime of a component, and its dependencies declared externally:
                 - Incompatible because this component declares documentation and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about its target Java version (required compatibility with Java 8)
                     - Doesn't say anything about its elements (required them preferably in the form of class files)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
             - Variant 'runtimeElements' capability io.kotest.extensions:kotest-extensions-testcontainers:1.3.4 declares a runtime of a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
                 - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
             - Variant 'sourcesElements' capability io.kotest.extensions:kotest-extensions-testcontainers:1.3.4 declares a runtime of a component, and its dependencies declared externally:
                 - Incompatible because this component declares documentation and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about its target Java version (required compatibility with Java 8)
                     - Doesn't say anything about its elements (required them preferably in the form of class files)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
```
