### ISSUE TITLE
Kotest + Allure: NoSuchMethodError: io.kotest.core.descriptors.Descriptor$DefaultImpls.path$default(...)

### ISSUE THREAD

**Issue by iRomul** [kotest/kotest#3152]
Hi! I'm encountering with an error `java.lang.NoSuchMethodError: 'io.kotest.core.descriptors.TestPath io.kotest.core.descriptors.Descriptor$DefaultImpls.path$default(io.kotest.core.descriptors.Descriptor, boolean, int, java.lang.Object)'` while trying to run minimal test with Allure extension.
Full exception:
```
java.lang.NoSuchMethodError: 'io.kotest.core.descriptors.TestPath io.kotest.core.descriptors.Descriptor$DefaultImpls.path$default(io.kotest.core.descriptors.Descriptor, boolean, int, java.lang.Object)'
io.kotest.engine.extensions.ExtensionException$BeforeTestException: java.lang.NoSuchMethodError: 'io.kotest.core.descriptors.TestPath io.kotest.core.descriptors.Descriptor$DefaultImpls.path$default(io.kotest.core.descriptors.Descriptor, boolean, int, java.lang.Object)'
	at app//io.kotest.engine.test.TestExtensions$beforeTestBeforeAnyBeforeContainer$errors$4$2.invoke(TestExtensions.kt:89)
	at app//io.kotest.engine.test.TestExtensions$beforeTestBeforeAnyBeforeContainer$errors$4$2.invoke(TestExtensions.kt:89)
	at app//io.kotest.common.ResultsKt.mapError(results.kt:8)
	at app//io.kotest.engine.test.TestExtensions.beforeTestBeforeAnyBeforeContainer-gIAlu-s(TestExtensions.kt:89)
        ...
Caused by: java.lang.NoSuchMethodError: 'io.kotest.core.descriptors.TestPath io.kotest.core.descriptors.Descriptor$DefaultImpls.path$default(io.kotest.core.descriptors.Descriptor, boolean, int, java.lang.Object)'
	at io.kotest.extensions.allure.AllureWriter.startTestCase(AllureWriter.kt:77)
	at io.kotest.extensions.allure.AllureTestReporter.beforeTest(AllureTestReporter.kt:16)
	at io.kotest.engine.test.TestExtensions.beforeTestBeforeAnyBeforeContainer-gIAlu-s(TestExtensions.kt:88)
	... 35 more
```

Dependencies used in project:
```
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.7.10"
    id("io.qameta.allure") version "2.10.0"
    java
}

allure {
    adapter.autoconfigure.set(false)
    version.set("2.17.3")
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation(kotlin("reflect"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
    implementation("org.slf4j:slf4j-log4j12:1.7.36")
    implementation(platform("com.fasterxml.jackson:jackson-bom:2.13.3"))
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.13.3")
    implementation("com.oracle.database.jdbc:ojdbc11:21.6.0.0.1")

    testImplementation("org.junit.jupiter:junit-jupiter:5.9.0")
    testImplementation("io.kotest:kotest-runner-junit5-jvm:5.4.2")
    testImplementation("io.kotest:kotest-assertions-core-jvm:5.4.2")
    testImplementation("io.kotest:kotest-property-jvm:5.4.2")
    testImplementation("io.kotest:kotest-common:5.4.2")
    testImplementation("io.kotest.extensions:kotest-extensions-allure:1.2.0")
}
```

Kotest config:
```
object ProjectConfig : AbstractProjectConfig() {
    override fun listeners() = listOf(AllureTestReporter())
}
```

Test class:
```
class SpecSampleTest : ShouldSpec({
    should("return 1") {
        1 shouldBe 1
    }
})
```

After a little bytecode research I had an assumption: AllureWriter class was compiled with `-Xjvm-default=disabled` option while io.kotest.core.descriptors.Descriptor was compiled with `-Xjvm-default=all` options which leads to the error here:

```
uuids[testCase.descriptor.path()] = uuid
```

Any ideas how to solve it?

Thanks!

**Comment by sksamuel** [comment]
Where do you see the -Xjvm-default flags?

**Comment by LeoColman** [comment]
What JDK are you using?
