### ISSUE TITLE
calling take(1) on a Gen sometimes returns an empty Sequence

### ISSUE THREAD

**Issue by rprinsen** [kotest/kotest#3193]
**Which version of Kotest are you using**
5.3.1

In our project we have implemented generators to generate test data for us.
In some cases we just want to use the generator to generate one instance of the test data object.

We call `take(1).first()` on the generator for that. However, in some cases we get a `Collection is empty.` exception.
I've been trying to figure out why this happens, if it's by design, and if there are other methods I can call to reliably get 1 instance from a generator, but haven't figured it out yet.

full stacktrace:
`
Collection is empty.
java.util.NoSuchElementException: Collection is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.random(_Collections.kt:560)
	at io.kotest.property.arbitrary.CollectionsKt$element$1.invokeSuspend(collections.kt:15)
	at io.kotest.property.arbitrary.CollectionsKt$element$1.invoke(collections.kt)
	at io.kotest.property.arbitrary.CollectionsKt$element$1.invoke(collections.kt)
	at io.kotest.property.arbitrary.BuildersKt$arbitrary$1.invokeSuspend(builders.kt:22)
	at io.kotest.property.arbitrary.BuildersKt$arbitrary$1.invoke(builders.kt)
	at io.kotest.property.arbitrary.BuildersKt$arbitrary$1.invoke(builders.kt)
	at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1$singleShotArb$restrictedContinuation$1.invokeSuspend(builders.kt:236)
	at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1$singleShotArb$restrictedContinuation$1.invoke(builders.kt)
	at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1$singleShotArb$restrictedContinuation$1.invoke(builders.kt)
	at io.kotest.property.arbitrary.SingleShotArbContinuation.createSingleShotArb(builders.kt:395)
	at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1.singleShotArb(builders.kt:247)
	at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1.sample(builders.kt:216)
	at io.kotest.property.Arb$samples$1.invoke(Gen.kt:115)
	at io.kotest.property.Arb$samples$1.invoke(Gen.kt:115)
	at kotlin.sequences.GeneratorSequence$iterator$1.calcNext(Sequences.kt:591)
	at kotlin.sequences.GeneratorSequence$iterator$1.next(Sequences.kt:597)
	at io.kotest.property.Gen$generate$1.invoke(Gen.kt:48)
	at io.kotest.property.Gen$generate$1.invoke(Gen.kt:44)
	at kotlin.sequences.GeneratorSequence$iterator$1.calcNext(Sequences.kt:591)
	at kotlin.sequences.GeneratorSequence$iterator$1.hasNext(Sequences.kt:609)
	at kotlin.sequences.TakeSequence$iterator$1.hasNext(Sequences.kt:421)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
	at io.kotest.property.arbitrary.CollectionsKt$list$2.invokeSuspend(collections.kt:107)
	at io.kotest.property.arbitrary.CollectionsKt$list$2.invoke(collections.kt)
	at io.kotest.property.arbitrary.CollectionsKt$list$2.invoke(collections.kt)
	at io.kotest.property.arbitrary.BuildersKt$arbitrary$8$delegate$1.invokeSuspend(builders.kt:105)
	at io.kotest.property.arbitrary.BuildersKt$arbitrary$8$delegate$1.invoke(builders.kt)
	at io.kotest.property.arbitrary.BuildersKt$arbitrary$8$delegate$1.invoke(builders.kt)
	at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1$singleShotArb$restrictedContinuation$1.invokeSuspend(builders.kt:236)
	at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1$singleShotArb$restrictedContinuation$1.invoke(builders.kt)
	at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1$singleShotArb$restrictedContinuation$1.invoke(builders.kt)
	at io.kotest.property.arbitrary.SingleShotArbContinuation.createSingleShotArb(builders.kt:395)
	at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1.singleShotArb(builders.kt:247)
	at io.kotest.property.arbitrary.BuildersKt$arbitraryBuilder$1.sample(builders.kt:216)
	at io.kotest.property.arbitrary.BuildersKt$arbitrary$8.sample(builders.kt:103)
	at io.kotest.property.arbitrary.BindKt$bindN$1.sample(bind.kt:479)
	at io.kotest.property.arbitrary.TrampolineArb.sample(map.kt:71)
	at io.kotest.property.Arb$samples$1.invoke(Gen.kt:115)
	at io.kotest.property.Arb$samples$1.invoke(Gen.kt:115)
	at kotlin.sequences.GeneratorSequence$iterator$1.calcNext(Sequences.kt:591)
	at kotlin.sequences.GeneratorSequence$iterator$1.hasNext(Sequences.kt:609)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.TakeSequence$iterator$1.hasNext(Sequences.kt:421)
	at kotlin.sequences.SequencesKt___SequencesKt.first(_Sequences.kt:111)

`

**Comment by myuwono** [comment]
@rprinsen are you able to provide the code for the arb that throws? As well as how it was used?

**Comment by rprinsen** [comment]
Sure!
Basically i've created a extension function on Gen that will return 1 instance:

```
fun <T> Gen<T>.takeOne(random: RandomSource = RandomSource.default()): T =
    this.generate(random)
        .map { it.value }
        .take(1)
        .first()
```
and I call this on one of our custom generators, for instance:
```
  val dataSource = dataSourceGenerator(
            fields = Arb.of(product.data.keys.toList()),
            dataTypes = Arb.of(DataType.TEXT)
        ).takeOne()

```

the exception is thrown from the `.first()` part of  `takeOne()`

**Comment by myuwono** [comment]
I see, I can see how this exception can be thrown. 

Looking at this:
```kotlin
Collection is empty.
java.util.NoSuchElementException: Collection is empty.
at kotlin.collections.CollectionsKt___CollectionsKt.random(_Collections.kt:560)
at io.kotest.property.arbitrary.CollectionsKt$element$1.invokeSuspend(collections.kt:15)
```

It seems that in one of the  generators that you have defined in the codebase, `Arb.of(list)` may have been given an empty list. Would it be possible to check that @rprinsen?

That should have been an illegal operation and would ideally be rejected with an illegal argument instead. However, the current definition of `Arb.of` is missing a `require(list.isNotEmpty())` so users are given a rather misleading information on sample generation instead of on Arb construction.

**Comment by rprinsen** [comment]
Aah, that's it, 
`fields = Arb.of(product.data.keys.toList())` 
`product.data.keys` would sometimes return an empty list, because that object is generated too.

Ha, damn, property testing is awesome, but really hard to debug sometimes :)
Thanks for clearing this up @myuwono! a more clear error message would have been really helpful, nice to see you got a pull request already :)
