### ISSUE TITLE
shouldBeEqualToComparingFields causes InaccessibleObjectException exception

### ISSUE THREAD

**Issue by despinaotto** [kotest/kotest#3254]
We have Java 17 and everything has worked fine until we wanted to update our gradle version to  v7.5.1.
Our tests do not work anymore and we get this exception.

java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.lang.Object[] java.util.ArrayList.elementData accessible: module java.base does not "opens java.util" to unnamed module @a48b8e6
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at kotlin.reflect.jvm.KCallablesJvm.setAccessible(KCallablesJvm.kt:65)
	at io.kotest.matchers.equality.ReflectionKt$checkEqualityOfFieldsRecursively$fields$1.invoke(reflection.kt:586)
	at io.kotest.matchers.equality.ReflectionKt$checkEqualityOfFieldsRecursively$fields$1.invoke(reflection.kt:586)
	at kotlin.sequences.SequencesKt___SequencesKt$onEach$1.invoke(_Sequences.kt:2149)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
	at kotlin.sequences.SequencesKt___SequencesKt$sortedWith$1.iterator(_Sequences.kt:638)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
	at io.kotest.matchers.equality.ReflectionKt.checkEqualityOfFieldsRecursively(reflection.kt:589)
	at io.kotest.matchers.equality.ReflectionKt.checkEqualityOfFieldsRecursively$default(reflection.kt:572)
	at io.kotest.matchers.equality.ReflectionKt$beEqualComparingFields$1.test(reflection.kt:536)
	at io.kotest.matchers.ShouldKt.invokeMatcher(should.kt:43)
	at io.kotest.matchers.ShouldKt.should(should.kt:38)
	at io.kotest.matchers.equality.ReflectionKt.shouldBeEqualToComparingFields(reflection.kt:380)
	at io.kotest.matchers.equality.ReflectionKt.shouldBeEqualToComparingFields(reflection.kt:471)

**Comment by Kantis** [comment]
Could you try to to add `--add-opens=java.base/java.util=ALL-UNNAMED` to the arguments for the JVM that runs the tests? I think this happens because you're trying to use `shouldBeEqualToComparingFields` on an `ArrayList`?

If you run tests with gradle, you can add `org.gradle.jvmargs=--add-opens=java.base/java.util=ALL-UNNAMED` in gradle.properties

**Comment by seungdols** [comment]
@Kantis Hi, I have same issue. 

I use shouldBeEqualToComparingFields matcher for test
But I have error of InaccessibleObjectException in shouldBeEqualToComparingFields matcher.

```
Unable to make public final int java.util.LinkedHashMap$LinkedKeySet.size() accessible: module java.base does not "opens java.util" to unnamed module @3eb738bb
java.lang.reflect.InaccessibleObjectException: Unable to make public final int java.util.LinkedHashMap$LinkedKeySet.size() accessible: module java.base does not "opens java.util" to unnamed module @3eb738bb
```

kotest version: 5.8.0

**Comment by Kantis** [comment]
@seungdols did you try adding the JVM property?

**Comment by alshain** [comment]
@Kantis I've hit the same issue. Of course, the add-opens works, but is that really the way to go forward rather than special-casing this in kotest?
