### ISSUE TITLE
IDEA plugin is extremely slow to start tests

### ISSUE THREAD

**Issue by jlous** [kotest/kotest#3295]
Medium-sized project
Re-running single minimal tests using kotest plugin (preexisting run configs)
Measuring from "instantiating tests" appears,  until the green check mark is shown (i.e. excluding startup and build time)

- jUnit takes < 1s
- Kotest takes 22s

Making it hard to sell kotest to the teams

Kotest plugin 1.2.63 (and earlier)
IDEA 2022.2.3 (and earlier)

**Comment by sksamuel** [comment]
Can you try disabling scanning using the settings here:
https://kotest.io/docs/framework/framework-config-props.html

We are considering disabling automatic scanning by default in future releases if the impact is positive.

**Comment by janhoeve** [comment]
I had a similar issue, but more on _finishing_ the tests.
The actual tests were already completed (green), yet the 'root' test was showing a spinner for 5 seconds more before turning into green as well.

I figured out that I need to set _two_ properties to reduce the time to finish the tests from this 5 seconds to almost instantly.
```
kotest.framework.classpath.scanning.config.disable=true
kotest.framework.classpath.scanning.autoscan.disable=true
```

Some extra information; I created a few thread dumps to see what was going on in this 5 seconds period.
All were showing `classgraph` stuff:
```
	at sun.nio.ch.FileChannelImpl.readInternal(java.base@17.0.3/FileChannelImpl.java:835)
	at sun.nio.ch.FileChannelImpl.read(java.base@17.0.3/FileChannelImpl.java:824)
	at nonapi.io.github.classgraph.fileslice.reader.RandomAccessFileChannelReader.read(RandomAccessFileChannelReader.java:97)
	at nonapi.io.github.classgraph.fileslice.reader.RandomAccessFileChannelReader.readUnsignedShort(RandomAccessFileChannelReader.java:151)
	at nonapi.io.github.classgraph.fileslice.reader.RandomAccessFileChannelReader.readShort(RandomAccessFileChannelReader.java:146)
	at nonapi.io.github.classgraph.fastzipfilereader.FastZipEntry.getSlice(FastZipEntry.java:197)
	at io.github.classgraph.ClasspathElementZip$1.open(ClasspathElementZip.java:390)
	at io.github.classgraph.ClasspathElementZip$1.openClassfile(ClasspathElementZip.java:376)
	at io.github.classgraph.Classfile.<init>(Classfile.java:1969)
	at io.github.classgraph.Scanner$ClassfileScannerWorkUnitProcessor.processWorkUnit(Scanner.java:719)
	at io.github.classgraph.Scanner$ClassfileScannerWorkUnitProcessor.processWorkUnit(Scanner.java:641)
	at nonapi.io.github.classgraph.concurrency.WorkQueue.runWorkLoop(WorkQueue.java:246)
```
which makes sense given the name of these two properties ;)

**Comment by jlous** [comment]
@sksamuel Yes, this cuts the startup time quite dramatically.  Not quite down to junit levels, but definitely something I want!

**Comment by jlous** [comment]
Here are the execution times for a minimal dummy test in my project 
(timed from '"Instatiating tests" apears and until the green checkmark is shown):

- No config: 20s
- disable scanning.config only: 11s
- disable scanning.autoscan only: 11s
- disable both: 1-2s

Sadly, I need to use KotestProjectConfig, so I cannot disable config scanning, and only get half the gain.
Would it be possible to offer a faster config-scan option, for example specifying the location/name of the config class, or using a default fixed location?

Using run-configs to replace KotestProjectConfig is too brittle, relying on setings not in the repo

**Comment by sksamuel** [comment]
You can disable both and then set a system property to point to your config file.
`kotest.framework.config.fqn`

See
https://kotest.io/docs/framework/project-config.html#runtime-detection

**Comment by sksamuel** [comment]
Closing as the `kotest.framework.config.fqn` does everything required.
