### ISSUE TITLE
idea: composite matchers, MatcherResultBuilder

### ISSUE THREAD

**Issue by vlsi** [kotest/kotest#3343]
Currently, every matcher has to return exactly one result.

What do you think if a matcher was allowed to return several findings?

For instance, suppose I wanted adding a matcher that would verify if a database table is empty.

Here's a draft code

```kotlin
interface Table {
    val name: String
}

fun emptyTable(con: Connection) =
    object: Matcher<Table> {
        override fun test(value: Table): MatcherResult {
            con.createStatement().use { st ->
                val rs = st.executeQuery("select count(*) from ${st.enquoteIdentifier(value.name, false)}")
                // it would be nice to reuse "resultset must contain row" matcher here, but it's not possible
                rs.next()
                val count = rs.getInt(1)
                return MatcherResult(
                    count == 0,
                    { "Table ${value.name} is not empty, it contains $count rows" },
                    { "Table ${value.name} is empty" }
                )
            }
        }
    }
```

The usage would be

```kotlin
val tableUnderTest == ....

// verify that the table is empty in the given DB
tableUnderTest shouldBe emptyTable(con = databaseConnection)
```

So far so good, however, note how I can't really reuse "resultset must contain row" matcher (see https://github.com/kotest/kotest/issues/3339#issuecomment-1385336335).
On top of that, if the table is missing in the database, `executeQuery` would fail, and the assertion would be completely screwed.

However, suppose later I want to verify multiple database connections, not just one of them:

```kotlin
val tableUnderTest == ....

val databasesUnderTest: List<Connection>
// verify that the table is empty in the given DB
tableUnderTest shouldBe emptyTable(conections = databasesUnderTest)
```

I do not see what is the intended way to squeeze multiple assertion results into a single `MatchResult`.

Have you considered something as follows?

In other words, `MatcherResultBuilder` that will enable `Matcher` implementations to build composite result based on several checks.
At the same time, it could have its own `withClue` so the clues are added accordingly to the match results.

```kotlin
interface Table {
    val name: String
}

interface MatcherResultBuilder {
    fun failure(message: String, throwable: Throwable)
    fun addMatcherResult(result: MatcherResult)

    fun withClue(clue: () -> Any, thunk: () -> Unit)
}
fun buildMatcherResult(builder: MatcherResultBuilder.() -> Unit): MatcherResult {
    TODO("")
}

fun isEmpty(connections: List<Connection>) =
    object: Matcher<Table> {
        override fun test(value: Table): MatcherResult =
            buildMatcherResult {
                for (connection in connections) {
                    // TODO: use better DB names instead of Connection.toString()
                    withClue({ "Database $connection" }) {
                        connection.createStatement().use { st ->
                            val rs = try {
                                st.executeQuery(
                                    "select count(*) from ${
                                        st.enquoteIdentifier(
                                            value.name,
                                            false
                                        )
                                    }"
                                )
                            } catch (e: Exception) {
                                failure("Failed to query table ${value.name}", e)
                                // try next connection
                                return@use
                            }
                            // Probably we could factor
                            rs.next()
                            val count = rs.getInt(1)
                            addMatcherResult(
                                MatcherResult(
                                    count == 0,
                                    { "Table ${value.name} is not empty, it contains $count rows" },
                                    { "Table ${value.name} is empty" }
                                )
                            )
                        }
                    }
                }
            }
        }
    }
```

**Comment by vlsi** [comment]
Another case for composite matchers is `Matcher<T>.or`, `Matcher<T>.and`.

For instance:

```kotlin
12 shouldBe (between(0, 2) or between(0, 3))
```

=>

```
java.lang.AssertionError: 12 should be between (0, 3)
```

The error message is misleading. The actual test expected `between(0, 2) or between(0, 3)`, however, only the last expectation is printed in the message.

The same might happen for `and` as well: user might want to see all failing conditions, not just one of them.

For example:

```kotlin
"password" shouldBe (containADigit() and contain(Regex("[a-z]")) and contain(Regex("[A-Z]")))
```

The failure becomes

```
"password" should contain at least one digit
```

In practice, it might be better to see all the violations at once to better understand the requirements and fix all the bugs at once.

**Comment by vlsi** [comment]
Here's another candidate for composite matcher API are:

https://github.com/kotest/kotest/blob/aba6984d6a08530e931274f7a9f6e3b62a66b681/kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/eq/RegexEq.kt#L12-L16

https://github.com/kotest/kotest/blob/0ba14983d485b1b1caef0e5a2cd7402ba47e34d2/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/regex/RegexMatchers.kt#L24-L34

They implement pretty much the same thing, however, `regex shouldBe regex` fails with a bad message since it misses both expected and actual regex in the output message.

**Comment by sksamuel** [comment]
I like the idea of composite results. Do you think we could do that without breaking any existing matchers?

**Comment by pientaa** [comment]
@vlsi there are already [Data Class Matchers](https://kotest.io/docs/assertions/data-class-matchers.html). It seems to be partially what you're looking for. You can build your custom matcher with a composite result, but you need to build in on top of some class, it won't work for primitives though. IMHO #2894 could be reopened and I could extend this compose API to primitives, because I see advantages of how `and` and `or`  methods work right now and it seems the best solution due to not breaking any existing matcher. @sksamuel WDYT?

**Comment by vlsi** [comment]
@pientaa , data class matcher have no use for me. I have provided a sample of what I need: composing and comparing results from multiple databases. Data class matchers have absolutely no use there as it would be time-consuming to convert all of that to the data classes.

I incline that `and` and `or` are too limited, and the generic API should be builder-like.

I have spent some time on impementing composite matchers with kotest-assertions, and I incline I would rather give Atrium a try instead.

**Comment by pientaa** [comment]
@vlsi I think that _Data Class Matchers_ is not an appropriate naming, because it suggests it works only with `data class` which is not true (I'll create a PR with changes in documentation). You can compose a matcher even for an interface, so you don't need to convert it to the data classes

**Comment by pientaa** [comment]
Regarding confusing naming I created an issue #3405 and I'm going to fix the naming in a documentation

When it comes to the example with `Regex`, it seems to be doable with current `Matchet.Companion.compose` function

```kotlin
   fun composedRegexMatcher(options: Set<RegexOption>) = Matcher.compose(
      haveSameRegexOptionsMatcher(options) to Regex::pattern,
      haveSameRegexOptionsMatcher(options) to Regex::pattern
   )
   ```

**Comment by pientaa** [comment]
Regarding confusing naming I created an issue #3405 and I'm going to fix the naming in a documentation

When it comes to the example with Regex, it seems to be doable with current `Matcher.Companion.compose` function
```kotlin
fun composedRegexMatcher(regex: Regex) = Matcher.compose(
   haveSamePatternMatcher(regex.pattern) to Regex::pattern,
   haveSameRegexOptionsMatcher(regex.options) to Regex::pattern
)
```

**Comment by vlsi** [comment]
@pientaa , I appreciate your time on improving the naming (it does matter), however, I am pretty sure `Matcher.compose` targets only a small subset of cases (no matter the naming), and there should be a more generic approach.
Then, the signature `vararg pairs: Pair<Matcher<*>, ...` creates API that is hard to use properly since it would accept everything at a cost of failing in the runtime (e.g. `ClassCastException`).

I expect something like `assertSoftly { ... }`, except it should work for matchers. I described this in the very first comment of the issue (see `buildMatcherResult`)

----

```kotlin
   fun composedRegexMatcher(regex: Regex) = Matcher.compose(
      haveSamePatternMatcher(regex.pattern) to Regex::pattern,
      haveSameRegexOptionsMatcher(regex.options) to Regex::options
   )

   init {
      "test" {
         Regex("a.+b", IGNORE_CASE) shouldBe composedRegexMatcher(Regex("a.*b", DOT_MATCHES_ALL))
      }
    }
```

fails

```
class java.lang.String cannot be cast to class kotlin.text.Regex (java.lang.String is in module java.base of loader 'bootstrap'; kotlin.text.Regex is in unnamed module of loader 'app')
java.lang.ClassCastException: class java.lang.String cannot be cast to class kotlin.text.Regex (java.lang.String is in module java.base of loader 'bootstrap'; kotlin.text.Regex is in unnamed module of loader 'app')
	at io.kotest.matchers.regex.RegexMatchersKt$haveSamePatternMatcher$1.test(RegexMatchers.kt:52)
	at io.kotest.matchers.reflection.ComposeKt$compose$1.test(compose.kt:13)
	at io.kotest.matchers.ShouldKt.invokeMatcher(should.kt:43)
	at io.kotest.matchers.ShouldKt.should(should.kt:38)
	at io.kotest.matchers.ShouldKt.shouldBe(should.kt:19)
```

The reason is that `haveSamePatternMatcher` is `Matcher<Regex>`, so it expects `Regex` as an input, while `Regex::pattern` yields a string, and it causes `ClassCastException`

---

If I try something like

```kotlin
   fun composedRegexMatcher(regex: Regex) = Matcher.compose(
      equalityMatcher(regex.pattern) to Regex::pattern,
      equalityMatcher(regex.options) to Regex::options
   )

   init {
      "asb" {
         Regex("a.+b", IGNORE_CASE) shouldBe composedRegexMatcher(Regex("a.*b", DOT_MATCHES_ALL))
      }
```

Then it becomes

```
expected:<"a.*b"> but was:<"a.+b">
expected:<[DOT_MATCHES_ALL]> but was:<[IGNORE_CASE]>
```

However,
1) It is tough to write
2) It does not provide clues on what was compared and why
3) It behaves weirdly when one of the matcher succeeds
4) It is prone to errors like `ClassCastException` exception above. I believe, it is unfixable thanks to `Matcher.compose(vararg pairs: Pair<Matcher<*>, ...` parameter type.

```kotlin
   fun composedRegexMatcher(regex: Regex) = Matcher.compose(
      equalityMatcher(regex.pattern) to Regex::pattern,
      equalityMatcher(regex.options) to Regex::options
   )

   init {
      "asb" {
         Regex("a.+b", IGNORE_CASE) shouldBe composedRegexMatcher(Regex("a.+b", DOT_MATCHES_ALL))
      }
```

```
expected:<"a.+b"> but was:<"a.+b">
expected:<[DOT_MATCHES_ALL]> but was:<[IGNORE_CASE]>
Expected :[DOT_MATCHES_ALL]
Actual   :[IGNORE_CASE]
```

What is `expected:<"a.+b"> but was:<"a.+b">` after all? Of course it should be fixable in `Matcher.compose`. Currently it emits `failureMessage` for all the matchers which yields surprising output. However, fixing `Matcher.compose` won't make it useful in general.

**Comment by pientaa** [comment]
@vlsi yeah, I get it, so I proposed more flexible way of composing matchers here #3406. Firstly I planned just to fix the documentation, but later on it turned out that I can propose some non-breaking changes and I also proposed there some improvement for future releases (because it will break compose matcher API)

**Comment by vlsi** [comment]
>I proposed more flexible way of composing matchers here https://github.com/kotest/kotest/pull/3406

Frankly speaking, I do not see why you propose "more flexible way of composing matchers" in "Rename Data Class Matchers to Composed Matchers" (documentation fix) issue rather than in "idea: composite matchers, MatcherResultBuilder" (this issue).

However, I see you are stuck with `vararg` approach to composition, which does not really solve the limits I listed above:
1. It is tough to write, and the syntax is different from the rest part of kotest-assertions
2. It does not provide clues on what was compared and why. I can't add a clue for one of the matchers
3. It does not provide a way to add `if` or `for` over one of the matchers
4. `vararg matchers: Matcher<T>` does not help with matching unrelated values. See "multiple database connections" in the very first comment on this issue.

**Comment by pientaa** [comment]
> Frankly speaking, I do not see why you propose "more flexible way of composing matchers" in "Rename Data Class Matchers to Composed Matchers" (documentation fix) issue rather than in "idea: composite matchers, MatcherResultBuilder" (this issue).

you're right, I should have done it in current issue, sorry

> However, I see you are stuck with vararg approach to composition, which does not really solve the limits I listed above:

Yeah, I'll try to propose something else in current issue. Just give me some time to play a little with it in code.

But when it comes to 

> Another case for composite matchers is Matcher<T>.or, Matcher<T>.and.

What do you think about an easy fix like that?

```kotlin
infix fun <T> Matcher<T>.and(other: Matcher<T>): Matcher<T> = Matcher {
   val first = this.test(it)
   val second = other.test(it)
   MatcherResult(
      first.passed() && second.passed(),
      { "(${first.failureMessage()} and ${second.failureMessage()})" },
      { "(${first.negatedFailureMessage()} or ${second.negatedFailureMessage()})" },
   )
}

infix fun <T> Matcher<T>.or(other: Matcher<T>): Matcher<T> = Matcher {
   val first = this.test(it)
   val second = other.test(it)
   MatcherResult(
      first.passed() || second.passed(),
      { "(${first.failureMessage()} or ${second.failureMessage()})" },
      { "(${first.negatedFailureMessage()} and ${second.negatedFailureMessage()})" },
   )
}
```
This way you get following response in the example you gave: 

```kotlin
12 shouldBe (between(0, 2) or between(0, 3))
```
```
(12 should be between (0, 2) inclusive or 12 should be between (0, 3) inclusive)
java.lang.AssertionError: (12 should be between (0, 2) inclusive or 12 should be between (0, 3) inclusive)
```

**Comment by vlsi** [comment]
> What do you think about an easy fix like that?

Of course it is much better output than the current implementation of and/or, however, I am not interested in and/or

**Comment by vlsi** [comment]
> first.passed() && second.passed()

However, please note that this change significantly alters the behaviour. You basically kill short-circuit feature(previously the second matcher was not executed if the first failed), so users' tests might start crashing.

I think I would stop commenting here as it takes time, and there's impedance mismatch with maintainers.

**Comment by pientaa** [comment]
@vlsi I thought about your request for a while and it looks like we don't need to add builder to achieve what you want to achieve
	
I was able to write this	
```kotlin
fun isEmpty(connections: List<Connection>) =
   object : Matcher<Table> {
      override fun test(value: Table): MatcherResult =
         composeAll {
            connections.mapNotNull { connection ->
               withClue({ "Database $connection" }) {
                  connection.createStatement().let { st ->
                     val rs = try {
                        st.executeQuery("...")
                     } catch (e: Exception) {
                        failure("Failed to query table ${value.name}", e)
                        // try next connection
                        return@let null
                     }
                     rs.next()
                     val count = rs.getInt(1)
                     MatcherResult(
                        count == 0,
                        { "Table ${value.name} is not empty, it contains $count rows" },
                        { "Table ${value.name} is empty" }
                     )
                  }
               }
            }
         }
   }
```

and I wrote only that function to make it possible
	
```kotlin
fun composeAll(func: () -> List<MatcherResult>) =
   func().let { results ->
      MatcherResult(
         results.all { it.passed() },
         { results.joinToString(" and ") { it.failureMessage() } },
         { results.joinToString(" or ") { it.negatedFailureMessage() } }
      )
   }
```
   	
I tried to follow your proposition with `MatcherResultBuilder` but (unless I did something wrong) it was impossible to make clues and failures work when wrapped in `MatcherResult`. What do you think about it? If it satisfies you, I can also add `composeAny` and this will be a simple non-breaking change to add these two functions

**Comment by vlsi** [comment]
>I thought about your request for a while and it looks like we don't need to add builder to achieve what you want to achieve
> I was able to write this

@pientaa , 

a) `withClue` does not work there. In other words, `MatcherResult(...)` does not pick the clues
b) `failure("Failed to query table ${value.name}", e)` is ignored as well
c) `count == 0` duplicates the existing matchers, and it would be nice to be able to use already existing 

and so on.

**Comment by pientaa** [comment]
@vlsi 

> a) `withClue` does not work there. In other words, `MatcherResult(...)` does not pick the clues

yup, it works only for failures in its scope. Look here:

```kotlin
/**
 * Add [clue] as additional info to the assertion error message in case an assertion fails.
 * Can be nested, the error message will contain all available clues.
 *
 * @param thunk the code with assertions to be executed
 * @return the return value of the supplied [thunk]
 */
inline fun <R> withClue(clue: Any?, thunk: () -> R): R {
   return clue.asClue { thunk() }
}
```

So if you'd like to run `withClue` for `MatcherResult`, you should do it this way:

```kotlin
connections.forAll { connection ->
   withClue("Database $connection" ) {
      tableUnderTest shouldBe emptyTable(connection = connection)
}
```
> b) `failure("Failed to query table ${value.name}", e)` is ignored as well

Failure works, it throws an assertion error. But it's not aggregated in `MatcherResult` message. If a) is OK to you, it can be rewritten to `MatcherResult` as well

> c) count == 0 duplicates the existing matchers, and it would be nice to be able to use already existing

you can use the existing matcher, sure, why not?
