### ISSUE TITLE
kotest-extensions-wiremock 1.0.3 not compatible with kotest 5.5.5

### ISSUE THREAD

**Issue by fgaule** [kotest/kotest#3457]
The example listed in the official documentation for kotest-extensions-wiremock does not work if you are using kotest 5.5.5
Probably because kotest-extensions-wiremock latest version supports kotests <= 4.3 

**Which version of Kotest are you using**
kotest: 5.5.5
kotest-extensions-wiremock: 1.0.3

dependency:tree | grep kotest
```shell
% mvn dependency:tree | grep kotest 
[INFO] +- io.kotest.extensions:kotest-extensions-wiremock:jar:1.0.3:test
[INFO] |  \- io.kotest:kotest-framework-api-jvm:jar:4.4.3:test
[INFO] +- io.kotest:kotest-runner-junit5-jvm:jar:5.5.5:test
[INFO] |  +- io.kotest:kotest-common-jvm:jar:5.5.5:test
[INFO] |  +- io.kotest:kotest-framework-engine-jvm:jar:5.5.5:test
[INFO] |  +- io.kotest:kotest-framework-discovery-jvm:jar:5.5.5:test
[INFO] |  +- io.kotest:kotest-extensions-jvm:jar:5.5.5:test
[INFO] |  +- io.kotest:kotest-framework-concurrency-jvm:jar:5.5.5:test
[INFO] +- io.kotest:kotest-assertions-core-jvm:jar:5.5.5:test
[INFO] |  +- io.kotest:kotest-assertions-shared-jvm:jar:5.5.5:test
[INFO] |  \- io.kotest:kotest-assertions-api-jvm:jar:5.5.5:test
[INFO] +- io.kotest:kotest-property-jvm:jar:5.5.5:test
```

Output after running the example listed in Kotest documentation ([link](https://kotest.io/docs/extensions/wiremock.html))

```java
Testing started at 14:44 ...
java.lang.NoClassDefFoundError: io/kotest/core/names/DisplayNameFormatter
io/kotest/core/names/DisplayNameFormatter
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.kotest.engine.listener.TeamCityTestEngineListener.<init>(TeamCityTestEngineListener.kt:31)
	at io.kotest.engine.listener.TeamCityTestEngineListener.<init>(TeamCityTestEngineListener.kt:24)
	at io.kotest.engine.launcher.ConsoleKt.createConsoleListener(console.kt:18)
	at io.kotest.engine.launcher.MainKt.main(main.kt:30)
Caused by: java.lang.ClassNotFoundException: io.kotest.core.names.DisplayNameFormatter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 13 more
Exception in thread "main" java.lang.NoClassDefFoundError: io/kotest/core/names/DisplayNameFormatter
	at io.kotest.engine.listener.TeamCityTestEngineListener.<init>(TeamCityTestEngineListener.kt:31)
	at io.kotest.engine.listener.TeamCityTestEngineListener.<init>(TeamCityTestEngineListener.kt:24)
	at io.kotest.engine.launcher.ConsoleKt.defaultConsoleListener(console.kt:45)
	at io.kotest.engine.launcher.ConsoleKt.createConsoleListener(console.kt:27)
	at io.kotest.engine.launcher.MainKt.main(main.kt:30)`
```

**Comment by jorgejcabrera** [comment]
Hi! Does anyone have a clue? I found the same issue.

**Comment by Kantis** [comment]
I published v2 of the extension now, should fix this. Please confirm.

I suspect this only affected Maven users?
