### ISSUE TITLE
idea: Allow test factory inclusion in TestContainers

### ISSUE THREAD

**Issue by RaphaelTarita** [kotest/kotest#3482]
I like using test containers to organize my test cases into subgroups (I'm personally using `FunSpec` and `context()` but this idea would apply to all testing styles which support test containers). Especially when a certain logical group of test cases is large, it's nice to see the results grouped together in reports or in the IntelliJ test pane.

I also like using `include()` to utilize test factories which generate multiple test cases for different sets of data. Usually using `include()` leads to a lot of test cases, and it would be great if I could group them in a `context()` (or similar test containers in other styles).

For example, let's say I'm testing some functionality related to serialization, and I use a test factory to generate test cases for different serializable classes:
```kotlin
fun <T> serializationTests(obj: T, strategy: KSerializer<T>) = funSpec {
    test("should serialize correctly") {
        // ...
    }
    
    test("should deserialize correctly") {
        // ...
    }
}
```
Ideally, I would then include those tests in a test container:
```kotlin
class UtilTests : FunSpec({
    context("some tests") {
        // ...
    }
    context("serialization tests") {
        include(serializationTests(Foo(), Foo.serializer())
        include(serializationTests(Bar(), Bar.serializer())
        include(serializationTests(Baz(), Baz.serializer())
    }
    context("some other tests") {
        // ...
    }
})
```
However, doing this will yield the following error:
```stacktrace
Cannot add a root test after the spec has been instantiated: <your test name>
io.kotest.core.spec.InvalidDslException: Cannot add a root test after the spec has been instantiated: <your test name>
	at app//io.kotest.core.spec.DslDrivenSpec.add(DslDrivenSpec.kt:45)
	at app//io.kotest.core.spec.DslDrivenSpec.include(DslDrivenSpec.kt:55)
        at <application-specific stacktrace>
```
Every test factory has to be included at the root level of the surrounding spec.

Proposal:
Allow for test factories to be `include()`d in TestContainers like `context()` (`FunSpec`)

**Comment by RaphaelTarita** [comment]
Are there any updates on this?

**Comment by sksamuel** [comment]
So the basic idea is to allow test factories to be added inside other nested tests ?

**Comment by RaphaelTarita** [comment]
or, atleast in test containers like `context()`, but yes, exactly.

**Comment by Ejden** [comment]
Any updates? Currently it's a pain having to run all of the tests in a test class just to run tests from single factory :c Maybe it would be also worth to allow running include sections seperately?

**Comment by PreAgile** [comment]
I'm thinking of taking this on.                                                          
                                                                                            
  The issue is that `DslDrivenSpec.include()` always delegates to `add(RootTest)`,  which is blocked by the `sealed` flag at execution time. Nested `test()` calls work because they go through `ContainerScope.registerTestCase()` — and since             
  `ContainerScope` has no `include()`, Kotlin resolves to the outer scope instead.

  The fix would be a suspend extension on `ContainerScope` that converts `RootTest` → `NestedTest` and calls `registerTest()` directly:
                                                                                            
  ```kotlin
  suspend fun ContainerScope.include(factory: TestFactory) {                                
     factory.tests.forEach { rootTest ->                                                  
        registerTest(                                                                       
           name = rootTest.name,                                                           
           xmethod = rootTest.xmethod,
           config = rootTest.config,                                                        
           type = rootTest.type,
        ) { rootTest.test(this) }                                                           
     }                                                                                    
     // factory extensions/callbacks would need separate handling                           
  }                                                                                        
```
  This leaves root-level include() untouched (no breaking change). One open question: RootTest carries a factoryId that NestedTest doesn't have — not sure if that matters for filtering or reporting in your setup.                        
                                                                                          
  Does this direction work for you?
