### ISSUE TITLE
java.lang.NoSuchMethodError: 'io.kotest.core.descriptors.TestPath io.kotest.core.descriptors.Descriptor$DefaultImpls.path$default(io.kotest.core.descriptors.Descriptor, boolean, int, java.lang.Object)'

### ISSUE THREAD

**Issue by v-porytskyi** [kotest/kotest#3485]
I trying to configure Kotest with the Allure test report.

My  ```build.gradle.kts```:

```Gradle
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.6.20"
    id("io.qameta.allure") version "2.11.2"

    application
}

group = "org.cloud-solutions-llc"
version = "1.0-SNAPSHOT"

val ktorVersion = "2.0.1"
val koTestVersion = "5.5.5"
val retrofitVersion = "2.9.0"
val retrofitGsonVersion = "2.9.0"
val dotEnvVersion = "6.4.0"
val allureVersion = "1.2.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.slf4j:slf4j-simple:2.0.5")
    implementation("io.kotest.extensions:kotest-extensions-allure:$allureVersion")
    implementation("io.kotest:kotest-runner-junit5-jvm:$koTestVersion")
    implementation("io.kotest:kotest-framework-datatest:$koTestVersion")
    implementation("com.squareup.retrofit2:retrofit:$retrofitVersion")
    implementation("com.squareup.retrofit2:converter-gson:$retrofitGsonVersion")
    implementation("io.github.cdimascio:dotenv-kotlin:$dotEnvVersion")
}

tasks.test {
    useJUnitPlatform()
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}

application {
    mainClass.set("MainKt")
}

allure {
    adapter.autoconfigure.set(false)
}
```

My ```KotestProjectConfig```:
```Kotlin
import io.kotest.core.config.AbstractProjectConfig
import io.kotest.core.extensions.Extension
import io.kotest.extensions.allure.AllureTestReporter

object KotestProjectConfig : AbstractProjectConfig() {
    override val parallelism = 4

    override fun extensions(): List<Extension> {
        val list = mutableListOf<Extension>()

        super.extensions().forEachIndexed { index, it ->
            list.add(index, it)
        }

        list.add(AllureTestReporter())

        return list
    }
}
```

Test example:
```kotlin
package api.features.localizations.languages

import utils.Random
import client.Client
import retrofit2.await
import client.http.request.JsonRequest
import client.services.localizations.language.entity.InternalLanguage
import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.FunSpec
import client.services.localizations.language.request.CreateLanguage
import client.services.localizations.language.request.UpdateLanguage
import enums.Visibility
import io.kotest.core.test.TestCase
import io.kotest.core.test.TestResult
import io.kotest.matchers.shouldNotBe
import retrofit2.awaitResponse
import java.util.*

class UpdateEntitySpec : FunSpec() {
    private val client = Client().localizations().languages().internal()
    private var language = InternalLanguage()

    override suspend fun beforeEach(testCase: TestCase) {
        super.beforeEach(testCase)

        language = client.create(
            JsonRequest(
                CreateLanguage(
                    Random().string(6),
                    Random().string(24)
                )
            )
        ).await().data

        language.id shouldNotBe 0
    }

    override suspend fun afterEach(testCase: TestCase, result: TestResult) {
        super.afterEach(testCase, result)

        client.delete(language.id).awaitResponse().code() shouldBe 204
    }

    init {
        test("Full update entity") {
            val model = UpdateLanguage(
                Random().string(6),
                Random().string(6),
                Visibility.Hidden.toString()
            )

            val response = client.update(language.id, JsonRequest(model)).await()

            language.id shouldBe response.data.id
            response.data.code shouldBe model.code
            response.data.name shouldBe model.name
        }

        test("Update code only") {
            val model = UpdateLanguage(code = Random().string(6))
            val response = client.update(language.id, JsonRequest(model)).await()

            language.id shouldBe response.data.id
            response.data.code shouldBe model.code
        }

        test("Update name only") {
            val model = UpdateLanguage(name = Random().string(6))
            val response = client.update(language.id, JsonRequest(model)).await()

            language.id shouldBe response.data.id
            response.data.name shouldBe model.name?.replaceFirstChar {
                if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString()
            }
        }
    }
}

```

When a run a test, I get the error:
```
java.lang.NoSuchMethodError: 'io.kotest.core.descriptors.TestPath io.kotest.core.descriptors.Descriptor$DefaultImpls.path$default(io.kotest.core.descriptors.Descriptor, boolean, int, java.lang.Object)'
io.kotest.engine.extensions.ExtensionException$BeforeTestException: java.lang.NoSuchMethodError: 'io.kotest.core.descriptors.TestPath io.kotest.core.descriptors.Descriptor$DefaultImpls.path$default(io.kotest.core.descriptors.Descriptor, boolean, int, java.lang.Object)'
	at app//io.kotest.engine.test.TestExtensions$beforeTestBeforeAnyBeforeContainer$errors$4$2.invoke(TestExtensions.kt:89)
	at app//io.kotest.engine.test.TestExtensions$beforeTestBeforeAnyBeforeContainer$errors$4$2.invoke(TestExtensions.kt:89)
	at app//io.kotest.common.ResultsKt.mapError(results.kt:8)
	at app//io.kotest.engine.test.TestExtensions.beforeTestBeforeAnyBeforeContainer-gIAlu-s(TestExtensions.kt:89)
	at app//io.kotest.engine.test.TestExtensions$beforeTestBeforeAnyBeforeContainer$1.invokeSuspend(TestExtensions.kt)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoSuchMethodError: 'io.kotest.core.descriptors.TestPath io.kotest.core.descriptors.Descriptor$DefaultImpls.path$default(io.kotest.core.descriptors.Descriptor, boolean, int, java.lang.Object)'
	at io.kotest.extensions.allure.AllureWriter.startTestCase(AllureWriter.kt:77)
	at io.kotest.extensions.allure.AllureTestReporter.beforeTest(AllureTestReporter.kt:16)
	at io.kotest.engine.test.TestExtensions.beforeTestBeforeAnyBeforeContainer-gIAlu-s(TestExtensions.kt:88)
	... 6 more

```

**I get this error on Linux Debian 11. On Mac OS this configuration works fine.**

**Comment by Kantis** [comment]
The error indicates version incompatibility between the kotest version used by the allure extension, and the kotest version you're using from your project. Try downgrading to Kotest 5.3.

It shouldn't matter which OS you use. Could you provide the output of `./gradlew dependencies` from both systems?

**Comment by v-porytskyi** [comment]
I checked with Kotest version 5.3.0 it works correctly. 
Thank you very much.
