### ISSUE TITLE
Incompatible with kotlin 1.9.x

### ISSUE THREAD

**Issue by serpro69** [kotest/kotest#3666]
Kotest: 5.6.2
Kotlin: 1.9.10

```
io.github.serpro69.semverkt.gradle.plugin.SemverKtPluginFT STANDARD_ERROR
    java.lang.IncompatibleClassChangeError: Found interface kotlin.time.TimeMark, but class was expected
        at io.kotest.engine.spec.interceptor.SpecFinishedInterceptor.intercept-0E7RQCE(SpecFinishedInterceptor.kt:37)
        at io.kotest.engine.spec.interceptor.SpecFinishedInterceptor$intercept$1.invokeSuspend(SpecFinishedInterceptor.kt)
        (Coroutine boundary)
        at io.kotest.engine.ConcurrentTestSuiteScheduler.schedule(ConcurrentTestSuiteScheduler.kt:43)
```

Looks similar to https://github.com/kotest/kotest/issues/2960

**Comment by serpro69** [comment]
Sorry, my bad, a sub-module had an older version declared :/ 5.6.2 seems to work fine with latest kotlin version
