### ISSUE TITLE
beforeSpec sometimes gets called multiple times on the same Spec instance

### ISSUE THREAD

**Issue by xenomachina** [kotest/kotest#3684]
After trying to upgrade to either 5.7.1 or 5.7.2 we're seeing `beforeSpec` getting called twice on a single spec instance, but only sometimes. We weren't seeing this behavior with 5.6.2 or earlier.

How many times `beforeSpec` gets called in 5.7.x seems to be nondeterministic: on some machines it usually only gets called once, on others it'll more often be called twice. Other things can affect this too, like if all specs are being run, or only a subset, or even if the repo is clean vs has previously run the tests.

Given the nondeterminism, it feels like a race condition: like something is not realizing that another coroutine already ran (or started to run) `beforeSpec`, and so it runs it again.

This is causing a number of our tests to fail, as we often use `beforeSpec` to set up resources for tests, and our assumption has always been that it is only run once per spec instance.

**Comment by sksamuel** [comment]
Do you have a sample that reproduces this?
Which isolation mode are you using?
Running from gradle?

**Comment by xenomachina** [comment]
> Do you have a sample that reproduces this?

I made up a mostly self-contained sample that sometimes reproduces the problem. Please see below.

As mentioned above, the problem doesn't reproduce reliably in the test suites where we've seen it fail, and the same is true for this test. I can't get it to reproduce **at all** on either of my computers, while a co-worker can only reproduce it some of the time, and only when running our full test suite, not when running only one spec. It does seem to happen reliably in our GitLab CI environment, however.

Based on the behavior we're seeing and my reading of [`BeforeSpecListenerInterceptor`](https://github.com/kotest/kotest/pull/3649/files#diff-8d49101f680a16508ffae5b35bdca8e586196ca6e3722a23e6a6b2c9df9b59c3R23), I think what's happening is that kotest checks `context.state` to see whether `beforeSpec` has already been called (for the test's spec), but only marks it as having been run after `beforeSpec` returns. Because the read+write of that state isn't atomic we can sometimes end up with `beforeSpec` being called again before the state gets updated.

I still don't understand why it's so hard to get this to reproduce, though.

> Which isolation mode are you using?

We've seen this with `SingleInstance` isolation mode. Setting `parallelism` greater than 1 may also be a factor. (We set it to `Runtime.getRuntime().availableProcessors() + 1` in our `ProjectConfig`.)

> Running from gradle?

Yes, we are running our tests from gradle.

---

### Sample code:

``` kotlin
class BeforeSpecRunsExactlyOnce : FunSpec() {
    companion object {
        private val beforeSpecRan = AtomicBoolean()
        private val counter = AtomicInteger(0)
    }

    override fun isolationMode(): IsolationMode = IsolationMode.SingleInstance

    override suspend fun beforeSpec(spec: Spec) {
        yield()
        beforeSpecRan.getAndSet(true).shouldBe(false) // this is the assertion that fails
        yield()
        super.beforeSpec(spec)
        yield()
        coroutineScope {
            async { delay(10000) }.await()
        }
        yield()
        counter.incrementAndGet()
        yield()
    }

    override fun afterSpec(f: AfterSpec) {
        super.afterSpec(f)
        beforeSpecRan.get() shouldBe true
        counter.get() shouldBe 1
    }

    init {
        test("test  0") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test  1") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test  2") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test  3") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test  4") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test  5") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test  6") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test  7") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test  8") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test  9") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 10") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 11") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 12") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 13") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 14") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 15") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 16") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 17") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 18") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 19") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 20") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 21") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 22") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 23") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 24") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 25") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 26") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 27") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 28") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 29") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 30") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 31") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 32") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 33") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 34") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 35") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 36") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 37") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 38") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 39") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 40") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 41") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 42") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 43") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 44") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 45") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 46") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 47") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 48") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 49") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 50") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 51") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 52") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 53") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 54") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 55") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 56") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 57") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 58") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 59") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 60") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 61") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 62") { beforeSpecRan.get() shouldBe true; delay(10) }
        test("test 63") { beforeSpecRan.get() shouldBe true; delay(10) }
    }
}
```
---

### Sample code's output:

```

io.kotest.engine.extensions.ExtensionException$BeforeSpecException: io.kotest.assertions.AssertionFailedError: expected:<false> but was:<true>
        at app//io.kotest.engine.spec.SpecExtensions$beforeSpec$errors$1$2.invoke(SpecExtensions.kt:52)
        at app//io.kotest.engine.spec.SpecExtensions$beforeSpec$errors$1$2.invoke(SpecExtensions.kt:52)
        at app//io.kotest.common.ResultsKt.mapError(results.kt:17)
        at app//io.kotest.engine.spec.SpecExtensions.beforeSpec-gIAlu-s(SpecExtensions.kt:52)
        at app//io.kotest.engine.spec.SpecExtensions$beforeSpec$1.invokeSuspend(SpecExtensions.kt)
        at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
Caused by: io.kotest.assertions.AssertionFailedError: expected:<false> but was:<true>
        at app//com.example.BeforeSpecRunsExactlyOnce.beforeSpec(BeforeSpecRunsExactlyOnce.kt:28)
        at app//com.example.BeforeSpecRunsExactlyOnce$beforeSpec$1.invokeSuspend(BeforeSpecRunsExactlyOnce.kt)
        ... 5 more
```

**Comment by xenomachina** [comment]
FWIW: simplifying `beforeSpec` in the sample above to this still fails in our CI:

``` kotlin
    override suspend fun beforeSpec(spec: Spec) {
        beforeSpecRan.getAndSet(true).shouldBe(false)
        super.beforeSpec(spec)
        delay(10000)
        counter.incrementAndGet()
    }
```

(The reason for the weird original version was my failed attempts to get it to reproduce locally on my machines.)

**Comment by sksamuel** [comment]
This is enough to reproduce it every time.

```
class BeforeSpecRunsExactlyOnce : FunSpec() {
   companion object {
      private val beforeSpecRan = AtomicBoolean()
   }

   override fun concurrency(): Int = 10

   override suspend fun beforeSpec(spec: Spec) {
      if (beforeSpecRan.get()) error("boom")
      beforeSpecRan.set(true)
      delay(2)
   }

   init {
      test("test  0") { beforeSpecRan.get() shouldBe true; delay(10) }
      test("test  1") { beforeSpecRan.get() shouldBe true; delay(10) }
   }
}
```
