### ISSUE TITLE
java.lang.Object arrow.core.Either for getA(),getB() and getT()

### ISSUE THREAD

**Issue by ColoLP** [kotest/kotest#3693]
**Which version of Kotest are you using**
kotest: 4.3.2
arrow-core: 1.2.1

I've recently updated to newest version of kotest and arrow-core, and I've experienced this error while trying to run my tests and use methods like shouldBeRight, shouldBeLeft, shouldBe 

These are the error that I get

```
java.lang.NoSuchMethodError: 'java.lang.Object arrow.core.Either$Right.getB()'
or java.lang.NoSuchMethodError: 'java.lang.Object arrow.core.Either$Right.getA()'
or java.lang.NoSuchMethodError: 'java.lang.Object arrow.core.Either$Right.getT()'

```

As an example I only share one stack trace
```
java.lang.NoSuchMethodError: 'java.lang.Object arrow.core.Either$Right.getB()'
	at io.kotest.assertions.arrow.either.MatchersKt$beRight$1.test(matchers.kt:37)
	at io.kotest.assertions.arrow.either.MatchersKt$beRight$1.test(matchers.kt:30)
	at io.kotest.matchers.ShouldKt.should(should.kt:32)
	at io.kotest.assertions.arrow.either.MatchersKt.shouldBeRight(matchers.kt:28)
	at com.lastminute.refund.adapters.provider.voucher.WillyWonkaRestClientTest.create voucher happy path(WillyWonkaRestClientTest.kt:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
```

**Comment by sksamuel** [comment]
It looks to me like the version of arrow changed and those methods moved or were removed.
You're running old versions of kotest, can you upgrade to 5.7.2 ?

**Comment by ColoLP** [comment]
Hello! thanks for the answer. 
I've tried your solution and now I've compilation errors. Now, shouldBeSome shouldBeNone Method is not recognized for optional as you explained in your Website.

**Comment by sksamuel** [comment]
can you show some code with the dependencies you're using

**Comment by ColoLP** [comment]
This are my dependencies: 
![image](https://github.com/kotest/kotest/assets/14929784/c6d150f6-2d58-4d8a-a03e-48920200422f)

And this is my code: 
```
fun INTERMEDIARY() {
    val refundOrder = RefundOrderBuilder.aRefundOrder().withLegalObligation(INTERMEDIARY).build()
    val refundDocuments = RefundDocumentsBuilder.aRefundDocuments().build()
    val anyReason =
      IsNotDeletedDocumentValidator.REFUND_INVALID

    every { ruleIntermediary.check(refundDocuments) } returns Optional.of(anyReason)

    legalObligationFilter.apply(refundOrder, refundDocuments).asOption()
  }
```
When I tried to import the dependency method It's not showed. 

![image](https://github.com/kotest/kotest/assets/14929784/72bd62a4-ef5e-471a-8ce0-7dbf8ea7574e)

**Comment by ColoLP** [comment]
I could said, that this issue is "fixed" but, I've to do some things. For example, .shouldBeSome it never find it, so I use the shouldBe method with Some(MyImplementationObject) and It works. Same with .shouldBeNone(None)

**Comment by LeoColman** [comment]
@ColoLP 
If you think it's worth it, could you open a new issue detailing your 'new' situation? 
I'll close this one as fixed
