### ISSUE TITLE
Kotest uses virtual time for tests timeouts when Dispatchers.Main is overridden

### ISSUE THREAD

**Issue by osipxd** [kotest/kotest#3703]
**Version:** 5.7.2

If you have overridden `Dispatchers.Main` before a test, timeout uses virtual time and always fails with `TimeoutCancellationException`.

Kotest config:
```kotlin
class KotestConfig : AbstractProjectConfig() {
    override val coroutineTestScope: Boolean = true
    override val timeout = 5.seconds
}
```

Test code:
```kotlin
class MySpec : FeatureSpec({

    val dispatcher = StandardTestDispatcher()

    beforeTest { Dispatchers.setMain(dispatcher) }
    afterTest { Dispatchers.resetMain() }

    feature("...") {
        scenario("...") {
            // It will crash if Main dispatcher was not set before
            launch(Dispatchers.Main) {
                delay(100)
            }.join()

            dispatcher.scheduler shouldBe testCoroutineScheduler
        }
    }
})
```

**Actual result**
Test fails with timeout exception:
```stacktrace
Timed out after 5s of _virtual_ (kotlinx.coroutines.test) time. To use the real time, wrap 'withTimeout' in 'withContext(Dispatchers.Default.limitedParallelism(1))'
kotlinx.coroutines.TimeoutCancellationException: Timed out after 5s of _virtual_ (kotlinx.coroutines.test) time. To use the real time, wrap 'withTimeout' in 'withContext(Dispatchers.Default.limitedParallelism(1))'
	at app//kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:191)
	at app//kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:159)
	...
	at app//io.kotest.engine.test.interceptors.TestCoroutineInterceptor.intercept(TestCoroutineInterceptor.kt:34)
	at app//io.kotest.engine.test.TestInvocationInterceptor$runBeforeTestAfter$wrappedTest$1$1.invokeSuspend(TestInvocationInterceptor.kt:70)
	at app//io.kotest.engine.test.TestInvocationInterceptor$runBeforeTestAfter$wrappedTest$1$1.invoke(TestInvocationInterceptor.kt)
	at app//io.kotest.engine.test.TestInvocationInterceptor$runBeforeTestAfter$wrappedTest$1$1.invoke(TestInvocationInterceptor.kt)
	at app//io.kotest.engine.test.interceptors.InvocationTimeoutInterceptor$intercept$3.invokeSuspend(InvocationTimeoutInterceptor.kt:43)
	...
```

**Expected result**
Test runs without exception.

**Comment by osipxd** [comment]
Possible workaround is to use `invocationTimeout` instead of `timeout`. Difference I found between these options is that `invocationTimeout` applies timeout only to tests, not to test containers.
