### ISSUE TITLE
SpecInstantiation: Specs must have a public zero-arg constructor

### ISSUE THREAD

**Issue by nayanseth** [kotest/kotest#3833]
Getting the following error when using springmockk 4.0.2, kotest 5.8.0, 1.13.9 mockk, kotest spring extension 1.1.3

``` shell
io.blah.MyTest.null
[ERROR]   Run 1: MyTest » SpecInstantiation Could not create instance of class io.blah.MyTest. Specs must have a public zero-arg constructor.
```

### Sample Code

``` kotlin
class MyTest(
  @MockkBean
  private val testClass: TestClass
) : FunSpec() {
    override fun extensions() = listOf(SpringExtension)
    init {
        test("blah test") {}
    }
}
```

I also have kotest.properties file in my src/test/resources folder:

```
kotest.framework.classpath.scanning.config.disable=true
kotest.framework.classpath.scanning.autoscan.disable=true
```

### Stacktrace

```
at io.kotest.engine.spec.InstantiateSpecKt.javaReflectNewInstance(instantiateSpec.kt:54)
	at io.kotest.engine.spec.InstantiateSpecKt.createAndInitializeSpec(instantiateSpec.kt:30)
	at io.kotest.engine.spec.InstantiateSpecKt.instantiate(instantiateSpec.kt:11)
	at io.kotest.engine.spec.SpecRefKt.instance(SpecRef.kt:14)
	at io.kotest.engine.spec.SpecExecutor.createInstance-gIAlu-s(SpecExecutor.kt:63)
	at io.kotest.engine.spec.SpecExecutor.access$createInstance-gIAlu-s(SpecExecutor.kt:24)
	at io.kotest.engine.spec.SpecExecutor$execute$innerExecute$1.invokeSuspend(SpecExecutor.kt:40)
	at io.kotest.engine.spec.SpecExecutor$execute$innerExecute$1.invoke(SpecExecutor.kt)
	at io.kotest.engine.spec.SpecExecutor$execute$innerExecute$1.invoke(SpecExecutor.kt)
```

**Comment by nayanseth** [comment]
Figured it out. When we disable autoscan, kotest will need us to manually specify the extensions that we want to use. In this case, I had to add SpringAutowireConstructorExtension to the ProjectLevel config file

``` kotlin
import io.kotest.core.config.AbstractProjectConfig
import io.kotest.core.extensions.Extension
import io.kotest.extensions.spring.SpringAutowireConstructorExtension

class ProjectConfig : AbstractProjectConfig() {
    override fun extensions(): List<Extension> {
        return super.extensions() + listOf<Extension>(
            SpringAutowireConstructorExtension
        )
    }
}
```

It was mentioned in advanced extension doc: https://kotest.io/docs/framework/extensions/advanced-extensions.html (ConstructorExtension)
