### ISSUE TITLE
JVM Tests fail to run on JDK 21 when System Properties are propagated in Gradle

### ISSUE THREAD

**Issue by YSakhno** [kotest/kotest#3851]
When propagation of the System Properties is turned on as specified in [Kotest's documentation on tags](https://kotest.io/docs/framework/tags.html#gradle), tests fail to run under JDK 21 with the following exception (tests are invoked from the command line using `./gradlew test`):

```plain
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 1.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:64)
	at java.base@21.0.2/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base@21.0.2/java.lang.reflect.Method.invoke(Method.java:580)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.junit.platform.commons.JUnitException: TestEngine with ID 'kotest' failed to discover tests
	at app//org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
	at app//org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:134)
	at app//org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:108)
	at app//org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:80)
	at app//org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at app//org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:119)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:94)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:89)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	... 16 more
Caused by: io.kotest.engine.config.ConfigurationException: io.github.classgraph.ClassGraphException: Uncaught exception during scan
	at app//io.kotest.engine.config.ConfigManager$compile$2.invoke(ConfigManager.kt:29)
	at app//io.kotest.engine.config.ConfigManager$compile$2.invoke(ConfigManager.kt:29)
	at app//io.kotest.common.ResultsKt.mapError(results.kt:17)
	at app//io.kotest.engine.config.ConfigManager.compile-gIAlu-s(ConfigManager.kt:29)
	at app//io.kotest.engine.config.ConfigManager.initialize(ConfigManager.kt:19)
	at app//io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine.discover(KotestJunitPlatformTestEngine.kt:108)
	at app//io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine.discover(KotestJunitPlatformTestEngine.kt:39)
	at app//org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
	... 26 more
Caused by: io.github.classgraph.ClassGraphException: Uncaught exception during scan
	at app//io.github.classgraph.ClassGraph.scan(ClassGraph.java:1637)
	at app//io.github.classgraph.ClassGraph.scan(ClassGraph.java:1654)
	at app//io.github.classgraph.ClassGraph.scan(ClassGraph.java:1667)
	at app//io.kotest.engine.config.ApplyConfigFromAutoScanKt.applyConfigFromAutoScan(applyConfigFromAutoScan.kt:24)
	at app//io.kotest.engine.config.ConfigManager.compile-gIAlu-s(ConfigManager.kt:27)
	... 30 more
Caused by: java.lang.IllegalArgumentException: Method "list" could not be invoked: java.lang.reflect.InvocationTargetException
	at nonapi.io.github.classgraph.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:231)
	at io.github.classgraph.ModuleReaderProxy.list(ModuleReaderProxy.java:110)
	at io.github.classgraph.ClasspathElementModule.scanPaths(ClasspathElementModule.java:304)
	at io.github.classgraph.Scanner$4.processWorkUnit(Scanner.java:1097)
	at io.github.classgraph.Scanner$4.processWorkUnit(Scanner.java:1091)
	at nonapi.io.github.classgraph.concurrency.WorkQueue.runWorkLoop(WorkQueue.java:246)
	at nonapi.io.github.classgraph.concurrency.WorkQueue.runWorkQueue(WorkQueue.java:161)
	at io.github.classgraph.Scanner.processWorkUnits(Scanner.java:316)
	at io.github.classgraph.Scanner.openClasspathElementsThenScan(Scanner.java:1089)
	at io.github.classgraph.Scanner.call(Scanner.java:1148)
	at io.github.classgraph.Scanner.call(Scanner.java:82)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Running tests under JDK 17 or 11 does not have this problem (with all other settings being equal).

Commenting out the line that sets up property propagation in Gradle

```kts
//    systemProperties = System.getProperties().asIterable().associate { it.key.toString() to it.value }
```

allows tests to run normally, even under JDK 21.

**Which version of Kotest are you using** 5.8.0
**Gradle** 8.5
**JDK** 21 (21.0.1+12)
**JDK Vendor** Temurin (Adoptium)

**Comment by sksamuel** [comment]
I cannot duplicate this with gradle 8.5 or 8.6 using temurin 21.

My settings:

```
subprojects {
   apply(plugin = "org.jetbrains.kotlin.jvm")

   tasks {
      java {
         targetCompatibility = JavaVersion.VERSION_21
         sourceCompatibility = JavaVersion.VERSION_21
         withSourcesJar()
      }
   }

   // configure kotest to run
   tasks.test {
      useJUnitPlatform()
      testLogging {
         showExceptions = true
         showStandardStreams = true
         exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
      }
      systemProperties = System.getProperties().asIterable().associate { it.key.toString() to it.value }
   }

   // set all projects to the latest LTS of the JDK and stable kotlin version
   tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
      kotlinOptions.jvmTarget = "21"
      kotlinOptions.apiVersion = "1.9"
      kotlinOptions.languageVersion = "1.9"
   }
}
```

Can you make a standalone repo that fails ?

**Comment by YSakhno** [comment]
Sorry, I am not able to reproduce this myself anymore...

I guess you may close this issue for now. I'll be sure to reopen / provide more information if I happen to run into this problem again.
