### ISSUE TITLE
Kotest doesn't work with GraalVM 's tracing agent

### ISSUE THREAD

**Issue by helpermethod** [kotest/kotest#3852]
Not sure if this is a bug or more of a feature request, but here goes:

Due to its use of `Classgraph.scan()`, Kotest can't be used in conjunction with GraalVM's tracing agent.

A reproducer can be found [here](https://github.com/helpermethod/kotest-graalvm-reproducer).

I **think** this could be mitigated if `Classgraph.scan()` is initialized at build-time instead of run-time. I see if I can submit a PR.

**Comment by sksamuel** [comment]
You can disable classgraph scanning by setting the system property or env var:
kotest.framework.classpath.scanning.autoscan.disable=true

**Comment by helpermethod** [comment]
> You can disable classgraph scanning by setting the system property or env var: kotest.framework.classpath.scanning.autoscan.disable=true

Thanks for the suggestion! I've forked kotest and tried to perform the classpath scanning at build-time, but I was unsure if I would cover most cases.

**Comment by karolgurecki** [comment]
Seems like disabling classpath scanning do not resolve the issue.

Example code which I did you can find in [this](https://github.com/karolgurecki/kotest-graalvm-test) repository.

GraalVM stacktrace:

```
The culprit object has been instantiated with the following trace:
        at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltInClassDescriptorFactory.<init>(JvmBuiltInClassDescriptorFactory.kt:19)
        at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltInsPackageFragmentProvider.<init>(JvmBuiltInsPackageFragmentProvider.kt:48)
        at kotlin.reflect.jvm.internal.impl.load.kotlin.DeserializationComponentsForJava$Companion.createModuleData(DeserializationComponentsForJava.kt:131)
        at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.RuntimeModuleData$Companion.create(RuntimeModuleData.kt:32)
        at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(moduleByClassLoader.kt:58)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:38)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:37)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:70)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(KDeclarationContainerImpl.kt:37)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:55)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:53)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:70)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt:53)
        at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:193)
        at kotlin.reflect.jvm.internal.KClassImpl.getVisibility(KClassImpl.kt:273)
        at io.kotest.framework.discovery.DiscoveryFilter$ClassModifierDiscoveryFilter.test(DiscoveryFilter.kt:35)
        at io.kotest.framework.discovery.Discovery$filterFn$1.invoke(Discovery.kt:61)
        at io.kotest.framework.discovery.Discovery$filterFn$1.invoke(Discovery.kt:60)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:813)
        at io.kotest.framework.discovery.Discovery.doDiscovery-IoAF18A(Discovery.kt:109)
------------------------------------------------------------------------------------------------------------------------        at io.kotest.framework.discovery.Discovery.discover(Discovery.kt:73)

        at io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine.discover(KotestJunitPlatformTestEngine.kt:118)
        at io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine.discover(KotestJunitPlatformTestEngine.kt:35)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:132)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:107)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:78)
        at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:99)
        at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:77)
        at org.junit.platform.launcher.core.DelegatingLauncher.discover(DelegatingLauncher.java:42)
        at org.junit.platform.launcher.core.SessionPerRequestLauncher.discover(SessionPerRequestLauncher.java:56)
        at org.graalvm.junit.platform.JUnitPlatformFeature.discoverTestsAndRegisterTestClassesForReflection(JUnitPlatformFeature.java:135)
        at org.graalvm.junit.platform.JUnitPlatformFeature.beforeAnalysis(JUnitPlatformFeature.java:94)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:773)
        at com.oracle.svm.hosted.NativeImageGenerator$$Lambda/0x0000000801688220.accept(Unknown Source)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:90)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:773)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:592)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:539)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:721)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
com.oracle.svm.hosted.classinitialization.ClassInitializationFeature$$Lambda/0x0000000801784ae8@1cc978a5
The following detailed trace displays from which field in the code the object was reached.
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.checkImageHeapInstance(ClassInitializationFeature.java:186)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:616)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:307)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readArrayElement(AnalysisConstantReflectionProvider.java:158)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.createImageHeapObjectArray(ImageHeapScanner.java:267)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.createImageHeapObject(ImageHeapScanner.java:251)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$getOrCreateImageHeapConstant$2(ImageHeapScanner.java:205)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        ... 21 more
```

**Comment by sksamuel** [comment]
This now works in the 6.0 milestone builds as classgraph is no longer a dependency.
