### ISSUE TITLE
withData ignores assertSoftly configuration

### ISSUE THREAD

**Issue by Fleshgrinder** [kotest/kotest#3884]
I'm using the latest version of Kotest. It doesn't matter where I configure that I want to use soft assertions by default. I'm doing it in the test case in the minimal reproducer, but the same effect applies if it's configured globally via a config class or the properties.

```kotlin
package com.fleshgrinder.kotest

import io.kotest.core.spec.style.StringSpec
import io.kotest.datatest.withData
import io.kotest.matchers.shouldBe

class WithDataSoftly : StringSpec({
    assertSoftly = true

    withData(Pair("a", "b"), Pair("c", "d")) {
        it.first shouldBe "x"
        it.second shouldBe "y"
    }
})
```

```
Expected :"x"
Actual   :"a"
<Click to see difference>

[…]

Expected :"x"
Actual   :"c"
<Click to see difference>
```

Wrapping the assertions myself in `assertSoftly` fixes the issue.

```kotlin
package com.fleshgrinder.kotest

import io.kotest.assertions.assertSoftly
import io.kotest.core.spec.style.StringSpec
import io.kotest.datatest.withData
import io.kotest.matchers.shouldBe

class WithDataSoftly : StringSpec({
    withData(Pair("a", "b"), Pair("c", "d")) {
        assertSoftly {
            it.first shouldBe "x"
            it.second shouldBe "y"
        }
    }
})
```

```
io.kotest.assertions.MultiAssertionError: The following 2 assertions failed:
1) expected:<"x"> but was:<"a">
   at com.fleshgrinder.kotest.WithDataSoftly$1$1.invokeSuspend(WithDataSoftly.kt:11)
2) expected:<"y"> but was:<"b">
   at com.fleshgrinder.kotest.WithDataSoftly$1$1.invokeSuspend(WithDataSoftly.kt:12)

[…]

io.kotest.assertions.MultiAssertionError: The following 2 assertions failed:
1) expected:<"x"> but was:<"c">
   at com.fleshgrinder.kotest.WithDataSoftly$1$1.invokeSuspend(WithDataSoftly.kt:11)
2) expected:<"y"> but was:<"d">
   at com.fleshgrinder.kotest.WithDataSoftly$1$1.invokeSuspend(WithDataSoftly.kt:12)
```

It does however break the `<Click to see difference>` but that's a different story. 😉

**Comment by sksamuel** [comment]
This is because assert softly only works for TestType.Test by default.
I will investigate if there's a reason for that.
