### ISSUE TITLE
Single test run fails with`java.lang.NoClassDefFoundError`, but all test for the class are passing

### ISSUE THREAD

**Issue by igorwojda** [kotest/kotest#3914]
**Which version of Kotest are you using**
- Android Studio Iguana | 2023.2.1 (roken in older versions as well)
- kotest `5.8.0`
- Intellij Plugin `Intellij Plugin-IC-2023.2`

All tests in class works fine, single test fails
![image](https://github.com/kotest/kotest/assets/530122/871622d7-3a26-494a-82d5-59eb443b6be1)

Error:
```
"/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java" -Didea.test.cyclic.buffer.size=1048576 -javaagent:/Applications/Android Studio.app/Contents/lib/idea_rt.jar=60142:/Applications/Android Studio.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Applications/Android Studio.app/Contents/lib/idea_rt.jar:/Users/igorwojda/Library/Android/sdk/platforms/android-34/android.jar:/Users/igorwojda/Library/Android/sdk/platforms/android-34/data/res:/Users/igorwojda/IdeaProjects/konsist/samples/starter-projects/konsist-starter-android-gradle-kotlin-kotest/konsistTest/build/tmp/kotlin-classes/debugUnitTest:/Users/igorwojda/IdeaProjects/konsist/samples/starter-projects/konsist-starter-android-gradle-kotlin-kotest/konsistTest/build/intermediates/compile_and_runtime_not_namespaced_r_class_jar/debugUnitTest/generateDebugUnitTestStubRFile/R.jar:/Users/igorwojda/.gradle/caches/transforms-4/0a94b3319a9a700a6c2c60b83314879a/transformed/appcompat-1.6.1/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/0a94b3319a9a700a6c2c60b83314879a/transformed/appcompat-1.6.1/res:/Users/igorwojda/.gradle/caches/transforms-4/0a94b3319a9a700a6c2c60b83314879a/transformed/appcompat-1.6.1/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/283f9906ca93bcd71a13c9aeeb0e3a49/transformed/activity-1.6.0/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/283f9906ca93bcd71a13c9aeeb0e3a49/transformed/activity-1.6.0/res:/Users/igorwojda/.gradle/caches/transforms-4/283f9906ca93bcd71a13c9aeeb0e3a49/transformed/activity-1.6.0/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/6632faa1f06b15c5187ba316d5f4f55a/transformed/core-1.9.0/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/6632faa1f06b15c5187ba316d5f4f55a/transformed/core-1.9.0/res:/Users/igorwojda/.gradle/caches/transforms-4/6632faa1f06b15c5187ba316d5f4f55a/transformed/core-1.9.0/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/ad8e3c7125f7abecc07e6b387e303c33/transformed/annotation-experimental-1.3.0/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/ad8e3c7125f7abecc07e6b387e303c33/transformed/annotation-experimental-1.3.0/res:/Users/igorwojda/.gradle/caches/transforms-4/ad8e3c7125f7abecc07e6b387e303c33/transformed/annotation-experimental-1.3.0/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/d13da1a41303a1ab89de176bf2ae60a5/transformed/lifecycle-runtime-2.5.1/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/d13da1a41303a1ab89de176bf2ae60a5/transformed/lifecycle-runtime-2.5.1/res:/Users/igorwojda/.gradle/caches/transforms-4/d13da1a41303a1ab89de176bf2ae60a5/transformed/lifecycle-runtime-2.5.1/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/6632a29a5ac064417759885be10bd8f3/transformed/versionedparcelable-1.1.1/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/6632a29a5ac064417759885be10bd8f3/transformed/versionedparcelable-1.1.1/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/1f807914f382a7a6041bff9602104bf0/transformed/lifecycle-viewmodel-2.5.1/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/1f807914f382a7a6041bff9602104bf0/transformed/lifecycle-viewmodel-2.5.1/res:/Users/igorwojda/.gradle/caches/transforms-4/1f807914f382a7a6041bff9602104bf0/transformed/lifecycle-viewmodel-2.5.1/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/53c305581a23ae646a1cbf30100c8291/transformed/lifecycle-viewmodel-savedstate-2.5.1/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/53c305581a23ae646a1cbf30100c8291/transformed/lifecycle-viewmodel-savedstate-2.5.1/res:/Users/igorwojda/.gradle/caches/transforms-4/53c305581a23ae646a1cbf30100c8291/transformed/lifecycle-viewmodel-savedstate-2.5.1/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/2e3a8a00484f56945875ec268f81ce36/transformed/core-ktx-1.9.0/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/2e3a8a00484f56945875ec268f81ce36/transformed/core-ktx-1.9.0/res:/Users/igorwojda/.gradle/caches/transforms-4/2e3a8a00484f56945875ec268f81ce36/transformed/core-ktx-1.9.0/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/f7b6aa2270c9801eb2090604e19c85f4/transformed/lifecycle-livedata-core-2.5.1/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/f7b6aa2270c9801eb2090604e19c85f4/transformed/lifecycle-livedata-core-2.5.1/res:/Users/igorwojda/.gradle/caches/transforms-4/f7b6aa2270c9801eb2090604e19c85f4/transformed/lifecycle-livedata-core-2.5.1/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/79fc39c9139225f815293b51cd739e4a/transformed/savedstate-1.2.0/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/79fc39c9139225f815293b51cd739e4a/transformed/savedstate-1.2.0/res:/Users/igorwojda/.gradle/caches/transforms-4/79fc39c9139225f815293b51cd739e4a/transformed/savedstate-1.2.0/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/4cb87cfe2ae7bc9775303ef0851017c8/transformed/appcompat-resources-1.6.1/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/4cb87cfe2ae7bc9775303ef0851017c8/transformed/appcompat-resources-1.6.1/res:/Users/igorwojda/.gradle/caches/transforms-4/4cb87cfe2ae7bc9775303ef0851017c8/transformed/appcompat-resources-1.6.1/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/7c3a0e9c59a5a086ed4e07dcaec0dce0/transformed/vectordrawable-1.1.0/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/7c3a0e9c59a5a086ed4e07dcaec0dce0/transformed/vectordrawable-1.1.0/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/3de4896a209fe18f7f7171a60cbe871e/transformed/vectordrawable-animated-1.1.0/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/3de4896a209fe18f7f7171a60cbe871e/transformed/vectordrawable-animated-1.1.0/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/4bc71305de840d65d3eb68584b5963a2/transformed/interpolator-1.0.0/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/4bc71305de840d65d3eb68584b5963a2/transformed/interpolator-1.0.0/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/f99fc91bf4daf50b03686c1e1924d1b4/transformed/cursoradapter-1.0.0/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/f99fc91bf4daf50b03686c1e1924d1b4/transformed/cursoradapter-1.0.0/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/d25b76e20a03f9e61313b47f93d0e90b/transformed/drawerlayout-1.0.0/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/d25b76e20a03f9e61313b47f93d0e90b/transformed/drawerlayout-1.0.0/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/464c52137868386f9ef4b7db818af1f1/transformed/customview-1.0.0/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/464c52137868386f9ef4b7db818af1f1/transformed/customview-1.0.0/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/70f85cd4d19b43ffc2081aca8c469cdc/transformed/fragment-1.3.6/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/70f85cd4d19b43ffc2081aca8c469cdc/transformed/fragment-1.3.6/res:/Users/igorwojda/.gradle/caches/transforms-4/70f85cd4d19b43ffc2081aca8c469cdc/transformed/fragment-1.3.6/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/2ca280b41445dc814dd75f6f81301ba6/transformed/viewpager-1.0.0/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/2ca280b41445dc814dd75f6f81301ba6/transformed/viewpager-1.0.0/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/29e482553ccba9ae04733a10fd841f78/transformed/loader-1.0.0/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/29e482553ccba9ae04733a10fd841f78/transformed/loader-1.0.0/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/c589dab4ed18100a1918fee72fc775f6/transformed/lifecycle-livedata-2.0.0/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/c589dab4ed18100a1918fee72fc775f6/transformed/lifecycle-livedata-2.0.0/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/transforms-4/ef5e08bd28bac752fddeeafe1ec3d510/transformed/core-runtime-2.1.0/jars/classes.jar:/Users/igorwojda/.gradle/caches/transforms-4/ef5e08bd28bac752fddeeafe1ec3d510/transformed/core-runtime-2.1.0/AndroidManifest.xml:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.23/dbaadea1f5e68f790d242a91a38355a83ec38747/kotlin-stdlib-1.9.23.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/androidx.annotation/annotation/1.3.0/21f49f5f9b85fc49de712539f79123119740595/annotation-1.3.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/androidx.arch.core/core-common/2.1.0/b3152fc64428c9354344bd89848ecddc09b6f07e/core-common-2.1.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/androidx.lifecycle/lifecycle-common/2.5.1/1fdb7349701e9cf2f0a69fc10642b6fef6bb3e12/lifecycle-common-2.5.1.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/androidx.collection/collection/1.1.0/1f27220b47669781457de0d600849a5de0e89909/collection-1.1.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-android/1.6.1/4e61fcdcc508cbaa37c4a284a50205d7c7767e37/kotlinx-coroutines-android-1.6.1.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm/1.6.1/97fd74ccf54a863d221956ffcd21835e168e2aaa/kotlinx-coroutines-core-jvm-1.6.1.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.8.0/ed04f49e186a116753ad70d34f0ac2925d1d8020/kotlin-stdlib-jdk8-1.8.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.8.0/3c91271347f678c239607abb676d4032a7898427/kotlin-stdlib-jdk7-1.8.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/23.0.0/8cc20c07506ec18e0834947b84a864bfc094484e/annotations-23.0.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-android/1.7.0/3f6da7e477aed4c55b0c9755002ca1d606da29c1/kotlinx-coroutines-android-1.7.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm/1.7.0/239d3e685a54ae7c75a03708b78f3a810b5fb360/kotlinx-coroutines-core-jvm-1.7.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.9.10/c7510d64a83411a649c76f2778304ddf71d7437b/kotlin-stdlib-jdk8-1.9.10.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.9.10/bc5bfc2690338defd5195b05c57562f2194eeb10/kotlin-stdlib-jdk7-1.9.10.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-runner-junit5-jvm/5.8.0/ac0bf80b9970b7c5b835454acb80f4bc07b378e5/kotest-runner-junit5-jvm-5.8.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-framework-api-jvm/5.8.0/d5c8cd2b5d00e56246ec47813495e8b2cd7c5c57/kotest-framework-api-jvm-5.8.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-assertions-shared-jvm/5.8.0/624e26cd61cdf900a7fded2783c4b747b406f7f5/kotest-assertions-shared-jvm-5.8.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-assertions-api-jvm/5.8.0/a96590a2196c65412679dcb226658547abc008a0/kotest-assertions-api-jvm-5.8.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-common-jvm/5.8.0/7163ede402fe8c884313494fbf2263f577cf1a64/kotest-common-jvm-5.8.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-test-jvm/1.7.0/78caf36355ea7198b4bc5e328a2ebed4e3358936/kotlinx-coroutines-test-jvm-1.7.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-framework-engine-jvm/5.8.0/eec53ed9b246634b7eee23828d59c8b70caeca0e/kotest-framework-engine-jvm-5.8.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/io.github.classgraph/classgraph/4.8.162/85bc1625bc8aac51ad32971ebb26a3e35cb97356/classgraph-4.8.162.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-framework-discovery-jvm/5.8.0/9a13b703f1cf45e5c7d63fd393cf446428e0802b/kotest-framework-discovery-jvm-5.8.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/com.github.ajalt/mordant/1.2.1/6cbab1a74ab6dafbf81b7706733d4c2fbaff2e0b/mordant-1.2.1.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/com.github.ajalt/colormath/1.2.0/c62f49b31f34588dbbfb477c08fd56bc3026d202/colormath-1.2.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-assertions-core-jvm/5.8.0/745144a20b1e3146f6a3ccb38a775abea5e0cb2c/kotest-assertions-core-jvm-5.8.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-extensions-jvm/5.8.0/3badce4a9576705e043fbe548d85ffe2ca30488d/kotest-extensions-jvm-5.8.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-framework-concurrency-jvm/5.8.0/dd63871080d2f739eb1937754f48abbf9a14b091/kotest-framework-concurrency-jvm-5.8.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-engine/1.8.2/b737de09f19864bd136805c84df7999a142fec29/junit-platform-engine-1.8.2.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.opentest4j/opentest4j/1.3.0/152ea56b3a72f655d4fd677fc0ef2596c3dd5e6e/opentest4j-1.3.0.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-commons/1.8.2/32c8b8617c1342376fd5af2053da6410d8866861/junit-platform-commons-1.8.2.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.apiguardian/apiguardian-api/1.1.2/a231e0d844d2721b0fa1b238006d15c6ded6842a/apiguardian-api-1.1.2.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-suite-api/1.8.2/a148ffd359cac121fcba000ad7f5a75b5e2ac2b4/junit-platform-suite-api-1.8.2.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-launcher/1.8.2/c334fcee82b81311ab5c426ec2d52d467c8d0b28/junit-platform-launcher-1.8.2.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-api/5.8.2/4c21029217adf07e4c0d0c5e192b6bf610c94bdc/junit-jupiter-api-5.8.2.jar:/Users/igorwojda/.gradle/caches/modules-2/files-2.1/com.lemonappdev/konsist/0.13.0/96a3d64fa236c448a06623cc47d711d08f7235d3/konsist-0.13.0.jar io.kotest.engine.launcher.MainKt --spec com.sample.SampleKonsistTest --testpath android activity class name ends with 'Activity' --reporter teamcity
Testing started at 19:11 ...
java.lang.NoClassDefFoundError: kotlin/reflect/full/KClasses
	at io.kotest.mpp.JvmReflection.annotations(reflection.kt:34)
	at io.kotest.mpp.JvmReflection.annotations(reflection.kt:25)
	at io.kotest.engine.concurrency.ConcurrencyKt.isIsolate(concurrency.kt:22)
	at io.kotest.engine.ConcurrentTestSuiteScheduler.schedule(ConcurrentTestSuiteScheduler.kt:41)
	at io.kotest.engine.TestEngine$execute$innerExecute$1.invokeSuspend(TestEngine.kt:63)
	at io.kotest.engine.TestEngine$execute$innerExecute$1.invoke(TestEngine.kt)
	at io.kotest.engine.TestEngine$execute$innerExecute$1.invoke(TestEngine.kt)
	at io.kotest.engine.interceptors.TestEngineInitializedInterceptor.intercept(TestEngineInitializedInterceptor.kt:16)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invokeSuspend(TestEngine.kt:69)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.interceptors.DumpConfigInterceptor.intercept(DumpConfigInterceptor.kt:21)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invokeSuspend(TestEngine.kt:69)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.interceptors.WriteFailuresInterceptor.intercept(WriteFailuresInterceptor.kt:34)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invokeSuspend(TestEngine.kt:69)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.interceptors.EmptyTestSuiteInterceptor.intercept(EmptyTestSuiteInterceptor.kt:27)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invokeSuspend(TestEngine.kt:69)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.interceptors.ProjectTimeoutEngineInterceptor.intercept(ProjectTimeoutEngineInterceptor.kt:15)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invokeSuspend(TestEngine.kt:69)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.interceptors.ProjectListenerEngineInterceptor.intercept(ProjectListenerEngineInterceptor.kt:23)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invokeSuspend(TestEngine.kt:69)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.interceptors.ProjectExtensionEngineInterceptor$intercept$initial$1.invokeSuspend(ProjectExtensionEngineInterceptor.kt:22)
	at io.kotest.engine.interceptors.ProjectExtensionEngineInterceptor$intercept$initial$1.invoke(ProjectExtensionEngineInterceptor.kt)
	at io.kotest.engine.interceptors.ProjectExtensionEngineInterceptor$intercept$initial$1.invoke(ProjectExtensionEngineInterceptor.kt)
	at io.kotest.engine.interceptors.ProjectExtensionEngineInterceptor.intercept(ProjectExtensionEngineInterceptor.kt:34)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invokeSuspend(TestEngine.kt:69)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.interceptors.SpecSortEngineInterceptor.intercept(SpecSortEngineInterceptor.kt:29)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invokeSuspend(TestEngine.kt:69)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.interceptors.TestDslStateInterceptor.intercept(TestDslStateInterceptor.kt:15)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invokeSuspend(TestEngine.kt:69)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.interceptors.TestEngineStartedFinishedInterceptor.intercept(TestEngineStartedFinishedInterceptor.kt:22)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invokeSuspend(TestEngine.kt:69)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.TestEngine$execute$execute$1$1.invoke(TestEngine.kt)
	at io.kotest.engine.TestEngine.execute$kotest_framework_engine(TestEngine.kt:75)
	at io.kotest.engine.TestEngineLauncher.async(TestEngineLauncher.kt:241)
	at io.kotest.engine.launcher.MainKt$main$1.invokeSuspend(main.kt:36)
	at io.kotest.engine.launcher.MainKt$main$1.invoke(main.kt)
	at io.kotest.engine.launcher.MainKt$main$1.invoke(main.kt)
	at io.kotest.common.RunBlockingKt$runBlocking$1.invokeSuspend(runBlocking.kt:3)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.common.RunBlockingKt.runBlocking(runBlocking.kt:3)
	at io.kotest.engine.launcher.MainKt.main(main.kt:34)
Caused by: java.lang.ClassNotFoundException: kotlin.reflect.full.KClasses
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 66 more

kotlin/reflect/full/KClasses

Process finished with exit code 255

```

Attaching sample Android Project
[konsist-starter-android-gradle-kotlin-kotest.zip](https://github.com/kotest/kotest/files/14541724/konsist-starter-android-gradle-kotlin-kotest.zip)

**Comment by sksamuel** [comment]
When you run the full class, is it using the gradle runner, and when you run a single test, the kotest runner ?

**Comment by igorwojda** [comment]
Good question. How can I verify this?

**Comment by sksamuel** [comment]
When you click the run icon do you see a gradle icon or a kotest icon in the run configuration dropdown?

**Comment by igorwojda** [comment]
Yes Gradle runner for all tests, and Kotest runner  for a single test

Actually I see both<img width="455" alt="image" src="https://github.com/kotest/kotest/assets/530122/2a6a3178-0447-401b-82c4-6a6ac3201cd1">

**Comment by nsk90** [comment]
looks it is duplicate of https://github.com/kotest/kotest/issues/3651

**Comment by LeoColman** [comment]
Closing as duplicate of #3651
