### ISSUE TITLE
Stacktrace lost when using custom matcher with `should` 

### ISSUE THREAD

**Issue by kirillzh** [kotest/kotest#3925]
**Which version of Kotest are you using**
5.8.0

I have a matcher like this:
```kotlin
fun beEnabled(buttonModel: ButtonModel) =
  Matcher<ButtonModel> { model ->
    MatcherResult(
      buttonModel.isEnabled,
      { "expected $model to be enabled" },
      { "expected $model to not be enabled" }
    )
  }

fun ButtonModel.shouldBeEnabled(): ButtonModel =
  apply {
    this should beEnabled(this)
  }
```

On failure `shouldBeEnabled` throws assertion error without full stacktrace which makes it hard to figure out where that assertion failed exactly:

```java
java.lang.AssertionError: ....
expected ButtonModel(text=Continue, isEnabled=false, isLoading=false, leadingIcon=null, treatment=Primary, size=Footer, testTag=null, onClick=StandardClick(onClick=() -> kotlin.Unit)) to be enabled
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

When I change `shouldBeEnabled` implementation to this, I get the full stacktrace on failure, am I implementing a custom matcher wrong?
```kotlin
fun ButtonModel.shouldBeEnabled(): ButtonModel =
  apply {
    this.isEnabled.shouldBeTrue()
  }
```

**Comment by sksamuel** [comment]
Is this the exact copy n paste from what you're using, because I can't see why this would be wrong.

**Comment by LeoColman** [comment]
I think it's missing the class that the exception ocurred, and that's what they're pointing out

**Comment by sksamuel** [comment]
Yeah but when I try it I get the full stack trace.

**Comment by sksamuel** [comment]
Kotest 6.0 has support for decoroutinator. That is the way to handle this.
See https://github.com/kotest/kotest/issues/4886
