### ISSUE TITLE
Foreground coroutines are not waited for by the test when debug probes are enabled, in the root spec

### ISSUE THREAD

**Issue by CLOVIS-AI** [kotest/kotest#4058]
**Which version of Kotest are you using**
5.9.0

Normally, kotlinx-coroutines-test awaits all foreground coroutines before ending the test.

### Example 1

```kotlin
class ForegroundTest1 : FunSpec({
	this.coroutineTestScope = true
	this.coroutineDebugProbes = false

	test("Start foreground task") {
		launch {
			delay(1000)
			println("In a foreground scope")
		}
		println("In the test body")
	}
})
```

Output:
```
In the test body
In a foreground scope
```

This is the expected behavior. The test body finished, then awaited foreground coroutines.

### Example 2

```kotlin
class ForegroundTest2 : FunSpec({
	this.coroutineTestScope = true
	this.coroutineDebugProbes = true

	test("Start foreground task") {
		launch {
			delay(1000)
			println("In a foreground scope")
		}
		println("In the test body")
	}
})
```

Output:
```
In the test body
Coroutines dump 2024/06/03 20:33:44

Coroutine "coroutine#15":StandaloneCoroutine{Active}@6d071712, state: CREATED
	at _COROUTINE._CREATION._(CoroutineDebugging.kt:30)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.createCoroutineUnintercepted(IntrinsicsJvm.kt:161)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
```

This is incorrect behavior: the test should have waited for all foreground tasks to run before terminating. The output should be exactly the same as the first example.

The same problem is observed with `StringSpec`. I did not test the other specs.

### Example 3

Interestingly enough, this bug does not appear in nested tests.

```kotlin
class ForegroundTest3 : FunSpec({

	context("Without debug probes") {
		coroutineTestScope = true
		coroutineDebugProbes = false

		test("Start foreground task") {
			launch {
				delay(1000)
				println("In a foreground scope")
			}
			println("In the test body")
		}
	}

	context("With debug probes") {
		coroutineTestScope = true
		coroutineDebugProbes = true

		test("Start foreground task") {
			launch {
				delay(1000)
				println("In a foreground scope")
			}
			println("In the test body")
		}
	}
})
```

Output:
```
In the test body
In a foreground scope

In the test body
In a foreground scope
```

This made it particularly difficult to track down :sweat_smile: I hope that helps you find the cause, somehow.

**Comment by OliverO2** [comment]
> Normally, kotlinx-coroutines-test awaits all foreground coroutines before ending the test.

Is this documented somewhere?

Kotest has no notion of "foreground" coroutines. A test function is a `coroutineScope { ... }` which waits for jobs launched inside.

Now with debug probes, when would we expect them to check for runaway jobs? Before closing the test function's `CoroutineScope` (like above) or afterwards?

The differences in the above observations seem to be caused by scheduling differences in [withDebugProbe.kt](https://github.com/kotest/kotest/blob/fca03f350665503a1ccb841e0ab8385a48f83331/kotest-framework/kotest-framework-engine/src/jvmMain/kotlin/io/kotest/engine/concurrency/withDebugProbe.kt) invoked by [CoroutineDebugProbeInterceptor.kt](https://github.com/kotest/kotest/blob/3ab7ab0419a0a60fda7e8b827fcbba74d20be473/kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/test/interceptors/CoroutineDebugProbeInterceptor.kt). With the test schedule there is no real time, so machine differences matter.

**Comment by CLOVIS-AI** [comment]
I did not find any documentation regarding this behavior, however it can be observed with this code ([playground](https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMi4wLjAiLCJwbGF0Zm9ybSI6ImphdmEiLCJhcmdzIjoiIiwibm9uZU1hcmtlcnMiOnRydWUsInRoZW1lIjoiaWRlYSIsImNvZGUiOiJpbXBvcnQga290bGluLnRpbWUuRHVyYXRpb24uQ29tcGFuaW9uLnNlY29uZHNcbmltcG9ydCBrb3RsaW54LmNvcm91dGluZXMuKlxuaW1wb3J0IGtvdGxpbnguY29yb3V0aW5lcy50ZXN0LipcblxuZnVuIG1haW4oKSA9IHJ1blRlc3Qge1xuICAgIGxhdW5jaChDb3JvdXRpbmVOYW1lKFwiRm9yZWdyb3VuZCBjb3JvdXRpbmVcIikpIHtcbiAgICAgICAgZGVsYXkoMTAwKVxuICAgICAgICBwcmludGxuKFwiRm9yZWdyb3VuZCBjb3JvdXRpbmUgZG9uZVwiKVxuICAgIH1cbiAgICBcbiAgICBiYWNrZ3JvdW5kU2NvcGUubGF1bmNoKENvcm91dGluZU5hbWUoXCJTaG9ydCBiYWNrZ3JvdW5kIGNvcm91dGluZVwiKSkge1xuICAgICAgICBkZWxheSg1MClcbiAgICAgICAgcHJpbnRsbihcIlNob3J0IGJhY2tncm91bmQgY29yb3V0aW5lIGRvbmVcIilcbiAgICB9XG4gICAgXG4gICAgYmFja2dyb3VuZFNjb3BlLmxhdW5jaChDb3JvdXRpbmVOYW1lKFwiTG9uZyBiYWNrZ3JvdW5kIGNvcm91dGluZVwiKSkge1xuICAgICAgICBkZWxheSgxNTApXG4gICAgICAgIHByaW50bG4oXCJMb25nIGJhY2tncm91bmQgY29yb3V0aW5lIGRvbmVcIilcbiAgICB9XG4gICAgXG4gICAgcHJpbnRsbihcIlRlc3QgYm9keSBpcyBmaW5pc2hlZFwiKVxufSJ9)):
```kotlin
fun main() = runTest {
    launch(CoroutineName("Foreground coroutine")) {
        delay(100)
        println("Foreground coroutine done")
    }
    
    backgroundScope.launch(CoroutineName("Short background coroutine")) {
        delay(50)
        println("Short background coroutine done")
    }
    
    backgroundScope.launch(CoroutineName("Long background coroutine")) {
        delay(150)
        println("Long background coroutine done")
    }
    
    println("Test body is finished")
}
```

Output:
```
Test body is finished
Short background coroutine done
Foreground coroutine done
```

As we can see, when the test body is finished, `runTest` waits for all foreground coroutines (started with `launch`) before actually finishing the test. Once all foreground coroutines are done, the background coroutines that are left are cancelled and dumped if debugging is enabled (I do not know how to enable debug probes on the playground).

[Related discussion in the KotlinLang Slack](https://kotlinlang.slack.com/archives/C1CFAFJSK/p1717351769964539).

> Now with debug probes, when would we expect them to check for runaway jobs? Before closing the test function's CoroutineScope (like above) or afterwards?

When all foreground coroutines have terminated. Alternatively, when the test timeout is reached, anything still running is considered a runaway job.
