### ISSUE TITLE
RobolectricTest with compose navigation and savedStateHandle results in exception

### ISSUE THREAD

**Issue by petros-chariskos** [kotest/kotest#4161]
kotest version: 5.9.1
compose navigation version: 2.8.0-beta04

When testing a ViewModel that has a dependency to a `SavedStateHandle` and we retrieve the navigation arguments via the compose safe navigation framework by calling `savedStateHandle.toRoute()` then the test fails.

Sample code (from nowinandroid app):
```
@RobolectricTest
class InterestsViewModelTest : FunSpec() {
    private val userDataRepository = TestUserDataRepository()
    private val topicsRepository = TestTopicsRepository()
    private val getFollowableTopicsUseCase =
        GetFollowableTopicsUseCase(
            topicsRepository = topicsRepository,
            userDataRepository = userDataRepository,
        )
    private lateinit var viewModel: InterestsViewModel

    init {
        isolationMode = IsolationMode.InstancePerLeaf
        listener(InstantExecutorListener())

        beforeTest {
            viewModel =
                InterestsViewModel(
                    savedStateHandle =
                        SavedStateHandle(
                            route = InterestsRoute(initialTopicId = "sampleId"),
                        ),
                    userDataRepository = userDataRepository,
                    getFollowableTopics = getFollowableTopicsUseCase,
                )
        }

        test("uiState_whenInitialized_thenShowLoading") {
            assertEquals(InterestsUiState.Loading, viewModel.uiState.value)
        }
    }
}
```

Exception:
```
java.lang.NullPointerException: bundle.keySet() must not be null
io.kotest.engine.extensions.ExtensionException$BeforeAnyException: java.lang.NullPointerException: bundle.keySet() must not be null
	at app//io.kotest.engine.test.TestExtensions$beforeTestBeforeAnyBeforeContainer$errors$3$2.invoke(TestExtensions.kt:86)
	at app//io.kotest.engine.test.TestExtensions$beforeTestBeforeAnyBeforeContainer$errors$3$2.invoke(TestExtensions.kt:86)
	at app//io.kotest.common.ResultsKt.mapError(results.kt:17)
	at app//io.kotest.engine.test.TestExtensions.beforeTestBeforeAnyBeforeContainer-gIAlu-s(TestExtensions.kt:86)
	at app//io.kotest.engine.test.interceptors.LifecycleInterceptor.intercept(LifecycleInterceptor.kt:47)
	at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at app//io.kotest.engine.test.interceptors.TestCaseExtensionInterceptor$intercept$2.invokeSuspend(TestCaseExtensionInterceptor.kt:24)
	at app//io.kotest.engine.test.interceptors.TestCaseExtensionInterceptor$intercept$2.invoke(TestCaseExtensionInterceptor.kt)
	at app//io.kotest.engine.test.interceptors.TestCaseExtensionInterceptor$intercept$2.invoke(TestCaseExtensionInterceptor.kt)
	at app//io.kotest.engine.test.TestExtensions.intercept(TestExtensions.kt:148)
	at app//io.kotest.engine.test.interceptors.TestCaseExtensionInterceptor.intercept(TestCaseExtensionInterceptor.kt:24)
	at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at app//io.kotest.engine.test.interceptors.BeforeSpecListenerInterceptor$intercept$runTest$1$4$1.invokeSuspend(BeforeSpecListenerInterceptor.kt:50)
	at app//io.kotest.engine.test.interceptors.BeforeSpecListenerInterceptor$intercept$runTest$1$4$1.invoke(BeforeSpecListenerInterceptor.kt)
	at app//io.kotest.engine.test.interceptors.BeforeSpecListenerInterceptor$intercept$runTest$1$4$1.invoke(BeforeSpecListenerInterceptor.kt)
	at app//io.kotest.engine.test.interceptors.BeforeSpecListenerInterceptor.intercept(BeforeSpecListenerInterceptor.kt:60)
	at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at app//io.kotest.engine.test.interceptors.TestEnabledCheckInterceptor.intercept(TestEnabledCheckInterceptor.kt:31)
	at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at app//io.kotest.engine.test.interceptors.CoroutineErrorCollectorInterceptor$intercept$3.invokeSuspend(CoroutineErrorCollectorInterceptor.kt:34)
	at app//io.kotest.engine.test.interceptors.CoroutineErrorCollectorInterceptor$intercept$3.invoke(CoroutineErrorCollectorInterceptor.kt)
	at app//io.kotest.engine.test.interceptors.CoroutineErrorCollectorInterceptor$intercept$3.invoke(CoroutineErrorCollectorInterceptor.kt)
	at app//kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
	at app//kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at app//kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at app//io.kotest.engine.test.interceptors.CoroutineErrorCollectorInterceptor.intercept(CoroutineErrorCollectorInterceptor.kt:33)
	at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invokeSuspend(TestCaseExecutor.kt:100)
	at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at app//io.kotest.engine.test.TestCaseExecutor$execute$3$1.invoke(TestCaseExecutor.kt)
	at app//io.kotest.engine.test.interceptors.CoroutineDispatcherFactoryInterceptor$intercept$4.invokeSuspend(coroutineDispatcherFactoryInterceptor.kt:57)
	at app//io.kotest.engine.test.interceptors.CoroutineDispatcherFactoryInterceptor$intercept$4.invoke(coroutineDispatcherFactoryInterceptor.kt)
	at app//io.kotest.engine.test.interceptors.CoroutineDispatcherFactoryInterceptor$intercept$4.invoke(coroutineDispatcherFactoryInterceptor.kt)
	at app//io.kotest.engine.concurrency.FixedThreadCoroutineDispatcherFactory$withDispatcher$4.invokeSuspend(FixedThreadCoroutineDispatcherFactory.kt:59)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base@17.0.10/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: bundle.keySet() must not be null
	at androidx.navigation.testing.SavedStateHandleFactoryKt.invoke(SavedStateHandleFactory.kt:101)
	at androidx.navigation.testing.SavedStateHandleFactoryKt.invoke$default(SavedStateHandleFactory.kt:45)
	at com.google.samples.apps.nowinandroid.interests.InterestsViewModelTest$1.invokeSuspend(InterestsViewModelTest.kt:63)
	at com.google.samples.apps.nowinandroid.interests.InterestsViewModelTest$1.invoke(InterestsViewModelTest.kt)
	at com.google.samples.apps.nowinandroid.interests.InterestsViewModelTest$1.invoke(InterestsViewModelTest.kt)
	at io.kotest.core.spec.Spec$beforeTest$2.beforeTest(Spec.kt:365)
	at io.kotest.engine.test.TestExtensions.beforeTestBeforeAnyBeforeContainer-gIAlu-s(TestExtensions.kt:85)
	... 42 more
```

**Comment by LeoColman** [comment]
Unfortunately Kotest doesn't support Android/Robolectric tests out of the box.
If interested, I do maintain a robolectric extension here: https://github.com/LeoColman/kotest-android
