### ISSUE TITLE
LoadProjectConfigFromClassnameKt can not access a member of class my.project.KotestProjectConfig with modifiers "private"

### ISSUE THREAD

**Issue by aSemy** [kotest/kotest#4176]
I updated my project to avoid classpath scanning, and manually specified the FQN of the Kotest config class.

```kotlin
// build.gradle.kts
tasks.withType<Test>().configureEach {
  systemProperty("kotest.framework.config.fqn", "my.project.KotestProjectConfig")
  // FIXME remove when Kotest >= 6.0
  systemProperty("kotest.framework.classpath.scanning.autoscan.disable", "true")
}
```

But when I run the tests, I got an error:

```
TestEngine with ID 'kotest' failed to execute tests
org.junit.platform.commons.JUnitException: TestEngine with ID 'kotest' failed to execute tests
Caused by: io.kotest.engine.config.ConfigurationException: java.lang.IllegalAccessException: Class io.kotest.engine.config.LoadProjectConfigFromClassnameKt can not access a member of class my.project.KotestProjectConfig with modifiers "private"
	at io.kotest.engine.config.ConfigManager$compile$2.invoke(ConfigManager.kt:29)
	at io.kotest.engine.config.ConfigManager$compile$2.invoke(ConfigManager.kt:29)
	at io.kotest.common.ResultsKt.mapError(results.kt:8)
	at io.kotest.engine.config.ConfigManager.compile-gIAlu-s(ConfigManager.kt:29)
	at io.kotest.engine.config.ConfigManager.initialize(ConfigManager.kt:19)
	at io.kotest.engine.TestEngineLauncher.toConfig(TestEngineLauncher.kt:196)
	at io.kotest.engine.TestEngineLauncher$launch$2.invokeSuspend(TestEngineLauncher.kt:222)
	at io.kotest.engine.TestEngineLauncher$launch$2.invoke(TestEngineLauncher.kt)
	at io.kotest.engine.TestEngineLauncher$launch$2.invoke(TestEngineLauncher.kt)
	at io.kotest.common.RunBlockingKt$runBlocking$1.invokeSuspend(runBlocking.kt:3)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.common.RunBlockingKt.runBlocking(runBlocking.kt:3)
	at io.kotest.engine.TestEngineLauncher.launch(TestEngineLauncher.kt:221)
	at io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine.execute(KotestJunitPlatformTestEngine.kt:78)
	at io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine.execute(KotestJunitPlatformTestEngine.kt:50)
Caused by: java.lang.IllegalAccessException: Class io.kotest.engine.config.LoadProjectConfigFromClassnameKt can not access a member of class my.project.KotestProjectConfig with modifiers "private"
	at java.lang.Class.newInstance(Class.java:436)
	at io.kotest.engine.config.LoadProjectConfigFromClassnameKt.loadProjectConfigFromClassname(loadProjectConfigFromClassname.kt:8)
	at io.kotest.engine.TestEngineLauncher$toConfig$2.invoke(TestEngineLauncher.kt:198)
	at io.kotest.engine.TestEngineLauncher$toConfig$2.invoke(TestEngineLauncher.kt:196)
	at io.kotest.engine.config.ConfigManager.compile-gIAlu-s(ConfigManager.kt:28)
	... 18 more

```

It started working when I changed `object KotestProjectConfig : AbstractProjectConfig()` to `class KotestProjectConfig : AbstractProjectConfig()`. [The docs](https://kotest.io/docs/framework/project-config.html) use `object KotestProjectConfig : AbstractProjectConfig()` as an example, this should be changed?

**Comment by sksamuel** [comment]
We should support objects too. Just seems a bug.

**Comment by sksamuel** [comment]
Just added a test and it seems we already support objects.
Did you have a private field in here as well ?
Can you paste up the object you were using ?

**Comment by sksamuel** [comment]
@aSemy you got a reproducer ?

**Comment by aSemy** [comment]
I tried recreating it, but I couldn't. I think it was something to do with using `java-test-fixtures`, or maybe `internal` visibility, and maybe autoscan, but I guess now that autoscan is removed it's not a problem.
