### ISSUE TITLE
@ApplyExtension(SpringAutowireConstructorExtension::class) support

### ISSUE THREAD

**Issue by straxess** [kotest/kotest#4260]
When autoscan is disabled, I need to create my own ProjectConfig and specify `SpringAutowireConstructorExtension` inside 
because the `@ApplyExtension` annotation unfortunately does not work with `SpringAutowireConstructorExtension`:
```
class CommonProjectConfig : AbstractProjectConfig() {
    override fun extensions() = listOf(SpringAutowireConstructorExtension)
}
```

and `kotest.properties`:
```
kotest.framework.classpath.scanning.config.disable=true
kotest.framework.classpath.scanning.autoscan.disable=true
kotest.framework.config.fqn={...}.CommonProjectConfig
```

My versions:
```
io.kotest:kotest-runner-junit5-jvm:5.9.1
io.kotest:kotest-framework-datatest:5.9.1
io.kotest.extensions:kotest-extensions-spring:1.3.0
org.junit.jupiter:junit-jupiter-engine:5.10.3
org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.0.0
org.apache.maven.plugins:maven-surefire-plugin:3.1.2
```

I want to avoid creation of my custom ProjectConfig and I want to avoid performance issues with autoscan (my project is large).

My dream is to remove `kotest.framework.config.fqn={...}.CommonProjectConfig` from `kotest.properties` and rewrite my test as follows:
```
@SpringBootTest(
    classes = [ConfigService::class],
    webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT
)
@ApplyExtension(SpringAutowireConstructorExtension::class)
class ConfigServerTest(
    @LocalServerPort port: Int,
    restTemplate: TestRestTemplate
) : BehaviorSpec({

    val baseUrl = "http://localhost:$port"

    context("getting config by correct profile is successful") {
            restTemplate.getForObject<String>("$baseUrl/"application-example.yml"")
                .shouldContain("test-property")
                .shouldContain("some-test-property")
    }
}
```
But at the moment, if I perform these actions, I get an exception about requiring a constructor with no parameters:
```
io.kotest.engine.spec.SpecInstantiationException: Could not create instance of class {...}.ConfigServerTest. Specs must have a public zero-arg constructor.
	at io.kotest.engine.spec.InstantiateSpecKt.javaReflectNewInstance(instantiateSpec.kt:46)
	at io.kotest.engine.spec.InstantiateSpecKt.createAndInitializeSpec(instantiateSpec.kt:30)
	at io.kotest.engine.spec.InstantiateSpecKt.instantiate(instantiateSpec.kt:11)
	at io.kotest.engine.spec.SpecRefKt.instance(SpecRef.kt:14)
	at io.kotest.engine.spec.SpecExecutor.createInstance-gIAlu-s(SpecExecutor.kt:63)
	at io.kotest.engine.spec.SpecExecutor.access$createInstance-gIAlu-s(SpecExecutor.kt:24)
	at io.kotest.engine.spec.SpecExecutor$execute$innerExecute$1.invokeSuspend(SpecExecutor.kt:40)
	at io.kotest.engine.spec.SpecExecutor$execute$innerExecute$1.invoke(SpecExecutor.kt)
	at io.kotest.engine.spec.SpecExecutor$execute$innerExecute$1.invoke(SpecExecutor.kt)
	at io.kotest.engine.spec.interceptor.ref.FinalizeSpecInterceptor.intercept-0E7RQCE(FinalizeSpecInterceptor.kt:24)
	at ...
```

And I have seen information that autoscanning will be completely disabled in `kotest` 6.0, in which case I will 
remove `kotest.properties` completely for all my modules, replacing it with `@ApplyExtension(SpringAutowireConstructorExtension::class)` only in the places where I really need it. And that would be the clearest and most reliable way to set up `kotest` for me.

---

I guess this will be a good feature that can increase isolation of specs and avoid creating custom projectConfig.

**Comment by sksamuel** [comment]
I think what's happening here is the apply extension is not applied to construction of classes.
That's a bug, thanks for report.

**Comment by sksamuel** [comment]
Pr up
