### ISSUE TITLE
Kotest plugin keeps on crashing when open the IDE

### ISSUE THREAD

**Issue by andriesfc** [kotest/kotest#4498]
**Which version of Kotest _PLUGIN_ are you using** 
1.3.86-243-EAP-SNAPSHOT

```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation. Dumb mode start trace is in attachment.
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:69)
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:65)
	at org.jetbrains.kotlin.analysis.api.impl.base.sessions.KaBaseSessionProvider.beforeEnteringAnalysis(KaBaseSessionProvider.kt:64)
	at org.jetbrains.kotlin.analysis.api.impl.base.sessions.KaBaseSessionProvider.beforeEnteringAnalysis(KaBaseSessionProvider.kt:47)
	at io.kotest.plugin.intellij.psi.SuperClassesKt.getAllSuperClasses(superClasses.kt:56)
	at io.kotest.plugin.intellij.psi.SpecsKt.specStyle(specs.kt:52)
	at io.kotest.plugin.intellij.structure.KotestStructureViewExtension.getChildren(KotestStructureViewExtension.kt:24)
	at com.intellij.ide.structureView.impl.common.PsiTreeElementBase.mergeWithExtensions(PsiTreeElementBase.java:146)
	at com.intellij.ide.structureView.impl.common.PsiTreeElementBase.doGetChildren(PsiTreeElementBase.java:89)
	at com.intellij.ide.structureView.impl.common.PsiTreeElementBase.getChildrenWithoutCustomRegions(PsiTreeElementBase.java:79)
	at com.intellij.ide.navigationToolbar.StructureAwareNavBarModelExtension.childrenFromNodeAndProviders(StructureAwareNavBarModelExtension.kt:143)
	at com.intellij.ide.navigationToolbar.StructureAwareNavBarModelExtension.findParentInModel(StructureAwareNavBarModelExtension.kt:93)
	at com.intellij.ide.navigationToolbar.StructureAwareNavBarModelExtension.findParentInModel(StructureAwareNavBarModelExtension.kt:97)
	at com.intellij.ide.navigationToolbar.StructureAwareNavBarModelExtension.getParent(StructureAwareNavBarModelExtension.kt:79)
	at com.intellij.platform.navbar.backend.impl.DefaultNavBarItemProviderKt.parentFromOldExtensions(DefaultNavBarItemProvider.kt:125)
	at com.intellij.platform.navbar.backend.impl.DefaultNavBarItemProviderKt.access$parentFromOldExtensions(DefaultNavBarItemProvider.kt:1)
	at com.intellij.platform.navbar.backend.impl.DefaultNavBarItemProvider.findParent(DefaultNavBarItemProvider.kt:59)
	at com.intellij.platform.navbar.backend.impl.ImplKt.findParent(impl.kt:19)
	at com.intellij.platform.navbar.backend.impl.ImplKt.pathToItem$lambda$0(impl.kt:13)
	at kotlin.sequences.GeneratorSequence$iterator$1.calcNext(Sequences.kt:609)
	at kotlin.sequences.GeneratorSequence$iterator$1.hasNext(Sequences.kt:627)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:816)
	at com.intellij.platform.navbar.backend.impl.ImplKt.pathToItem(impl.kt:14)
	at com.intellij.platform.navbar.monolith.MonolithNavbarServiceDelegate.contextModel$lambda$1(MonolithNavBarServiceDelegate.kt:38)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:114)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable$lambda$4(InternalReadAction.kt:104)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2$lambda$1(cancellableReadAction.kt:32)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:351)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2(cancellableReadAction.kt:30)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:28)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:103)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:87)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:74)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invokeSuspend(InternalReadAction.kt:53)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:49)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:62)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:29)
	at com.intellij.platform.navbar.monolith.MonolithNavbarServiceDelegate.contextModel(MonolithNavBarServiceDelegate.kt:33)
	at com.intellij.platform.navbar.frontend.NavBarServiceKt.contextModel(NavBarService.kt:148)
	at com.intellij.platform.navbar.frontend.NavBarService$contextItems$1.invokeSuspend(NavBarService.kt:96)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

```

**Comment by benjishults** [comment]
I'm seeing the same stack trace FWIW.

**Comment by AntonShuvaev** [comment]
Are there any plans to fix this? It’s really annoying to encounter this error every time the IDE starts.

**Comment by sksamuel** [comment]
https://github.com/kotest/kotest-intellij-plugin/pull/328

**Comment by sksamuel** [comment]
Will need to wait for jetbrains to approve it on a working day, but it's fixed.
