### ISSUE TITLE
"create test" stopped working

### ISSUE THREAD

**Issue by jlous** [kotest/kotest#4502]
The dialog comes up normally, but when I press OK and the dialog closes, nothing is created.
Works for Junit, but not KoTest

kotest 5.9.1
kotest plugin 1.3.86-243-EAP-SNAPSHOT
IntelliJ IDEA 2024.3

**Comment by hjed** [comment]
Also experiencing this issue on upgrade to intelij 2024.3
Same kotest plugin version as above. 
Kotest Version 4.6.3

Running kotest tests works once created manually if that's relevant

**Comment by jlous** [comment]
correction: the package is created, but no file

**Comment by jlous** [comment]
I this related to https://github.com/kotest/kotest/issues/4532?

**Comment by sksamuel** [comment]
> correction: the package is created, but no file

Did you change something - upgrade intellij, kotest, etc ?

**Comment by jlous** [comment]
I think it is new to 2024.3, but haven't verified with a downgrade.

**Comment by sksamuel** [comment]
Hmm I am on 2024.3 and it works for me.
Are you on KMP or JVM ?

**Comment by hjed** [comment]
The upgrade is also what broke it for me. (And same behaviour with the package being created).

I'm on JVM (17 if that's relevant). And I'm seeing this in multiple different projects I'm working on.

**Comment by sksamuel** [comment]
What's your exact intellij build ?

IntelliJ IDEA 2024.3 (Ultimate Edition)
Build #IU-243.21565.193, built on November 12, 2024

**Comment by sksamuel** [comment]
And is there a stacktrace in the intellij debug popup when this happens ?

**Comment by hjed** [comment]
Mine is `Build #IU-243.21565.193, built on November 13, 2024` Maybe Mac/arm is a factor? 

```
Runtime version: 21.0.5+8-b631.16 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```

No error popup. I do see this in the idea.log and it seems to corelate with clicking "create":

```
024-12-09 17:48:03,320 [6888914]   WARN - #c.i.u.Alarm - Do not create alarm without coroutineScope: com.intellij.ide.util.gotoByName.ChooseByNameBase.<init>(ChooseByNameBase.java:122)
2024-12-09 17:48:03,321 [6888915]   WARN - #c.i.u.Alarm - Do not create alarm without coroutineScope: com.intellij.ide.util.gotoByName.ChooseByNameBase.<init>(ChooseByNameBase.java:136)
2024-12-09 17:48:03,322 [6888916]   WARN - #c.i.u.Alarm - Do not create alarm without coroutineScope: com.intellij.ide.util.gotoByName.ChooseByNameBase.<init>(ChooseByNameBase.java:122)
2024-12-09 17:48:03,322 [6888916]   WARN - #c.i.u.Alarm - Do not create alarm without coroutineScope: com.intellij.ide.util.gotoByName.ChooseByNameBase.<init>(ChooseByNameBase.java:136)
```

**Comment by jlous** [comment]
Seems the problem only occurs in K2 mode.

IDEA Build #IU-243.21565.193, built on November 13, 2024
Runtime version: 21.0.5+8-b631.16 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Apple M1 Pro, MacOs 14.7.1 (23H222)

**Comment by jlous** [comment]
This is probably as expected, but anyway: 
Still present with IntelliJ IDEA 2024.3.1 + plugin 1.3.89-243-EAP-SNAPSHOT
Workaround (switch off k2 mode) still works

**Comment by sksamuel** [comment]
Once I get a reply to this should be able to fix properly.
https://platform.jetbrains.com/t/trying-to-work-around-prohibitedanalysisexception-analysis-is-not-allowed-called-in-the-edt-thread/1152

**Comment by huehnerlady** [comment]
When I want to find a test with cmd+shift+T I get the exception:

```
java.lang.IllegalArgumentException: Must not run on the EDT
	at io.kotest.plugin.intellij.psi.SuperClassesKt.getAllSuperClasses(superClasses.kt:18)
	at io.kotest.plugin.intellij.psi.SpecsKt.specStyle(specs.kt:52)
	at io.kotest.plugin.intellij.psi.SpecsKt.isSpec(specs.kt:31)
	at io.kotest.plugin.intellij.psi.SpecsKt.isContainedInSpec(specs.kt:76)
	at io.kotest.plugin.intellij.KotestTestFinder.isTest(KotestTestFinder.kt:45)
	at com.intellij.testIntegration.TestFinderHelper.isTest(TestFinderHelper.java:48)
	at com.intellij.testIntegration.GotoTestOrCodeHandler.getSourceAndTargetElements(GotoTestOrCodeHandler.java:49)
	at com.intellij.codeInsight.navigation.GotoTargetHandler.invoke(GotoTargetHandler.java:69)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$0(CodeInsightAction.java:73)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$1(CodeInsightAction.java:79)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:226)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:159)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:70)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:41)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.kt:374)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:32)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$actionProcessor$1.performAction(IdeKeyEventDispatcher.kt:499)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$8$lambda$7(IdeKeyEventDispatcher.kt:850)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:98)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$8(IdeKeyEventDispatcher.kt:850)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:1173)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.kt:396)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner(IdeKeyEventDispatcher.kt:848)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.access$doPerformActionInner(IdeKeyEventDispatcher.kt:1)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.kt:577)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.kt:512)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.kt:451)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.kt:444)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.kt:306)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:606)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$22(IdeEventQueue.kt:565)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:917)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:117)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```


Kotest-plugin version: 1.3.93-2024.3.1
Kotest version: 5.9.1
Intellij: IntelliJ IDEA 2024.3.5 (Ultimate Edition)
Build #IU-243.26053.27, built on March 16, 2025
macOS 15.4
Kotlin plugin: K2 mode


Maybe this helps?

**Comment by sksamuel** [comment]
Closed as fixed in latest plugin release
