### ISSUE TITLE
Kotest swallows exception thrown in coroutine and reports TestTimeoutException

### ISSUE THREAD

**Issue by bliessens** [kotest/kotest#4593]
Kotest version `6.0.0.M1` and `5.9.1`

Runnnig below describe spec:

```kotlin

        describe("Kotest swallows exception in coroutine") {
            launch {
                val seq =
                    sequence {
                        val values = listOf(1, 2, 3)

                        yield(values.get(0))
                        yield(values.get(1))
                        yield(values.get(2))
                        yield(values.get(3))
                    }

                seq.forEach {
                    println(it)
                }
            }.join()
        }

```

fails with this stacktrack:

```
Test 'Kotest swallows exception in coroutine' did not complete within 10m
io.kotest.engine.test.interceptors.TestTimeoutException: Test 'Kotest swallows exception in coroutine' did not complete within 10m
	at io.kotest.engine.test.interceptors.TimeoutInterceptor.intercept(TimeoutInterceptor.kt:40)
	at io.kotest.engine.test.interceptors.TimeoutInterceptor$intercept$1.invokeSuspend(TimeoutInterceptor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith$$$capture(ContinuationImpl.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:28)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith$$$capture(ContinuationImpl.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:28)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith$$$capture(ContinuationImpl.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:99)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
``` 

While I'ld expect to see the actual root cause exception

**Comment by sksamuel** [comment]
```
class F : DescribeSpec() {
   init {
      describe("Kotest swallows exception in coroutine") {
         launch {
            val seq =
               sequence {
                  val values = listOf(1, 2, 3)

                  yield(values.get(0))
                  yield(values.get(1))
                  yield(values.get(2))
                  yield(values.get(3))
               }

            seq.forEach {
               println(it)
            }
         }.join()
      }
   }
}

```

Gives me

```
1
2
3
java.lang.ArrayIndexOutOfBoundsException: 3
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at com.sksamuel.kotest.engine.spec.style.F$1$1$seq$1.invokeSuspend(FunSpecTest.kt:92)
```

Is there more to the test than what you pasted ?

**Comment by bliessens** [comment]
I get the same `TestTimeoutException` exception when running your `class F` sample. 

This is my complete test class:

```kotlin
class G : DescribeSpec({

        describe("Kotest swallows exception in coroutine") {
            launch {
                val seq =
                    sequence {
                        val values = listOf(1, 2, 3)

                        yield(values.get(0))
                        yield(values.get(1))
                        yield(values.get(2))
                        yield(values.get(3))
                    }

                seq.forEach {
                    println(it)
                }
            }.join()
        }
    })

```

I'm running the spec in IntelliJ with Kotest run configuration

**Comment by bliessens** [comment]
Extracted above test case in separate project: https://github.com/bliessens/kotest-debug

this is what I have so far: 
// Eclipse Temurin 21 + kotest 5.9.1 + kotlin 2.0.21 => ArrayIndexOutOfBoundsException
// Eclipse Temurin 21 + kotest 5.9.1 + kotlin 2.1.0 => ArrayIndexOutOfBoundsException
// Eclipse Temurin 21 + kotest 6.0.0.M1 + kotlin 2.1.0 => TestTimeoutException
// Eclipse Temurin 21 + kotest 6.0.0.M1 + kotlin 2.0.21=> TestTimeoutException

**Comment by LeoColman** [comment]
Is this still an issue on Kotest 6?

**Comment by bliessens** [comment]
Problem do no longer occur with Kotest 6.0.5

**Comment by sksamuel** [comment]
Awesome!
