### ISSUE TITLE
shouldContainFile fails on JDK 8 with java.lang.NoSuchMethodError: java.util.stream.Stream.toList()Ljava/util/List

### ISSUE THREAD

**Issue by dittert** [kotest/kotest#4603]
This bug report is for Kotest version 5.9.1. My setup requires to use JDK 8 which causes `shouldContainFile` to behave unexpectedly.

Here is an example that shows the problem with a negated method call to save the boiler plate code required to create some file:

```kotlin
class Jdk8FailureSpec : FunSpec({
    val dir = tempdir()

    test("shouldContainFile succeeds for file objects") {
        // dir is of type file => test succeeds
        dir.shouldNotContainFile("file.txt")
    }

    test("shouldContainFile fails for path objects") {
        val aPath = dir.toPath()
        // aPath is of type path => test fails with exception
        aPath.shouldNotContainFile("file.txt")
    }
})
```

The call of `shouldNotContainFile` fails in the second test case with the following exception:

```stacktrace
java.lang.NoSuchMethodError: java.util.stream.Stream.toList()Ljava/util/List;
	at io.kotest.matchers.paths.PathsKt$containFile$1.test(paths.kt:162)
	at io.kotest.matchers.paths.PathsKt$containFile$1.test(paths.kt:160)
	at io.kotest.matchers.Matcher$DefaultImpls$invert$$inlined$invoke$1.test(Matcher.kt:188)
	at io.kotest.matchers.ShouldKt.invokeMatcher(should.kt:38)
	at io.kotest.matchers.ShouldKt.should(should.kt:33)
	at io.kotest.matchers.ShouldKt.shouldNot(should.kt:66)
	at io.kotest.matchers.paths.PathsKt.shouldNotContainFile(paths.kt:159)
	at example.Jdk8FailureSpec$1$2.invokeSuspend(Jdk8FailureSpec.kt:20)
	at example.Jdk8FailureSpec$1$2.invoke(Jdk8FailureSpec.kt)
	at example.Jdk8FailureSpec$1$2.invoke(Jdk8FailureSpec.kt)
	at io.kotest.core.spec.style.scopes.RootScopeKt$addTest$1.invokeSuspend(RootScope.kt:36)
	at io.kotest.core.spec.style.scopes.RootScopeKt$addTest$1.invoke(RootScope.kt)
	at io.kotest.core.spec.style.scopes.RootScopeKt$addTest$1.invoke(RootScope.kt)
	at io.kotest.engine.test.TestCaseExecutor$execute$innerExecute$1.invokeSuspend(TestCaseExecutor.kt:91)
	at io.kotest.engine.test.TestCaseExecutor$execute$innerExecute$1.invoke(TestCaseExecutor.kt)
        . . .  abbreviated for readability . . . 
```

Here is my `build.gradle.kts` file:

```kotlin
import org.jetbrains.kotlin.gradle.dsl.KotlinVersion

plugins {
    id("org.jetbrains.kotlin.jvm") version "2.1.0"
}

repositories {
    mavenCentral()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom:2.1.0"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.0")

    testImplementation("io.kotest:kotest-runner-junit5:5.9.1")
    testImplementation("io.kotest:kotest-assertions-core:5.9.1")
}

testing {
    suites {
        // Configure the built-in test suite
        @Suppress("UnstableApiUsage")
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter("5.11.0")
        }
    }
}


java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

kotlin {
    compilerOptions {
        jvmToolchain(8)
        languageVersion.set(KotlinVersion.KOTLIN_2_1)
    }
}
```

However, **both tests succeed** when I switch the toolchain to Java 21:

```kotlin
import org.jetbrains.kotlin.gradle.dsl.KotlinVersion

plugins {
    id("org.jetbrains.kotlin.jvm") version "2.1.0"
}

repositories {
    mavenCentral()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom:2.1.0"))

    implementation("org.jetbrains.kotlin:kotlin-stdlib:2.1.0")

    testImplementation("io.kotest:kotest-runner-junit5:5.9.1")
    testImplementation("io.kotest:kotest-assertions-core:5.9.1")
}

testing {
    suites {
        // Configure the built-in test suite
        @Suppress("UnstableApiUsage")
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter("5.11.0")
        }
    }
}


java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

kotlin {
    compilerOptions {
        jvmToolchain(21)
        languageVersion.set(KotlinVersion.KOTLIN_2_1)
    }
}
```

**Comment by dittert** [comment]
This problem was also discussed here: https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1733905492047069

**Comment by sksamuel** [comment]
They added this toList method to Stream in some recent JDK version. Need to find where we're using the non-JDK version and rename it.

**Comment by sksamuel** [comment]
This was fixed already in main actually, on commit 062f3840c959030449d369070145fe856b420392
It will be in the upcoming 6.0 release
