### ISSUE TITLE
Isn't there any plans to update?

### ISSUE THREAD

**Issue by vendelieu** [kotest/kotest#5350]
Seems like plugin is half dead and no plans to update, k2 already stable in IJ but plugin is giving strange bugs and working only half-baked :\

Specific test always giving me:
```kotlin
No matching tests found in any candidate test task.
    Requested tests:
        Test pattern com.example.MyTest.my test task :app:jvmTest
```

Ok, fine, can't run one test, but even running whole test class doing nothing :\

---

And such stacktrace for each startup:
```kotlin
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation. Dumb mode start trace is in attachment.
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:69)
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:65)
	at org.jetbrains.kotlin.analysis.api.impl.base.sessions.KaBaseSessionProvider.beforeEnteringAnalysis(KaBaseSessionProvider.kt:64)
	at org.jetbrains.kotlin.analysis.api.impl.base.sessions.KaBaseSessionProvider.beforeEnteringAnalysis(KaBaseSessionProvider.kt:47)
	at org.jetbrains.kotlin.analysis.api.fir.KaFirSessionProvider.beforeEnteringAnalysis(KaFirSessionProvider.kt:116)
	at io.kotest.plugin.intellij.psi.SuperClassesKt.getAllSuperClasses(superClasses.kt:56)
	at io.kotest.plugin.intellij.psi.SpecsKt.specStyle(specs.kt:52)
	at io.kotest.plugin.intellij.structure.KotestStructureViewExtension.getChildren(KotestStructureViewExtension.kt:24)
	at com.intellij.ide.structureView.impl.common.PsiTreeElementBase.mergeWithExtensions(PsiTreeElementBase.java:146)
	at com.intellij.ide.structureView.impl.common.PsiTreeElementBase.doGetChildren(PsiTreeElementBase.java:89)
	at com.intellij.ide.structureView.impl.common.PsiTreeElementBase.getChildrenWithoutCustomRegions(PsiTreeElementBase.java:79)
	at com.intellij.ide.navigationToolbar.StructureAwareNavBarModelExtension.childrenFromNodeAndProviders(StructureAwareNavBarModelExtension.kt:143)
	at com.intellij.ide.navigationToolbar.StructureAwareNavBarModelExtension.findParentInModel(StructureAwareNavBarModelExtension.kt:93)
	at com.intellij.ide.navigationToolbar.StructureAwareNavBarModelExtension.findParentInModel(StructureAwareNavBarModelExtension.kt:97)
	at com.intellij.ide.navigationToolbar.StructureAwareNavBarModelExtension.getParent(StructureAwareNavBarModelExtension.kt:79)
	at com.intellij.platform.navbar.backend.impl.DefaultNavBarItemProviderKt.parentFromOldExtensions(DefaultNavBarItemProvider.kt:125)
	at com.intellij.platform.navbar.backend.impl.DefaultNavBarItemProviderKt.access$parentFromOldExtensions(DefaultNavBarItemProvider.kt:1)
	at com.intellij.platform.navbar.backend.impl.DefaultNavBarItemProvider.findParent(DefaultNavBarItemProvider.kt:59)
	at com.intellij.platform.navbar.backend.impl.ImplKt.findParent(impl.kt:19)
	at com.intellij.platform.navbar.backend.impl.ImplKt.pathToItem$lambda$0(impl.kt:13)
	at kotlin.sequences.GeneratorSequence$iterator$1.calcNext(Sequences.kt:609)
	at kotlin.sequences.GeneratorSequence$iterator$1.hasNext(Sequences.kt:627)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:816)
	at com.intellij.platform.navbar.backend.impl.ImplKt.pathToItem(impl.kt:14)
	at com.intellij.platform.navbar.monolith.MonolithNavbarServiceDelegate.contextModel$lambda$1(MonolithNavBarServiceDelegate.kt:38)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:114)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable$lambda$4(InternalReadAction.kt:104)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2$lambda$1(cancellableReadAction.kt:32)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:351)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2(cancellableReadAction.kt:30)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:28)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:103)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:87)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:74)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$readLoop$1.invokeSuspend(InternalReadAction.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
```

**Comment by sksamuel** [comment]
Are you on this version ?

https://github.com/kotest/kotest/issues/5366#issuecomment-2475752320

**Comment by vendelieu** [comment]
yeah, is there any other more stable (not eap) version that support k2, how can I install it?

**Comment by sksamuel** [comment]
That should work.
I will be updating it to full K2 only this week though

**Comment by vendelieu** [comment]
great, thanks, isn't there any workaround/hack to make run tests, for now I'm just tossing from junit to kotest annotations since on my pc works only junit :(

**Comment by vendelieu** [comment]
`1.3.89-243-EAP-SNAPSHOT` version and still getting problem with starting specific test

**Comment by frayneposset** [comment]
FYI I'm still getting this error for version kotest 1.3.90-2024.3.1, with K2 enabled in IntelliJ.

**Comment by sksamuel** [comment]
@frayneposset are you still seeing issues ?

**Comment by frayneposset** [comment]
Yes, in a kotlin multiplatform project, tests in desktopTest can only be run individually. Trying to run the whole class' tests gives a no matching tests found in any candidate test task.

**Comment by tlusk** [comment]
@sksamuel if I click the gutter icon next to the class name (the one that looks like two overlapping arrows),  it creates a Gradle run configuration with `:module:my-module:test --tests "com.example.MyTest"` which gives no matching tests found.

If I right click the test name in the source code and pick `Run 'MyTest ...'` it creates a Kotest run configuration and the tests are found.

If I use the gutter icon next to any of the individual tests it creates a Kotest run configuration for that test and it works correctly.

Also if I right click on the entire `test` folder in the Project panel of the IDE and pick `Run 'tests in 'my-module...'` it creates a Gradle run configuration that has the same issue.


---------------------------------------------
EDIT: It looks like this happens if the tests are defined in a `context()` block and not `test()` block, but it looks like that might be an invalid test structure?

99% of my tests are using `AnnotationSpec` (where I was not seeing this issue), but I wanted to play around with the data driven testing `datatest` module but it seems incompatible with `AnnotationSpec`.  So I tried changing it to `FunSpec` which is where I ran into the issue above.

Changing `context()` to `test()` for tests that don't use `withData()` seems to fix the issues where the Gradle run configuration can't find the tests.

**Comment by sksamuel** [comment]
In 6.1 the "kotest" run producers have been superseded by the Gradle run producers.
This means this now works.
Please upgrade, and if you still see issues please reopen this ticket.
