### ISSUE TITLE
Use of deprecated API causes plugin crash

### ISSUE THREAD

**Issue by andriesfc** [kotest/kotest#5359]
After the latest update to IntelliJ (IDEA 2024.2 (Ultimate Edition)), a deprecation warning causes the IDE to crash with the following message: __com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon.__

**Plugin version:** `kotest-plugin-intellij (1.3.13-IC-2024.1.1)`

<details><summary>Details</summary>
<p>

**Stacktrace**:

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.kotest.plugin.intellij.toolwindow.FilterCallbacksAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: kotest-plugin-intellij]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```
</p>
</details>

**Comment by sksamuel** [comment]
This is fixed in the latest build which should be available for download tomorrow (pending jetbrains approval)
