### ISSUE TITLE
 `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon

### ISSUE THREAD

**Issue by esafak** [kotest/kotest#5362]
The plugin needs to be revised along the lines of https://github.com/bazelbuild/intellij/pull/6101:
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.kotest.plugin.intellij.actions.RunAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: kotest-plugin-intellij]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:200)
```

**Comment by sksamuel** [comment]
Updated in master, will be part of the next release.
Thanks for flagging.
