### ISSUE TITLE
KotlinIdeaResolutionException

### ISSUE THREAD

**Issue by theHacker** [kotest/kotest#5418]
For a while (could be since upgrading to stable IntelliJ 2022.1) IntelliJ stops syntax highlighting because of an exception in Kotest.
"Syntax highlighting has been temporarily turned off in file xxxx.kt because of an internal error"

Stacktrace:
```stacktrace
During querying provider io.kotest.plugin.intellij.linemarker.DisabledTestLineMarker@36cf73a6 (class io.kotest.plugin.intellij.linemarker.DisabledTestLineMarker)

org.jetbrains.kotlin.idea.caches.resolve.KotlinIdeaResolutionException: Kotlin resolution encountered a problem while analyzing KtTypeReference
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionFacadeWithDebugInfo.analyze(ResolutionFacadeWithDebugInfo.kt:43)
	at org.jetbrains.kotlin.idea.caches.resolve.ExtendedResolutionApiKt.analyze(extendedResolutionApi.kt:105)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.analyze(resolutionApi.kt:125)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.analyze$default(resolutionApi.kt:124)
	at io.kotest.plugin.intellij.psi.ClassesKt.getAllSuperClasses(classes.kt:50)
	at io.kotest.plugin.intellij.psi.SpecsKt.specStyle(specs.kt:74)
	at io.kotest.plugin.intellij.linemarker.DisabledTestLineMarker.markerForTest(DisabledTestLineMarker.kt:51)
	at io.kotest.plugin.intellij.linemarker.DisabledTestLineMarker.getLineMarkerInfo(DisabledTestLineMarker.kt:42)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:171)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:96)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:87)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:419)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:411)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:387)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:213)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:385)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.IllegalStateException: Cannot find entity for library with ID LibraryId(name=Gradle: kaptGeneratedClasses, tableId=ModuleLibraryTableId(moduleId=ModuleId(name=myprojectsname.main)))
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryBridgeImpl$librarySnapshotCached$1.invoke(LibraryBridgeImpl.kt:72)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryBridgeImpl$librarySnapshotCached$1.invoke(LibraryBridgeImpl.kt:44)
	at com.intellij.workspaceModel.storage.impl.ValuesCache.cachedValue(VersionedEntityStorageImpl.kt:26)
	at com.intellij.workspaceModel.storage.impl.VersionedEntityStorageImpl.cachedValue(VersionedEntityStorageImpl.kt:161)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryBridgeImpl.checkDisposed(LibraryBridgeImpl.kt:149)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryBridgeImpl.getLibrarySnapshot(LibraryBridgeImpl.kt:81)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryBridgeImpl.getFiles(LibraryBridgeImpl.kt:110)
	at org.jetbrains.kotlin.idea.caches.project.LibraryInfo.getLibraryRoots(IdeaModuleInfos.kt:303)
	at org.jetbrains.kotlin.idea.caches.project.ScriptDependenciesInfo$ForProject$Companion.gradleApiPresentInModule(ScriptModuleInfos.kt:127)
	at org.jetbrains.kotlin.idea.caches.project.ScriptDependenciesInfo$ForProject$Companion.createIfRequired(ScriptModuleInfos.kt:124)
	at org.jetbrains.kotlin.idea.caches.resolve.ProjectResolutionFacade.computeModuleResolverProvider(ProjectResolutionFacade.kt:123)
	at org.jetbrains.kotlin.idea.caches.resolve.ProjectResolutionFacade.access$computeModuleResolverProvider(ProjectResolutionFacade.kt:30)
	at org.jetbrains.kotlin.idea.caches.resolve.ProjectResolutionFacade$cachedValue$1.compute(ProjectResolutionFacade.kt:45)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at org.jetbrains.kotlin.idea.caches.resolve.ProjectResolutionFacade$cachedResolverForProject$1.invoke(ProjectResolutionFacade.kt:52)
	at org.jetbrains.kotlin.idea.caches.resolve.ProjectResolutionFacade$cachedResolverForProject$1.invoke(ProjectResolutionFacade.kt:30)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager.compute(LockBasedStorageManager.java:290)
	at org.jetbrains.kotlin.idea.caches.resolve.ProjectResolutionFacade.getCachedResolverForProject(ProjectResolutionFacade.kt:52)
	at org.jetbrains.kotlin.idea.caches.resolve.ProjectResolutionFacade.computeModuleResolverProvider(ProjectResolutionFacade.kt:111)
	at org.jetbrains.kotlin.idea.caches.resolve.ProjectResolutionFacade.access$computeModuleResolverProvider(ProjectResolutionFacade.kt:30)
	at org.jetbrains.kotlin.idea.caches.resolve.ProjectResolutionFacade$cachedValue$1.compute(ProjectResolutionFacade.kt:45)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at org.jetbrains.kotlin.idea.caches.resolve.ProjectResolutionFacade$cachedResolverForProject$1.invoke(ProjectResolutionFacade.kt:52)
	at org.jetbrains.kotlin.idea.caches.resolve.ProjectResolutionFacade$cachedResolverForProject$1.invoke(ProjectResolutionFacade.kt:30)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager.compute(LockBasedStorageManager.java:290)
	at org.jetbrains.kotlin.idea.caches.resolve.ProjectResolutionFacade.getCachedResolverForProject(ProjectResolutionFacade.kt:52)
	at org.jetbrains.kotlin.idea.caches.resolve.ProjectResolutionFacade.resolverForElement$kotlin_core(ProjectResolutionFacade.kt:141)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl.getFrontendService(ModuleResolutionFacadeImpl.kt:106)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl.analyze(ModuleResolutionFacadeImpl.kt:46)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionFacadeWithDebugInfo.analyze(ResolutionFacadeWithDebugInfo.kt:44)
	... 31 more
```

Kotest plugin: 1.1.50-IC-221-EAP-SNAPSHOT
IntelliJ: #IU-221.5080.210, built on April 12, 2022

**Comment by sksamuel** [comment]
Looks like some error in kapt triggering some IllegalStateException in kotest.

**Comment by jtonic** [comment]
Hi,

Recently I started to stumble upon this issue.

IntelliJ IDEA 2022.1.1 (Ultimate Edition)
Build #IU-221.5591.52, built on May 10, 2022
Runtime version: 11.0.14.1+1-b2043.45 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1

**kotest-plugin-intellij** (1.1.50-IC-221-EAP-SNAPSHOT)

**Kotlin**: 221-1.6.21-release-337-IJ5591.52

**Comment by henrik242** [comment]
I'm seeing the same thing. Has anyone figured it out?

**Comment by sksamuel** [comment]
The latest plugin should now be working with 221.

**Comment by theHacker** [comment]
I haven't seen the issue since. Maybe close this issue here?

**Comment by prashanthsridhar95** [comment]
I'm facing the same issue in Android Studio Flamingo (Canary build). Not able to work at all. No auto imports, no syntax correction, no auto suggestions.

**Comment by abhilash-alex** [comment]
I went to File > Repair IDE and went through 6 steps and it resolved the issue - I'm not sure if its a permanent fix though.
