### ISSUE TITLE
Does not work with Intellij 2021.2.x

### ISSUE THREAD

**Issue by vngantk** [kotest/kotest#5426]
I found that the plugin does not work with Intellij 2021.2.x. It cannot discover tests in a test spec. It works okay with 2021.1.x but not 2021.2.x.

**Comment by fipp** [comment]
Just got this with 2021.2.3 during/after upgrade of plugin:

```
com.intellij.diagnostic.PluginException: Short name 'ShouldBeInstanceOfInspection' is not unique
class 'io.kotest.plugin.intellij.inspections.ShouldBeInstanceOfInspection' in PluginDescriptor(name=Kotest, id=kotest-plugin-intellij, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/kotest-plugin-intellij, version=1.1.44-IC-2021.1, package=null)
and class 'io.kotest.plugin.intellij.inspections.ShouldBeInstanceOfInspection' in PluginDescriptor(name=Kotest, id=kotest-plugin-intellij, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/kotest-plugin-intellij, version=1.1.43-IC-2021.1, package=null)
conflict
	at com.intellij.codeInspection.ex.InspectionToolRegistrarKt.checkForDuplicateShortName(InspectionToolRegistrar.kt:176)
	at com.intellij.codeInspection.ex.InspectionToolRegistrarKt.registerInspection(InspectionToolRegistrar.kt:135)
	at com.intellij.codeInspection.ex.InspectionToolRegistrarKt.access$registerInspection(InspectionToolRegistrar.kt:1)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar$registerInspections$1.extensionAdded(InspectionToolRegistrar.kt:72)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar$registerInspections$1.extensionAdded(InspectionToolRegistrar.kt:70)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.notifyListeners(ExtensionPointImpl.java:785)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.lambda$registerExtensions$17(ExtensionPointImpl.java:985)
	at com.intellij.ide.plugins.DynamicPlugins$loadPlugin$1.run(DynamicPlugins.kt:820)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:936)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:808)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:790)
	at com.intellij.ide.plugins.PluginInstaller.installAndLoadDynamicPlugin(PluginInstaller.java:392)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.tryInstallWithoutRestart(PluginDownloader.java:351)
	at com.intellij.openapi.updateSettings.impl.PluginUpdateDialog$4.lambda$run$0(PluginUpdateDialog.java:198)
	at com.intellij.openapi.updateSettings.impl.UpdateInstaller.installDownloadedPluginUpdates(UpdateInstaller.kt:113)
	at com.intellij.openapi.updateSettings.impl.PluginUpdateDialog$4.lambda$run$1(PluginUpdateDialog.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

<img width="768" alt="image" src="https://user-images.githubusercontent.com/1716906/142827427-eb24c309-4b6a-4cef-826f-a6572f3a8cc5.png">

**Comment by irmen** [comment]
I just the same error as fipp above.  Kotest 1.1.44,  IntelliJ IDEA 2021.2.3

**Comment by sksamuel** [comment]
Looks like you have two versions of the plugin installed.

It says you have .1.44-IC-2021.1 and .1.43-IC-2021.1

**Comment by irmen** [comment]
Hm, I guess updating the plugin without restarting IDEA isn't a good idea then

**Comment by sksamuel** [comment]
Are you still seeing issues @irmen

**Comment by sksamuel** [comment]
Are you still seeing issues @vngantk

**Comment by irmen** [comment]
@sksamuel  no, I've cleaned out my old config folders and restarted the IDE.  It's working fine now. :+1:

**Comment by sksamuel** [comment]
Great
