### ISSUE TITLE
Kotest Intellij plugin issue with Clikt verion 3x

### ISSUE THREAD

**Issue by kdabir** [kotest/kotest#5474]
If a consuming project includes Clikt 3x, and I use the Kotest Intellij Plugin to execute test, I get this error. 
I am concluding this is Kotest Intellij plugin error as I can use Gradle to test my project successfully.

```
Exception in thread "main" java.lang.NoSuchMethodError: 'com.github.ajalt.clikt.parameters.options.OptionWithValues com.github.ajalt.clikt.parameters.options.OptionWithValuesKt.option$default(com.github.ajalt.clikt.core.ParameterHolder, java.lang.String[], java.lang.String, java.lang.String, boolean, java.lang.String, kotlin.text.Regex, java.util.Map, com.github.ajalt.clikt.completion.CompletionCandidates, int, java.lang.Object)'
	at io.kotest.engine.launcher.Execute.<init>(main.kt:34)
	at io.kotest.engine.launcher.MainKt.main(main.kt:24)
```

If you need any help to upgrade the project's Clikt version, I can raise a PR.

**Comment by sksamuel** [comment]
It's because the kotest engine uses clickt2 and there is a clash.
Kotest 4.3 which will be released this week no longer has a dependency on clickt to allow people to test projects that use clickt itself.

**Comment by kdabir** [comment]
Thanks @sksamuel for the quick update. I will wait for the 4.3 then. And a big thanks for kotest in general 🙏

**Comment by sksamuel** [comment]
Thank you for using it :+1:
