### ISSUE TITLE
Run single Test with 4.2.0.RC2 causes NoClassDefFoundError

### ISSUE THREAD

**Issue by huehnerlady** [kotest/kotest#5480]
Hi, 

In addition to kotest/kotest#5481 I get the following error when I try to run a single test in a Class:

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/kotest/core/filters/TestCaseFilter
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:642)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.kotest.launcher.ExecuteTestsKt.executeTests(executeTests.kt:37)
	at io.kotest.launcher.Execute.run(launcher.kt:71)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:168)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:16)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:258)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:255)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:273)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:298)
	at io.kotest.launcher.LauncherKt.main(launcher.kt:14)
Caused by: java.lang.ClassNotFoundException: io.kotest.core.filters.TestCaseFilter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 18 more
```

Running the whole test class works though.
I included:
```
  testImplementation("io.kotest:kotest-runner-junit5-jvm:4.2.0.RC2")
  testImplementation("io.kotest:kotest-core-jvm:4.2.0.RC2")
  testImplementation("io.kotest:kotest-assertions-core-jvm:4.2.0.RC2")
  testImplementation("io.kotest:kotest-property-jvm:4.2.0.RC2")
  testImplementation("io.kotest:kotest-extensions-spring:4.2.0.RC2")
```

Looking in the core-jvm dependency I can confirm that the class is not present, I can just see `Filter` and `TestFilter`

**Comment by sksamuel** [comment]
This is useful thanks. What's the stack trace when you only have 4.2.2 on
your build.

**Comment by Obirah** [comment]
I think this is the issue that was already discussed in https://github.com/kotest/kotest/issues/5485.

**Comment by sksamuel** [comment]
Confirmed working on slack with @huehnerlady
