### ISSUE TITLE
Cannot run single test when using with Kotest 4.2.0.RC2

### ISSUE THREAD

**Issue by Ultranium** [kotest/kotest#5486]
When I run a single test ("first test" in my code example) withing a test class using the green Run test in the gutter, the test fails with "java.lang.NoClassDefFoundError: io/kotest/core/filters/TestCaseFilter" exception.
Running all tests withing test class (using the double Run button in the gutter at the class declaration line) works fine.

**Code example:**

```
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

class TestMyClass : StringSpec({
    "first test" {
        2 * 2 shouldBe 4
    }
})
```

**Stack trace:**

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/kotest/core/filters/TestCaseFilter
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:642)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.kotest.launcher.ExecuteTestsKt.executeTests(executeTests.kt:37)
	at io.kotest.launcher.Execute.run(launcher.kt:71)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:168)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:16)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:258)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:255)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:273)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:298)
	at io.kotest.launcher.LauncherKt.main(launcher.kt:14)
Caused by: java.lang.ClassNotFoundException: io.kotest.core.filters.TestCaseFilter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 18 more
```

**Environment:**
- Plugin version: 1.1.9-IC-2020.1
- IntelliJ IDEA 2020.2 Ultimate Edition
- Kotest 4.2.0.RC2
- OpenJDK 14.0.2

**Comment by sksamuel** [comment]
Kotest 4.2.0 final has been released so upgrade to that.
And there is a kotest plugin update pending approval at jetbrains which will fix this issue, so once that gets released (today hopefully), you should be all set.

**Comment by Ultranium** [comment]
> Kotest 4.2.0 final has been released so upgrade to that.
> And there is a kotest plugin update pending approval at jetbrains which will fix this issue, so once that gets released (today hopefully), you should be all set.

Today I got the plugin update (not it's v. 1.1.11-IC-2020.1), switched to the final version 4.2.0
Things got even worse - now I can't run even all tests in the class using the gutter button - I get this error message:

```
Error: Unable to initialize main class io.kotest.launcher.LauncherKt
Caused by: java.lang.NoClassDefFoundError: io/kotest/core/engine/TestEngineListener
```

After reverting the Kotest version back to 4.2.0.RC2 with the latest plugin, it works as before - running all tests cases withing a class works, running a single test does not.

I created a repo with a minimal project to demonstrate this behavior - https://github.com/Ultranium/kotest-idea-plugin-bug
It contains only a single test class in the file src/test/kotlin/TestMyClass.kt.

**Comment by sksamuel** [comment]
That's not the latest plugin, that's the one released last week.
It's confusing because there's a lag where you have to wait for jetbrains
to approve uploads to the plugin repository.

**Comment by sksamuel** [comment]
[kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2020.1.zip](https://github.com/kotest/kotest-intellij-plugin/files/5103001/kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2020.1.zip)

^^ that is the latest if you want to install manually.

**Comment by Ultranium** [comment]
> [kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2020.1.zip](https://github.com/kotest/kotest-intellij-plugin/files/5103001/kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2020.1.zip)
> 
> ^^ that is the latest if you want to install manually.

I installed the plugin you provided and now everything works perfect.
Thank you!

**Comment by sksamuel** [comment]
Awesome.

**Comment by rkim-branch** [comment]
I am having similar variation of problem.

```
Exception in thread "main" java.lang.NoSuchMethodError: com.github.ajalt.clikt.parameters.options.OptionWithValuesKt.option$default(Lcom/github/ajalt/clikt/core/ParameterHolder;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;Lkotlin/text/Regex;Ljava/util/Map;Lcom/github/ajalt/clikt/completion/CompletionCandidates;ILjava/lang/Object;)Lcom/github/ajalt/clikt/parameters/options/OptionWithValues;
	at io.kotest.engine.launcher.Execute.<init>(main.kt:34)
	at io.kotest.engine.launcher.MainKt.main(main.kt:24)
```
It used to work fine, until I have upgrade clikt to 3.x from 2.x. As kotest-framework depends on clikt@2.x, IntelliJ plugin was not able to find matching bytecode symbol from 3.x jar.

**Comment by sksamuel** [comment]
Yes, if you are using clikt in your own project, it will clash with the
plugin.
I will have to remove usage of clikt from the plugin to avoid these clashes.

**Comment by th-jtullgren** [comment]
Is the new plugin approved yet? I am still only getting 1.1.36-IC-2020.2 to show up.

**Comment by sksamuel** [comment]
That is the latest version from a couple of months ago. Are you having some issues @th-jtullgren

**Comment by th-jtullgren** [comment]
@sksamuel I was seeing this issue even after uninstalling and reinstalling the plugin in Android Studio.  I went through some actions that seemed to clear it up. It might have been a download cache issue.  Thanks for letting me know!
