### ISSUE TITLE
StackOverflowError @SpecsKt.enclosingSpec()

### ISSUE THREAD

**Issue by theHacker** [kotest/kotest#5492]
Found this exception in "IDE Fatal Errors":
```stacktrace
java.lang.StackOverflowError
	at com.intellij.openapi.progress.impl.CoreProgressManager.runCheckCanceledHooks(CoreProgressManager.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:132)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:227)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:49)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getGreenStub(StubBasedPsiElementBase.java:373)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getStubOrPsiChild(StubBasedPsiElementBase.java:383)
	at org.jetbrains.kotlin.psi.KtClassOrObject.getSuperTypeList(KtClassOrObject.kt:38)
	at org.jetbrains.kotlin.psi.KtClassOrObject.getSuperTypeListEntries(KtClassOrObject.kt:40)
	at io.kotest.plugin.intellij.psi.ClassesKt.getSuperClassSimpleName(classes.kt:36)
	at io.kotest.plugin.intellij.psi.SpecsKt.specStyle(specs.kt:51)
	at io.kotest.plugin.intellij.psi.SpecsKt.isSubclassOfSpec(specs.kt:36)
	at io.kotest.plugin.intellij.psi.SpecsKt.enclosingSpec(specs.kt:227)
	at io.kotest.plugin.intellij.psi.SpecsKt.enclosingSpec(specs.kt:228)
	at io.kotest.plugin.intellij.psi.SpecsKt.enclosingSpec(specs.kt:228)
	at io.kotest.plugin.intellij.psi.SpecsKt.enclosingSpec(specs.kt:228)
	at io.kotest.plugin.intellij.psi.SpecsKt.enclosingSpec(specs.kt:228)
	at io.kotest.plugin.intellij.psi.SpecsKt.enclosingSpec(specs.kt:228)
	at io.kotest.plugin.intellij.psi.SpecsKt.enclosingSpec(specs.kt:228)
....
```

Kotest Plugin: 1.0.5
Kotlin Plugin: 1.4-M3-release-IJ20202.2-1
IntelliJ: #IU-202.5792.28, built on June 18, 2020

**Comment by sksamuel** [comment]
This is fixed in latest plugin (you should have received an updated prompt).
