### ISSUE TITLE
Getting Test Framework Quit Unexpectedly when running Kotest from the latest plugin 0.90.16, IntelliJ version 2020.1.1 (Ultimate Edition)

### ISSUE THREAD

**Issue by revanthpobala** [kotest/kotest#5505]
IDE:
IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 29, 2020
Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4

Kotest Plugin version -- 0.90.16

I have a bunch of Kotest written and I am getting the following exception when I try to run them from the Kotest plugin. 

Kotest dependencies:

```
 <!-- https://mvnrepository.com/artifact/io.kotest/kotest-runner-console-jvm -->
        <dependency>
            <groupId>io.kotest</groupId>
            <artifactId>kotest-runner-console-jvm</artifactId>
            <version>4.0.5</version>
        </dependency>
        <dependency>
            <groupId>io.kotest</groupId>
            <artifactId>kotest-runner-junit5-jvm</artifactId>
            <version>${kotest.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.kotest</groupId>
            <artifactId>kotest-property-jvm</artifactId>
            <version>${kotest.version}</version>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/io.kotest/kotest-core-jvm -->
        <dependency>
            <groupId>io.kotest</groupId>
            <artifactId>kotest-core-jvm</artifactId>
            <version>${kotest.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.kotest</groupId>
            <artifactId>kotest-assertions-core-jvm</artifactId>
            <version>4.0.5</version>
            <scope>test</scope>
        </dependency>
```

The error I am getting is 

```
Exception in thread "main" java.lang.NoSuchMethodError: 'void io.kotest.core.engine.KotestEngine.<init>(java.util.List, java.util.List, int, io.kotest.core.Tags, io.kotest.core.engine.TestEngineListener, java.util.List, int, kotlin.jvm.internal.DefaultConstructorMarker)'
	at io.kotest.runner.console.KotestConsoleRunner.execute(KotestConsoleRunner.kt:30)
	at io.kotest.runner.console.Execute.run(launcher.kt:66)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:154)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:252)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:249)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:267)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:290)
	at io.kotest.runner.console.LauncherKt.main(launcher.kt:14)

```

**Comment by sksamuel** [comment]
Are you using the latest kotest snapshot?

**Comment by revanthpobala** [comment]
I downloaded this plugin https://plugins.jetbrains.com/plugin/14080-kotest/update/84840 and my kotest and kotlin versions are

```
<kotlin.version>1.3.70</kotlin.version>
<kotest.version>4.0.0-BETA1</kotest.version>
```

**Comment by LeoColman** [comment]
Could you please try with the latest Kotest snapshot version?
Currently it's 4.1.0.297-SNAPSHOT

**Comment by revanthpobala** [comment]
@Kerooker  Sorry, my company's artifactory does not have that version.

**Comment by sksamuel** [comment]
If you can't use snapshots then you'll need to wait for 4.1 final and
kotest plugin 1.0 final.

**Comment by revanthpobala** [comment]
Thanks

**Comment by sksamuel** [comment]
They will be released in the next couple of weeks.
