### ISSUE TITLE
Exception with intellijs handling of junit4

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#5511]
```
com.intellij.psi.stubs.UpToDateStubIndexMismatch: PSI and index do not match.
Please report the problem to JetBrains with the files attached
INDEXED VERSION IS THE CURRENT ONE file=KtFile: FunSpec.class, file.class=class org.jetbrains.kotlin.idea.decompiler.classFile.KtClsFile, file.lang=Language: kotlin, modStamp=1
 AST INCONSISTENT, perhaps after incremental reparse; KtFile: FunSpec.class
 stub debugInfo=created in getStubTree(), with AST = false; with backReference
latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=PsiJetFileStubImpl[package=io.kotest.core.spec.style]}550919528
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=org.jetbrains.kotlin.idea.decompiler.KotlinDecompiledFileViewProvider{myVirtualFile=jar:///home/sam/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-core-jvm/4.1.0.279-SNAPSHOT/bf0fa870d0d7032465ceecd52506f3b4e604c6a6/kotest-core-jvm-4.1.0.279-SNAPSHOT.jar!/io/kotest/core/spec/style/FunSpec.class, content=VirtualFileContent{size=4851}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1588435807449; file length: 4851
 doc saved: true; doc stamp: 0; doc size: 948; committed: true
indexing info: indexed at 1588435807449 with document  byte size = 4851, char size = -1
	at com.intellij.psi.stubs.StubTreeLoader.handleUpToDateMismatch(StubTreeLoader.java:134)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:127)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:201)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:149)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:213)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:712)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:917)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:49)
	at com.intellij.psi.AbstractFileViewProvider.findElementAt(AbstractFileViewProvider.java:246)
	at com.intellij.psi.AbstractFileViewProvider.findElementAt(AbstractFileViewProvider.java:217)
	at com.intellij.psi.util.PsiTreeUtil.findElementOfClassAtRange(PsiTreeUtil.java:996)
	at org.jetbrains.kotlin.idea.decompiler.KtDecompiledFile.getDeclaration(KtDecompiledFile.kt:38)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledElementKt.findDeclarationInCompiledFile(LightMemberOriginForCompiledElement.kt:129)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledElementKt.access$findDeclarationInCompiledFile(LightMemberOriginForCompiledElement.kt:1)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledMethod$originalElement$2.invoke(LightMemberOriginForCompiledElement.kt:100)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledMethod$originalElement$2.invoke(LightMemberOriginForCompiledElement.kt:81)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LightMemberOriginForCompiledMethod.getOriginalElement(LightMemberOriginForCompiledElement.kt)
	at org.jetbrains.kotlin.asJava.elements.KtLightMemberImpl.getKotlinOrigin(KtLightMemberImpl.kt:62)
	at org.jetbrains.kotlin.asJava.elements.KtLightMemberImpl.getKotlinOrigin(KtLightMemberImpl.kt:35)
	at org.jetbrains.kotlin.idea.run.KotlinMultiplatformJUnitRecognizer.isTestAnnotated(KotlinMultiplatformJUnitRecognizer.kt:40)
	at com.intellij.execution.JUnitRecognizer.lambda$willBeAnnotatedAfterCompilation$0(JUnitRecognizer.java:14)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.lambda$findFirstSafe$0(ExtensionProcessingHelper.java:34)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:45)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.findFirstSafe(ExtensionProcessingHelper.java:34)
	at com.intellij.openapi.extensions.ExtensionPointName.findFirstSafe(ExtensionPointName.java:55)
	at com.intellij.execution.JUnitRecognizer.willBeAnnotatedAfterCompilation(JUnitRecognizer.java:14)
	at com.intellij.execution.junit.JUnitUtil.isExplicitlyTestAnnotated(JUnitUtil.java:345)
	at com.intellij.execution.junit.JUnitUtil.hasTestOrSuiteMethods(JUnitUtil.java:201)
	at com.intellij.execution.junit.JUnitUtil.lambda$isTestClass$0(JUnitUtil.java:195)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:64)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at com.intellij.execution.junit.JUnitUtil.isTestClass(JUnitUtil.java:194)
	at com.intellij.execution.junit2.inspection.JUnitEntryPoint.isEntryPoint(JUnitEntryPoint.java:40)
	at com.intellij.codeInspection.deadCode.UnusedDeclarationInspectionBase.isEntryPoint(UnusedDeclarationInspectionBase.java:344)
	at org.jetbrains.kotlin.idea.inspections.UnusedSymbolInspection$Companion.isEntryPoint(UnusedSymbolInspection.kt:132)
	at org.jetbrains.kotlin.idea.inspections.UnusedSymbolInspection$buildVisitor$1.invoke(UnusedSymbolInspection.kt:223)
	at org.jetbrains.kotlin.idea.inspections.UnusedSymbolInspection$buildVisitor$1.invoke(UnusedSymbolInspection.kt:91)
	at org.jetbrains.kotlin.psi.VisitorWrappersKt$namedDeclarationVisitor$1.visitNamedDeclaration(VisitorWrappers.kt:393)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedDeclaration(KtVisitorVoid.java:965)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedDeclaration(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtVisitor.visitClassOrObject(KtVisitor.java:41)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitClassOrObject(KtVisitorVoid.java:37)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitClassOrObject(KtVisitorVoid.java:465)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitClassOrObject(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtVisitor.visitClass(KtVisitor.java:33)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitClass(KtVisitorVoid.java:33)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitClass(KtVisitorVoid.java:459)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitClass(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtClass.accept(KtClass.kt:20)
	at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:59)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:77)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:64)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:306)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$3(LocalInspectionsPass.java:274)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:154)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:146)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$4(LocalInspectionsPass.java:271)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:125)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:114)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:271)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:148)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.AssertionError: Stub count doesn't match stubbed node length
	at com.intellij.psi.impl.source.FileTrees.lambda$reconcilePsi$5(FileTrees.java:189)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:574)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:182)
	... 83 more
```

**Comment by sksamuel** [comment]
```
com.intellij.psi.stubs.UpToDateStubIndexMismatch: PSI and index do not match.
Please report the problem to JetBrains with the files attached
INDEXED VERSION IS THE CURRENT ONE file=KtFile: BehaviorSpec.class, file.class=class org.jetbrains.kotlin.idea.decompiler.classFile.KtClsFile, file.lang=Language: kotlin, modStamp=1
 AST INCONSISTENT, perhaps after incremental reparse; KtFile: BehaviorSpec.class
 stub debugInfo=created in getStubTree(), with AST = false; with backReference
latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=PsiJetFileStubImpl[package=io.kotest.core.spec.style]}267665034
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=org.jetbrains.kotlin.idea.decompiler.KotlinDecompiledFileViewProvider{myVirtualFile=jar:///home/sam/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-core-jvm/4.1.0.283-SNAPSHOT/ef026bd32c16c8c908983df880699a52948fc094/kotest-core-jvm-4.1.0.283-SNAPSHOT.jar!/io/kotest/core/spec/style/BehaviorSpec.class, content=VirtualFileContent{size=4585}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1589033669137; file length: 4585
 doc saved: true; doc stamp: 0; doc size: 963; committed: true
indexing info: indexed at 1589033669137 with document  byte size = 4585, char size = -1
	at com.intellij.psi.stubs.StubTreeLoader.handleUpToDateMismatch(StubTreeLoader.java:134)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:127)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:201)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:149)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:213)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:712)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:142)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getText(ASTDelegatePsiElement.java:146)
	at org.jetbrains.kotlin.idea.projectView.KtDeclarationTreeNode.updateImpl(KtDeclarationTreeNode.java:87)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$doUpdate$1(AbstractPsiBasedNode.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:791)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.doUpdate(AbstractPsiBasedNode.java:139)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$update$0(AbstractPsiBasedNode.java:135)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:167)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:125)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:114)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:109)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:135)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:76)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:28)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:451)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:433)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:425)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:419)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:389)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:300)
	at com.intellij.ui.tree.StructureTreeModel$Node.isLeaf(StructureTreeModel.java:554)
	at com.intellij.ui.tree.StructureTreeModel$Node.access$400(StructureTreeModel.java:419)
	at com.intellij.ui.tree.StructureTreeModel.isLeaf(StructureTreeModel.java:336)
	at com.intellij.ui.tree.AsyncTreeModel.getLeafState(AsyncTreeModel.java:444)
	at com.intellij.ui.tree.AsyncTreeModel.access$1800(AsyncTreeModel.java:42)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.load(AsyncTreeModel.java:615)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:588)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:481)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:447)
	at com.intellij.util.concurrency.Command$Processor.lambda$process$1(Command.java:48)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:73)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:191)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:158)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:473)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:217)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.AssertionError: Stub count doesn't match stubbed node length
	at com.intellij.psi.impl.source.FileTrees.lambda$reconcilePsi$5(FileTrees.java:189)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:574)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:182)
	... 57 more
```
