### ISSUE TITLE
Problem running Kotlintest's own tests with Kotlintest Plugin

### ISSUE THREAD

**Issue by lenalebt** [kotest/kotest#5540]
Hi,
I am using IntelliJ 2019.1.1 (191.6707.61) Community Edition with the Kotlintest plugin 3.3.0.11. I opened the Kotlintest source and wanted to run all of the Tests in `com/sksamuel/kotlintest/properties/GenTest.kt`.

I then get this stack trace:

```
Testing started at 13:18 ...
/usr/lib/jvm/java-8-openjdk-amd64/bin/java -javaagent:/home/lena/bin/install/idea-IC-182.4892.20/lib/idea_rt.jar=35021:/home/lena/bin/install/idea-IC-182.4892.20/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/java-atk-wrapper.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar:/home/lena/Projects/Programming/Kotlin/kotlintest/kotlintest-tests/kotlintest-tests-core/build/classes/kotlin/jvm/test:/home/lena/.gradle/caches/modules-2/files-2.1/org.objenesis/objenesis/2.6/639033469776fd37c08358c6b92a4761feb2af4b/objenesis-2.6.jar:/home/lena/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.9.7/8e7d1b599f4943851ffea125fd9780e572727fc0/byte-buddy-agent-1.9.7.jar:/home/lena/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy/1.9.7/8fea78fea6449e1738b675cb155ce8422661e237/byte-buddy-1.9.7.jar:/home/lena/.gradle/caches/modules-2/files-2.1/io.kindedj/kindedj/1.1.0/462731347602a3f24e3f21feec50928f9a657741/kindedj-1.1.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-commons/1.4.0/e0b2ed8fac32ad6469d75d034e759f1969db8dda/junit-platform-commons-1.4.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.opentest4j/opentest4j/1.1.1/efd9f971e91074491ea55b19f67b13470cf4fcdd/opentest4j-1.1.1.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.3.21/f30e4a9897913e53d778f564110bafa1fef46643/kotlin-stdlib-common-1.3.21.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-core/2.24.0/969a7bcb6f16e076904336ebc7ca171d412cc1f9/mockito-core-2.24.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.11.2/f5e9a2ffca496057d6891a3de65128efc636e26e/log4j-api-2.11.2.jar:/home/lena/.gradle/caches/modules-2/files-2.1/io.arrow-kt/arrow-effects-extensions/0.9.0/a4bdb77deda85f061e86eb4cf049e3950ab4851a/arrow-effects-extensions-0.9.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/io.arrow-kt/arrow-effects-data/0.9.0/529dba1316ac337f84d2171e687c54e730562581/arrow-effects-data-0.9.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/io.arrow-kt/arrow-core-extensions/0.9.0/65d17b5579460a0322adc4701434564fc5702271/arrow-core-extensions-0.9.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/io.arrow-kt/arrow-extras-data/0.9.0/330d69f521d7d70f6820cb27c0fe1d39360cd6a/arrow-extras-data-0.9.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/io.arrow-kt/arrow-typeclasses/0.9.0/48e40dc83d4485f2ded9dad56e51cb53cd8fa348/arrow-typeclasses-0.9.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-launcher/1.4.0/5cc8b7b305ffc79aa124a1a4fe5efab114f28cac/junit-platform-launcher-1.4.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-suite-api/1.4.0/8c03ee0615180d219c2dac86b004bd5d32b5649c/junit-platform-suite-api-1.4.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/io.arrow-kt/arrow-annotations/0.9.0/dbe68fdc10ca581836c36f34c1c3fb69455031ef/arrow-annotations-0.9.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.eclipse.jgit/org.eclipse.jgit/4.4.1.201607150455-r/63998ced66e425d9e8bcd0c59f710c98f0c021ff/org.eclipse.jgit-4.4.1.201607150455-r.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-common/1.1.1/7ed04382bdf0c89c5d87ac462aa4935ae8e85243/kotlinx-coroutines-core-common-1.1.1.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-api/5.4.0/1a09f25a160f71c267f9ebe3b229b17805c683e9/junit-jupiter-api-5.4.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-engine/1.4.0/b4419dc190a5d82b9cac6b52e0af9140895c3f87/junit-platform-engine-1.4.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.apiguardian/apiguardian-api/1.0.0/3ef5276905e36f4d8055fe3cb0bdcc7503ffc85d/apiguardian-api-1.0.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.3.21/d207ce2c9bcf17dc8e51bab4dbfdac4d013e7138/kotlin-stdlib-jdk7-1.3.21.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.3.21/4bcc2012b84840e19e1e28074284cac908be0295/kotlin-stdlib-1.3.21.jar:/home/lena/.gradle/caches/modules-2/files-2.1/com.nhaarman/mockito-kotlin/1.6.0/5709f219f7bbe2022fe3f0495282ca8745ddc310/mockito-kotlin-1.6.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-slf4j-impl/2.11.2/4d44e4edc4a7fb39f09b95b09f560a15976fa1ba/log4j-slf4j-impl-2.11.2.jar:/home/lena/.gradle/caches/modules-2/files-2.1/io.arrow-kt/arrow-effects-io-extensions/0.9.0/860b206042c64b79fc9aa10b06168b7febfb401/arrow-effects-io-extensions-0.9.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/io.arrow-kt/arrow-generic/0.9.0/2cd853f0c13caeb563a317851f99e7b4969f39ae/arrow-generic-0.9.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/io.arrow-kt/arrow-validation/0.9.0/6191da1f79bdf14fcb80a807d85ecfa2658ae89f/arrow-validation-0.9.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/io.arrow-kt/arrow-extras-extensions/0.9.0/59780a92fc0ff114f48e342e50cbb723ea5cfc79/arrow-extras-extensions-0.9.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.25/da76ca59f6a57ee3102f8f9bd9cee742973efa8a/slf4j-api-1.7.25.jar:/home/lena/.gradle/caches/modules-2/files-2.1/io.arrow-kt/arrow-core-data/0.9.0/a5b0228eebd5ee2f233f9aa9b9b624a32f84f328/arrow-core-data-0.9.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/com.github.wumpz/diffutils/2.2/647f913ef6c350d3b1bc1ffa48a74747a13e89f/diffutils-2.2.jar:/home/lena/.gradle/caches/modules-2/files-2.1/com.univocity/univocity-parsers/2.8.1/aa34369bc8766909a5633ce29eaba601e8e2e899/univocity-parsers-2.8.1.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core/1.1.1/3d2b7321cdef9ebf9cb7729ea4f75a6f6457df86/kotlinx-coroutines-core-1.1.1.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.3.21/d0d5ff2ac2ebd8a42697af41e20fc225a23c5d3b/kotlin-reflect-1.3.21.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-engine/5.4.0/30083adf3fbd7b734f12e6cb4d99dedab99fc34b/junit-jupiter-engine-5.4.0.jar:/home/lena/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.3.21/d0634d54452abc421db494ad32dd215e6591c49f/kotlin-stdlib-jdk8-1.3.21.jar:/home/lena/Projects/Programming/Kotlin/kotlintest/kotlintest-assertions/kotlintest-assertions-arrow/build/classes/kotlin/jvm/main:/home/lena/Projects/Programming/Kotlin/kotlintest/kotlintest-runner/kotlintest-runner-junit5/out/production/classes:/home/lena/Projects/Programming/Kotlin/kotlintest/kotlintest-runner/kotlintest-runner-junit5/out/production/resources:/home/lena/Projects/Programming/Kotlin/kotlintest/kotlintest-assertions/build/classes/kotlin/jvm/main:/home/lena/Projects/Programming/Kotlin/kotlintest/kotlintest-core/build/classes/kotlin/jvm/main:/home/lena/.IdeaIC2019.1/config/plugins/kotlintest-plugin-intellij/lib/kotlintest-runner-console-3.3.1.jar:/home/lena/.IdeaIC2019.1/config/plugins/kotlintest-plugin-intellij/lib/argparse4j-0.8.1.jar io.kotlintest.runner.console.LauncherKt --spec com.sksamuel.kotlintest.properties.GenTest
Exception in thread "main" java.lang.NoClassDefFoundError: io/kotlintest/runner/jvm/TestEngineListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.kotlintest.runner.console.KotlinTestConsoleRunner.execute(KotlinTestConsoleRunner.kt:11)
	at io.kotlintest.runner.console.LauncherKt.main(launcher.kt:17)
Caused by: java.lang.ClassNotFoundException: io.kotlintest.runner.jvm.TestEngineListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more

Process finished with exit code 1
```

Unsure where this comes from - ideas welcome :).

This happened when I was playing with some things I think are missing to `Gen` in Kotlintest, wanted to open a PR later on over there.

Cheers,
Lena

**Comment by LeoColman** [comment]
I think the issue we might be facing here is that we're currently moving KT to MultiPlatform, and currently we can't exactly run tests on the master branch. I'm getting this fixed ASAP.

Is that what you're trying to do?

**Comment by lenalebt** [comment]
Okay, wow, that's it. I ran it on 3.3.2 and it works. Did not think that this error message indicates a problem like that.
That really helped - I thought about filing an issue on kotlintest itself since I was not able to run tests on the master and thought I'd then try the plugin to run them directly.

Thanks for your help :).
