### ISSUE TITLE
Output error with table testing

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#5546]
```
##teamcity[testFailed name='should parse the short correctly' message='
The following 2 assertions failed:
1) Test failed for (buf, [B@3c58a3ab), (expectedShort, 0) with error foo
	at com.sksamuel.kotlintest.ByteArrayExtensionsKtTest$1$1.invokeSuspend(ByteArrayExtensionsKtTest.kt:46)
2) Test failed for (buf, [B@6d4de033), (expectedShort, -1) with error foo
	at com.sksamuel.kotlintest.ByteArrayExtensionsKtTest$1$1.invokeSuspend(ByteArrayExtensionsKtTest.kt:46)
']
```

**Comment by sksamuel** [comment]
Seems like intellij doesn't like messages over multiple lines.
