### ISSUE TITLE
Kotlintest 3.2.0+ makes my Gradle `build` task hangs or `GC overhead limit exceeded`

### ISSUE THREAD

**Issue by elect86** [kotest/kotest#610]
As titled, project at this [commit](https://github.com/kotlin-graphics/gli/commit/1a950ae926ffa26dddc52b0b1f1affec3580e53f)

with 3.1.11 no issues at all

**Comment by sksamuel** [comment]
Changing rem to cap breaks it ?

**Comment by LeoColman** [comment]
Why the empty test logging?

**Comment by elect86** [comment]
@sksamuel that fixed some tests

@Kerooker what do you mean?

**Comment by LeoColman** [comment]
There is an empty testLogging block

**Comment by elect86** [comment]
ah, I used [this](https://github.com/kotlin-graphics/gli/blob/master/build.gradle#L79) to print out normals stream outputs and wanted to keep it to avoid a future search

**Comment by LeoColman** [comment]
Maybe comment the block too? I'm wild guessinh that perhaps it's part of thr issue, maybe gradle is failing to resolve something.

Just guessing because we haven't had any reports similar to this so far

**Comment by elect86** [comment]
No success

```
> Task :compileJava NO-SOURCE
> Task :processResources
> Task :classes
> Task :inspectClassesForKotlinIC
> Task :jar
> Task :javadoc NO-SOURCE
> Task :javadocJar
> Task :sourcesJar
> Task :assemble
> Task :discoverTestScriptsExtensions
> Task :compileTestKotlin
Compilation with Kotlin compile daemon was not successful
java.lang.Exception: Java heap space
	at org.jetbrains.kotlin.daemon.common.CompileService$CallResult$Error.get(CompileService.kt:60)
	at org.jetbrains.kotlin.daemon.common.CompileService$CallResult$Error.get(CompileService.kt:59)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.compileWithDaemon(GradleKotlinCompilerRunner.kt:221)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.compileWithDaemonOrFallback(GradleKotlinCompilerRunner.kt:166)
Could not connect to kotlin daemon. Using fallback strategy.
```

Could you give it a try on your machine?

**Comment by LeoColman** [comment]
Clone th e repository and did `./gradlew clean test`.

Flawless build

**Comment by LeoColman** [comment]
I'm not sure this is on our end, @elect86 

Maybe you're not giving gradle enough memory on your machine?

**Comment by elect86** [comment]
I have the very same behaviour on two machine, at work and at home

I'm trying right now on console (I always run through Idea) and it's the same.. it hangs on


<========-----> 63% EXECUTING [1m 30s]
> :compileTestKotlin

Ps: did you changed `kotlintest_version` to `3.2.0` before running?

**Comment by elect86** [comment]
I have the very same behaviour on two machine, at work and at home

I'm trying right now on console (I always run through Idea) and it's the same.. it hangs on

```
<========-----> 63% EXECUTING [1m 30s]
> :compileTestKotlin
```

Ps: did you changed `kotlintest_version` to `3.2.0` before running?

And then

```
Cause: Java heap space
Element is unknownThe root cause was thrown at: HashSet.java:106
        at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.java:88)
        at org.jetbrains.kotlin.codegen.FunctionCodegen.endVisit(FunctionCodegen.java:992)
        ... 97 more
Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by sksamuel** [comment]
I'm trying it now.

```
sam@sam-hp:~/development/workspace/kotlintest$ git clone git@github.com:kotlin-graphics/gli.git
Cloning into 'gli'...
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 2119 (delta 28), reused 50 (delta 19), pack-reused 2046
Receiving objects: 100% (2119/2119), 8.99 MiB | 1.09 MiB/s, done.
Resolving deltas: 100% (1183/1183), done.
sam@sam-hp:~/development/workspace/kotlintest$ cd gli/
sam@sam-hp:~/development/workspace/kotlintest/gli$ git checkout 1a950ae926ffa26dddc52b0b1f1affec3580e53f
Note: checking out '1a950ae926ffa26dddc52b0b1f1affec3580e53f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 1a950ae - fixed a couple of assertions after the removal of ByteBuffer.size - kotlintest issue
sam@sam-hp:~/development/workspace/kotlintest/gli$ ./gradlew test
```

**Comment by sksamuel** [comment]
```Starting a Gradle Daemon (subsequent builds will be faster)
w: /home/sam/development/workspace/kotlintest/gli/src/main/kotlin/gli_/saveKtx.kt: (71, 13): The value 'glm.ceilMultiple(imageSize, 4)' assigned to 'var imageSize: Int defined in gli_.saveKtx.saveKtx' is never used
w: /home/sam/development/workspace/kotlintest/gli/src/main/kotlin/gli_/tga/image reader.kt: (116, 17): Variable 'imageType' is never used
w: /home/sam/development/workspace/kotlintest/gli/src/test/kotlin/gli_/coreLoadImage.kt: (13, 17): Variable 'textureTga' is never used
w: /home/sam/development/workspace/kotlintest/gli/src/test/kotlin/gli_/coreTexture2d.kt: (74, 17): Variable 'textureB' is never used
w: /home/sam/development/workspace/kotlintest/gli/src/test/kotlin/gli_/coreTexture2d.kt: (119, 21): Variable 'orange' is never used
w: /home/sam/development/workspace/kotlintest/gli/src/test/kotlin/gli_/coreTexture2d.kt: (129, 21): Variable 'texture' is never used
w: /home/sam/development/workspace/kotlintest/gli/src/test/kotlin/gli_/coreTexture3d.kt: (58, 21): Variable 'orange' is never used
w: /home/sam/development/workspace/kotlintest/gli/src/test/kotlin/gli_/coreTextureCube.kt: (63, 21): Variable 'textureCube' is never used
w: /home/sam/development/workspace/kotlintest/gli/src/test/kotlin/gli_/coreTextureCubeArray.kt: (66, 21): Variable 'colors' is never used
w: /home/sam/development/workspace/kotlintest/gli/src/test/kotlin/gli_/size.kt: (140, 21): Variable 'blockCountA' is never used
w: /home/sam/development/workspace/kotlintest/gli/src/test/kotlin/gli_/size.kt: (142, 21): Variable 'blockCountB' is never used

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 3m 58s
```

**Comment by elect86** [comment]
that commit has the working `1.3.11`

I pushed on branch [`bug`](https://github.com/kotlin-graphics/gli/tree/bug), either change manually the kotlintest version in `build.gradle` or clone this

**Comment by sksamuel** [comment]
Same error.
Seems like a bug in Kotlin itself.

```java.lang.IllegalStateException: Backend Internal error: Exception during code generation
Cause: Back-end (JVM) Internal error: wrong code generated
org.jetbrains.kotlin.codegen.CompilationException Back-end (JVM) Internal error: Couldn't transform method node:
invokeSuspend (Ljava/lang/Object;)Ljava/lang/Object;:
  @Lorg/jetbrains/annotations/Nullable;() // invisible
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 0
   L0
   L1
    ALOAD 0
    GETFIELD gli_/coreTexture1d$5.p$ : Lio/kotlintest/TestContext;
    ASTORE 2
   L2
    LINENUMBER 130 L2
    ALOAD 0
    GETFIELD gli_/coreTexture1d$5.this$0 : Lgli_/coreTexture1d;
    ASTORE 3
    GETSTATIC gli_/Format.R32_SFLOAT_PACK32 : Lgli_/Format;
    ASTORE 4
    BIPUSH 8
    ANEWARRAY glm_/vec1/Vec1
    DUP
   L3
...
    LOCALVARIABLE $i$f$forEachIndexed I L3903 L3914 27
    LOCALVARIABLE this_$iv$iv$iv$iv Lgli_/Texture; L3935 L3936 32
    LOCALVARIABLE $i$f$data I L3935 L3936 33
    LOCALVARIABLE blockSize$iv$iv$iv I L3931 L3938 31
    LOCALVARIABLE imageOffset$iv$iv$iv I L3930 L3938 30
    LOCALVARIABLE extent$iv$iv$iv Lglm_/vec3/Vec3i; L3928 L3938 29
    LOCALVARIABLE this_$iv$iv$iv Lgli_/Texture; L3924 L3938 25
    LOCALVARIABLE texelCoord$iv$iv$iv Lglm_/vec3/Vec3i; L3924 L3938 26
    LOCALVARIABLE layer$iv$iv$iv I L3924 L3938 27
    LOCALVARIABLE face$iv$iv$iv I L3924 L3938 28
    LOCALVARIABLE $i$f$store I L3924 L3938 34
    LOCALVARIABLE this_$iv$iv Lgli_/Texture1d; L3923 L3939 22
    LOCALVARIABLE texelCoord$iv$iv Lglm_/vec1/Vec1i; L3923 L3939 23
    LOCALVARIABLE level$iv$iv I L3923 L3939 24
    LOCALVARIABLE $i$f$store I L3923 L3939 35
    LOCALVARIABLE i$iv I L3922 L3940 21
    LOCALVARIABLE test$iv Ljava/lang/Object; L3922 L3940 20
    LOCALVARIABLE $i$a$2$forEachIndexed I L3922 L3940 36
    LOCALVARIABLE item$iv$iv Ljava/lang/Object; L3921 L3941 19
    LOCALVARIABLE index$iv$iv I L3918 L3942 11
    LOCALVARIABLE $receiver$iv$iv [Ljava/lang/Object; L3917 L3942 10
    LOCALVARIABLE $i$f$forEachIndexed I L3917 L3942 37
    LOCALVARIABLE this_$iv$iv$iv Lgli_/Texture; L3950 L3951 23
    LOCALVARIABLE texelCoord$iv$iv$iv Lglm_/vec3/Vec3i; L3950 L3951 24
    LOCALVARIABLE layer$iv$iv$iv I L3950 L3951 25
    LOCALVARIABLE face$iv$iv$iv I L3950 L3951 26
    LOCALVARIABLE $i$f$load I L3950 L3951 27
    LOCALVARIABLE this_$iv$iv Lgli_/Texture1d; L3949 L3952 20
    LOCALVARIABLE texelCoord$iv$iv Lglm_/vec1/Vec1i; L3949 L3952 21
    LOCALVARIABLE level$iv$iv I L3949 L3952 22
    LOCALVARIABLE $i$f$load I L3949 L3952 28
    LOCALVARIABLE it$iv I L3948 L3953 19
    LOCALVARIABLE $i$a$1$<init> I L3948 L3953 29
    LOCALVARIABLE size$iv$iv I L3943 L3956 11
    LOCALVARIABLE $i$f$Array I L3943 L3956 30
    LOCALVARIABLE result$iv$iv [Ljava/lang/Object; L3944 L3956 12
    LOCALVARIABLE i$iv$iv I L3947 L3955 17
    LOCALVARIABLE this_$iv$iv$iv Lgli_/Texture; L3965 L3966 24
    LOCALVARIABLE texelCoord$iv$iv$iv Lglm_/vec3/Vec3i; L3965 L3966 25
    LOCALVARIABLE layer$iv$iv$iv I L3965 L3966 26
    LOCALVARIABLE face$iv$iv$iv I L3965 L3966 27
    LOCALVARIABLE $i$f$load I L3965 L3966 28
    LOCALVARIABLE this_$iv$iv Lgli_/Texture1d; L3964 L3967 21
    LOCALVARIABLE texelCoord$iv$iv Lglm_/vec1/Vec1i; L3964 L3967 22
    LOCALVARIABLE level$iv$iv I L3964 L3967 23
    LOCALVARIABLE $i$f$load I L3964 L3967 29
    LOCALVARIABLE it$iv I L3963 L3968 20
    LOCALVARIABLE $i$a$1$<init> I L3963 L3968 30
    LOCALVARIABLE size$iv$iv I L3958 L3971 12
    LOCALVARIABLE $i$f$Array I L3958 L3971 31
    LOCALVARIABLE result$iv$iv [Ljava/lang/Object; L3959 L3971 17
    LOCALVARIABLE i$iv$iv I L3962 L3970 18
    LOCALVARIABLE i$iv I L3975 L3977 12
    LOCALVARIABLE i$iv I L3980 L3982 12
    LOCALVARIABLE textureD$iv Lgli_/Texture1d; L3985 L3987 17
    LOCALVARIABLE textureC$iv Lgli_/Texture1d; L3984 L3987 12
    LOCALVARIABLE loadedSamplesB$iv [Ljava/lang/Object; L3972 L3987 11
    LOCALVARIABLE loadedSamplesA$iv [Ljava/lang/Object; L3957 L3987 10
    LOCALVARIABLE textureB$iv Lgli_/Texture1d; L3915 L3987 9
    LOCALVARIABLE textureA$iv Lgli_/Texture1d; L3901 L3987 8
    LOCALVARIABLE texelCoord$iv [Lglm_/vec1/Vec1i; L3900 L3987 16
    LOCALVARIABLE dimensions$iv Lglm_/vec1/Vec1i; L3888 L3987 7
    LOCALVARIABLE this_$iv Lgli_/coreTexture1d; L3887 L3987 5
    LOCALVARIABLE format$iv Lgli_/Format; L3887 L3987 6
    LOCALVARIABLE $i$f$run I L3887 L3987 38
    LOCALVARIABLE it [Lglm_/vec3/Vec3ui; L3885 L3991 4
    LOCALVARIABLE $i$a$15$let I L3885 L3991 39
    LOCALVARIABLE it$iv I L4020 L4022 12
    LOCALVARIABLE $i$a$1$<init> I L4020 L4022 17
    LOCALVARIABLE size$iv$iv I L4015 L4025 8
    LOCALVARIABLE $i$f$Array I L4015 L4025 18
    LOCALVARIABLE result$iv$iv [Ljava/lang/Object; L4016 L4025 9
    LOCALVARIABLE i$iv$iv I L4019 L4024 10
    LOCALVARIABLE this_$iv$iv Lgli_/Texture; L4035 L4036 21
    LOCALVARIABLE layer$iv$iv I L4035 L4036 22
    LOCALVARIABLE face$iv$iv I L4035 L4036 23
    LOCALVARIABLE level$iv$iv I L4035 L4036 24
    LOCALVARIABLE $i$f$data I L4035 L4036 25
    LOCALVARIABLE i$iv I L4034 L4038 20
    LOCALVARIABLE test$iv Ljava/lang/Object; L4034 L4038 19
    LOCALVARIABLE $i$a$1$forEachIndexed I L4034 L4038 26
    LOCALVARIABLE item$iv$iv Ljava/lang/Object; L4033 L4039 18
    LOCALVARIABLE index$iv$iv I L4030 L4040 10
    LOCALVARIABLE $receiver$iv$iv [Ljava/lang/Object; L4029 L4040 9
    LOCALVARIABLE $i$f$forEachIndexed I L4029 L4040 27
    LOCALVARIABLE this_$iv$iv$iv$iv Lgli_/Texture; L4061 L4062 32
    LOCALVARIABLE $i$f$data I L4061 L4062 33
    LOCALVARIABLE blockSize$iv$iv$iv I L4057 L4064 31
    LOCALVARIABLE imageOffset$iv$iv$iv I L4056 L4064 30
    LOCALVARIABLE extent$iv$iv$iv Lglm_/vec3/Vec3i; L4054 L4064 29
    LOCALVARIABLE this_$iv$iv$iv Lgli_/Texture; L4050 L4064 25
    LOCALVARIABLE texelCoord$iv$iv$iv Lglm_/vec3/Vec3i; L4050 L4064 26
    LOCALVARIABLE layer$iv$iv$iv I L4050 L4064 27
    LOCALVARIABLE face$iv$iv$iv I L4050 L4064 28
    LOCALVARIABLE $i$f$store I L4050 L4064 34
    LOCALVARIABLE this_$iv$iv Lgli_/Texture1d; L4049 L4065 22
    LOCALVARIABLE texelCoord$iv$iv Lglm_/vec1/Vec1i; L4049 L4065 23
    LOCALVARIABLE level$iv$iv I L4049 L4065 24
    LOCALVARIABLE $i$f$store I L4049 L4065 35
    LOCALVARIABLE i$iv I L4048 L4066 21
    LOCALVARIABLE test$iv Ljava/lang/Object; L4048 L4066 20
    LOCALVARIABLE $i$a$2$forEachIndexed I L4048 L4066 36
    LOCALVARIABLE item$iv$iv Ljava/lang/Object; L4047 L4067 19
    LOCALVARIABLE index$iv$iv I L4044 L4068 11
    LOCALVARIABLE $receiver$iv$iv [Ljava/lang/Object; L4043 L4068 10
    LOCALVARIABLE $i$f$forEachIndexed I L4043 L4068 37
    LOCALVARIABLE this_$iv$iv$iv Lgli_/Texture; L4076 L4077 23
    LOCALVARIABLE texelCoord$iv$iv$iv Lglm_/vec3/Vec3i; L4076 L4077 24
    LOCALVARIABLE layer$iv$iv$iv I L4076 L4077 25
    LOCALVARIABLE face$iv$iv$iv I L4076 L4077 26
    LOCALVARIABLE $i$f$load I L4076 L4077 27
    LOCALVARIABLE this_$iv$iv Lgli_/Texture1d; L4075 L4078 20
    LOCALVARIABLE texelCoord$iv$iv Lglm_/vec1/Vec1i; L4075 L4078 21
    LOCALVARIABLE level$iv$iv I L4075 L4078 22
    LOCALVARIABLE $i$f$load I L4075 L4078 28
    LOCALVARIABLE it$iv I L4074 L4079 19
    LOCALVARIABLE $i$a$1$<init> I L4074 L4079 29
    LOCALVARIABLE size$iv$iv I L4069 L4082 11
    LOCALVARIABLE $i$f$Array I L4069 L4082 30
    LOCALVARIABLE result$iv$iv [Ljava/lang/Object; L4070 L4082 12
    LOCALVARIABLE i$iv$iv I L4073 L4081 17
    LOCALVARIABLE this_$iv$iv$iv Lgli_/Texture; L4091 L4092 24
    LOCALVARIABLE texelCoord$iv$iv$iv Lglm_/vec3/Vec3i; L4091 L4092 25
    LOCALVARIABLE layer$iv$iv$iv I L4091 L4092 26
    LOCALVARIABLE face$iv$iv$iv I L4091 L4092 27
    LOCALVARIABLE $i$f$load I L4091 L4092 28
    LOCALVARIABLE this_$iv$iv Lgli_/Texture1d; L4090 L4093 21
    LOCALVARIABLE texelCoord$iv$iv Lglm_/vec1/Vec1i; L4090 L4093 22
    LOCALVARIABLE level$iv$iv I L4090 L4093 23
    LOCALVARIABLE $i$f$load I L4090 L4093 29
    LOCALVARIABLE it$iv I L4089 L4094 20
    LOCALVARIABLE $i$a$1$<init> I L4089 L4094 30
    LOCALVARIABLE size$iv$iv I L4084 L4097 12
    LOCALVARIABLE $i$f$Array I L4084 L4097 31
    LOCALVARIABLE result$iv$iv [Ljava/lang/Object; L4085 L4097 17
    LOCALVARIABLE i$iv$iv I L4088 L4096 18
    LOCALVARIABLE i$iv I L4101 L4103 12
    LOCALVARIABLE i$iv I L4106 L4108 12
    LOCALVARIABLE textureD$iv Lgli_/Texture1d; L4111 L4113 17
    LOCALVARIABLE textureC$iv Lgli_/Texture1d; L4110 L4113 12
    LOCALVARIABLE loadedSamplesB$iv [Ljava/lang/Object; L4098 L4113 11
    LOCALVARIABLE loadedSamplesA$iv [Ljava/lang/Object; L4083 L4113 10
    LOCALVARIABLE textureB$iv Lgli_/Texture1d; L4041 L4113 9
    LOCALVARIABLE textureA$iv Lgli_/Texture1d; L4027 L4113 8
    LOCALVARIABLE texelCoord$iv [Lglm_/vec1/Vec1i; L4026 L4113 16
    LOCALVARIABLE dimensions$iv Lglm_/vec1/Vec1i; L4014 L4113 7
    LOCALVARIABLE this_$iv Lgli_/coreTexture1d; L4013 L4113 5
    LOCALVARIABLE format$iv Lgli_/Format; L4013 L4113 6
    LOCALVARIABLE $i$f$run I L4013 L4113 38
    LOCALVARIABLE it [Lglm_/vec4/Vec4ui; L4011 L4117 4
    LOCALVARIABLE $i$a$16$let I L4011 L4117 39
    LOCALVARIABLE this Lgli_/coreTexture1d$5; L0 L4124 0
    LOCALVARIABLE result Ljava/lang/Object; L0 L4124 1
    MAXSTACK = 9
    MAXLOCALS = 40

Cause: GC overhead limit exceeded
Element is unknownThe root cause was thrown at: HashMap.java:1747
        at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.java:88)
        at org.jetbrains.kotlin.codegen.FunctionCodegen.endVisit(FunctionCodegen.java:992)
        ... 97 more
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.HashMap.newNode(HashMap.java:1747)
        at java.util.HashMap.putVal(HashMap.java:631)
        at java.util.HashMap.put(HashMap.java:612)
        at java.util.HashSet.add(HashSet.java:220)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
        at org.jetbrains.org.objectweb.asm.tree.analysis.SourceInterpreter.merge(SourceInterpreter.java:192)
        at org.jetbrains.org.objectweb.asm.tree.analysis.SourceInterpreter.merge(SourceInterpreter.java:49)
        at org.jetbrains.org.objectweb.asm.tree.analysis.Frame.merge(Frame.java:691)
        at org.jetbrains.org.objectweb.asm.tree.analysis.Analyzer.merge(Analyzer.java:507)
        at org.jetbrains.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:269)
        at org.jetbrains.kotlin.codegen.optimization.transformer.MethodTransformer.runAnalyzer(MethodTransformer.java:31)
        at org.jetbrains.kotlin.codegen.optimization.transformer.MethodTransformer.analyze(MethodTransformer.java:44)
        at org.jetbrains.kotlin.codegen.coroutines.ReturnUnitMethodTransformerKt.findSourceInstructions(ReturnUnitMethodTransformer.kt:141)
        at org.jetbrains.kotlin.codegen.coroutines.RedundantLocalsEliminationMethodTransformer.findPopPredecessors(RedundantLocalsEliminationMethodTransformer.kt:134)
        at org.jetbrains.kotlin.codegen.coroutines.RedundantLocalsEliminationMethodTransformer.simpleRemove(RedundantLocalsEliminationMethodTransformer.kt:114)
        at org.jetbrains.kotlin.codegen.coroutines.RedundantLocalsEliminationMethodTransformer.transform(RedundantLocalsEliminationMethodTransformer.kt:28)
        at org.jetbrains.kotlin.codegen.coroutines.CoroutineTransformerMethodVisitor.performTransformations(CoroutineTransformerMethodVisitor.kt:92)
        at org.jetbrains.kotlin.codegen.TransformationMethodVisitor.visitEnd(TransformationMethodVisitor.java:65)
        at org.jetbrains.kotlin.codegen.FunctionCodegen.endVisit(FunctionCodegen.java:992)
        at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:488)
        at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:264)
        at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:182)
        at org.jetbrains.kotlin.codegen.coroutines.CoroutineCodegenForLambda.generateResumeImpl(CoroutineCodegen.kt:450)
        at org.jetbrains.kotlin.codegen.coroutines.CoroutineCodegenForLambda.generateClosureBody(CoroutineCodegen.kt:234)
        at org.jetbrains.kotlin.codegen.ClosureCodegen.generateBody(ClosureCodegen.java:168)
        at org.jetbrains.kotlin.codegen.coroutines.CoroutineCodegenForLambda.generateBody(CoroutineCodegen.kt:242)
        at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:127)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.genClosure(ExpressionCodegen.java:1019)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.genClosure(ExpressionCodegen.java:989)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitLambdaExpression(ExpressionCodegen.java:980)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitLambdaExpression(ExpressionCodegen.java:108)
        at org.jetbrains.kotlin.psi.KtLambdaExpression.accept(KtLambdaExpression.java:39)
```

**Comment by LeoColman** [comment]
Oh wow

**Comment by elect86** [comment]
Ok, [issue](https://youtrack.jetbrains.com/issue/KT-29516) opened

**Comment by sksamuel** [comment]
I tried Kotlin 1.3.20 as well.

**Comment by sksamuel** [comment]
https://youtrack.jetbrains.com/issue/KT-29517

**Comment by sksamuel** [comment]
Oops me too. I'll close mine and link.

**Comment by LeoColman** [comment]
Any chances we can find which specific class is failing this, and provide a
workaround?

I tried debugging, but no success

**Comment by abelkov** [comment]
We have a similar bug report back from two years ago: https://youtrack.jetbrains.com/issue/KT-16493. The problem seems to be a particular pattern of using nested lambdas with receivers. It would be very helpful if you found the change in `kotlintest` diff that causes this to happen.

**Comment by LeoColman** [comment]
I hope Kotlin can fix this issue.
This is stale and not exactly something we can help with.

I'll close
