### ISSUE TITLE
Lifecycle behaviour in combination with BehaviorSpec

### ISSUE THREAD

**Issue by dtieber** [kotest/kotest#776]
## Description
I prefer BDD style which is why I'm using BehaviorSpec. However, I think there is an issue with lifecycle events. I read the documentation and it's not working as expected. Please mind the code below, which makes it easier to understand the issue.

There is only one test in my suite, but "beforeTest" is triggered three times. This leads to a problem because I'd like to verify an invocation in the `Then` block, but my mock is cleared at this point of time already, which is why this test fails. If I copied the `When` code to the `Then` block everything's fine. 

## Observed
You can search for "XXX" in order to see all lifecycle events of my test. Right now it looks like this:

1. init
2. beforeTest
3. Given
4. beforeTest
5. When
6. beforeTest
7. Then

## Expected
1. init
2. beforeTest
3. Given
4. When
5. Then

## Code
Let's imagine you want to test those classes:
```kotlin
class Foo(val bar: Bar) {
    fun foo() {
        bar.bar("abc")
    }
}

class Bar {
    fun bar(arg: String) { }
}
```

This is the actual test:
```kotlin
class TestTest : BehaviorSpec() {

    val log = LoggerFactory.getLogger(TestTest::class.java)
    val barMock = mockk<Bar>(relaxed = true)
    val foo = Foo(barMock)

    override fun beforeTest(testCase: TestCase) {
        log.info("XXX: beforeTest")
        clearMocks(barMock)
    }

    init {
        log.info("XXX: init")

        Given("a valid request") {
            log.info("XXX: Given")

            When("foo is invoked") {
                log.info("XXX: when")
                foo.foo()

                Then("bar is invoked with xxx") {
                    log.info("XXX: then")
                    verify {
                        barMock.bar( withArg { it shouldBe "abc" })
                    }
                }
            }
        }
    }
}
```

## Stacktrace
```
16:15:47.201 [main] DEBUG io.kotlintest.runner.jvm.TestDiscovery - Loaded 1 classes from classnames...
16:15:47.201 [main] DEBUG io.kotlintest.runner.jvm.TestDiscovery - Scan discovered 0 classes in the classpaths...
16:15:47.201 [main] DEBUG io.kotlintest.runner.jvm.TestDiscovery - Scan discovered 0 classes by package...
16:15:47.552 [main] DEBUG io.kotlintest.runner.jvm.TestDiscovery - After filters there are 1 spec classes
16:15:47.556 [main] DEBUG io.kotlintest.runner.jvm.TestDiscovery - After discovery extensions there are 1 spec classes16:15:47.729 [main] DEBUG io.kotlintest.runner.junit5.KotlinTestEngine - JUnit execution request [configurationParameters=LauncherConfigurationParameters []; rootTestDescriptor=KotlinTestEngineDescriptor: [engine:kotlintest]]
16:15:47.751 [main] DEBUG io.kotlintest.runner.junit5.JUnitTestRunnerListener - Engine started; classes=[[class com.rbmh.imageapi.controller.TestTest]]
16:15:47.754 [main] DEBUG io.kotlintest.runner.jvm.TestEngine - Submitting 1 specs
16:15:47.757 [main] DEBUG io.kotlintest.runner.jvm.TestEngine - Waiting for spec execution to terminate
16:15:48.028 [kotlintest-engine-0] DEBUG io.mockk.impl.instantiation.AbstractMockFactory - Creating mockk for Bar name=#1
16:15:48.533 [kotlintest-engine-0] INFO com.rbmh.imageapi.controller.TestTest - XXX: init
16:15:48.857 [pool-2-thread-1 @coroutine#2] INFO com.rbmh.imageapi.controller.TestTest - XXX: beforeTest
16:15:48.944 [pool-2-thread-1 @coroutine#2] DEBUG io.mockk.impl.stub.CommonClearer - Clearing [Bar(#1)] mocks ClearOptions(answers=true, recordedCalls=true, childMocks=true, verificationMarks=true, exclusionRules=true)
16:15:48.959 [pool-2-thread-1 @coroutine#4] INFO com.rbmh.imageapi.controller.TestTest - XXX: Given
16:15:48.963 [pool-2-thread-1 @coroutine#5] INFO com.rbmh.imageapi.controller.TestTest - XXX: beforeTest
16:15:48.963 [pool-2-thread-1 @coroutine#5] DEBUG io.mockk.impl.stub.CommonClearer - Clearing [Bar(#1)] mocks ClearOptions(answers=true, recordedCalls=true, childMocks=true, verificationMarks=true, exclusionRules=true)
16:15:48.966 [pool-2-thread-1 @coroutine#7] INFO com.rbmh.imageapi.controller.TestTest - XXX: when
16:15:48.994 [pool-2-thread-1 @coroutine#7] DEBUG io.mockk.impl.recording.states.AnsweringState - Answering kotlin.Unit on Bar(#1).bar(abc)
16:15:48.997 [pool-2-thread-1 @coroutine#8] INFO com.rbmh.imageapi.controller.TestTest - XXX: beforeTest
16:15:48.997 [pool-2-thread-1 @coroutine#8] DEBUG io.mockk.impl.stub.CommonClearer - Clearing [Bar(#1)] mocks ClearOptions(answers=true, recordedCalls=true, childMocks=true, verificationMarks=true, exclusionRules=true)
16:15:48.999 [pool-2-thread-1 @coroutine#10] INFO com.rbmh.imageapi.controller.TestTest - XXX: then

java.lang.AssertionError: Verification failed: call 1 of 1: Bar(#1).bar(matcher<String>())) was not called

  at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
  at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
  at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
  at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
  at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
  at io.mockk.MockKDsl.internalVerify(API.kt:118)
  at io.mockk.MockKKt.verify(MockK.kt:139)
  at io.mockk.MockKKt.verify$default(MockK.kt:136)
  at com.rbmh.imageapi.controller.TestTest$1$1$1.invokeSuspend(TestTest.kt:46)
  at com.rbmh.imageapi.controller.TestTest$1$1$1.invoke(TestTest.kt)
  at io.kotlintest.specs.AbstractBehaviorSpec$WhenContext$addThenContext$2.invokeSuspend(AbstractBehaviorSpec.kt:90)
  at io.kotlintest.specs.AbstractBehaviorSpec$WhenContext$addThenContext$2.invoke(AbstractBehaviorSpec.kt)
  at io.kotlintest.runner.jvm.TestCaseExecutor$executeTest$supervisorJob$1$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(TestCaseExecutor.kt:121)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)

16:15:49.136 [main] DEBUG io.kotlintest.runner.junit5.JUnitTestRunnerListener - Engine finished; throwable=[null]
16:15:49.146 [main] DEBUG io.kotlintest.runner.junit5.JUnitTestRunnerListener - Writing report to /Users/dti/dev/image-api/.kotlintest/spec_failures

Process finished with exit code 255

```

**Comment by LeoColman** [comment]
@sksamuel I think I need some help to understand this one.

**Comment by sksamuel** [comment]
Before Test will run 3 times because each "block" is considered a test.

Consider if you had multiple when's inside the given, and so on, what would
delimit the before test then?
If you just want something to run once, then you can do beforeSpec, or if
you want something else perhaps we can add it.

**Comment by dtieber** [comment]
@sksamuel Thank you for the clarification; I got your points.
`beforeSpec` doesn't really help in my case. I would like to set up (and reset) my mocks on `beforeTest` so that all test cases can be written in the most concise way possible (like in my example). 

As this doesn't seem to be a bug but a design consideration, I'll maybe switch to another style then.

**Comment by LeoColman** [comment]
Perhaps this can be solved with IsolationMode. Could you take a look, @dtieber?

**Comment by jacekgajek** [comment]
This problem is still present. beforeTest is executed multiple times. I'd expect to run it once per test. By "test" I mean the leaf, which is always `when`

Expected

test 1

1. init
2. Given 1
3. When 1
4. beforeTest
5. Then 1
6. afterTest

test 2

1. init
2. Given 1
3. When 1
4. beforeTest
5. Then 2
6. afterTest

**Comment by vprudnikov** [comment]
I agree that the current behavior is confusing. It surprises me in all ways, and I have to debug the test to understand why it works or doesn't.

For example I have a test 

```

    beforeEach {
        fakeEventPublisher.reset()
    }

    context("Customer is deactivated") {
        given("an active customer") {
            val customer = Customer()
            every { customerRepository.find(customer.id) } returns Optional.of(customer)

            `when`("service deactivates the customer") {
                customerDeactivationService.deactivateCustomer(customerId)

                then("customer should be deactivated") {
                    customer.isActive shouldBe false
                }
                and("customer is saved") {
                    verify { customerRepository.save(customer) }
                }
                and("CustomerDeactivated is published") {
                    fakeEventPublisher.publishedEvents shouldContain CustomerDeactivated(customerId)
                }
            }
        }
    }

```

The question is: How do we ensure the `fakeEventPublisher` gets reset **before the where block and only then**?

I tried to play with isolation modes and calling different beforeXXX methods.
The `isolationMode = IsolationMode.InstancePerLeaf` does the trick, since a new instance of fakeEventPublisher will be recreated per each run of given-when-then.

However, it doesn't work in integration tests when we have a shared instance for the whole test.

As a developer, I have pretty fair expectations: I want to run `fakeEventPublisher.reset()` before the `when` block. The implementation design considerations and limitations shouldn't confuse the developer, in my opinion :)

Thank you!
