### ISSUE TITLE
Update to 3.3.0+ leads to test framework error

### ISSUE THREAD

**Issue by yaroslav-shlapak** [kotest/kotest#789]
Reproduced on: Android Studio 3.5 Beta 2 and IntelliJ IDEA 2019.1.2
The test project to reproduce: https://github.com/yaroslav-shlapak/TestSpekProject

After update to 3.3.2 from 3.1.10 getting the error all the time when runnig tests:
![Screenshot from 2019-05-28 15-26-49](https://user-images.githubusercontent.com/3373419/58477780-107bc800-815d-11e9-9788-99ddd40ada8c.png)
```
Exception in thread "main" java.lang.annotation.AnnotationFormatError: java.lang.IllegalArgumentException: Wrong type at constant pool index
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:77)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getDeclaredAnnotations(Class.java:3477)
	at kotlin.reflect.jvm.internal.components.ReflectClassStructure.loadClassAnnotations(ReflectKotlinClass.kt:85)
	at kotlin.reflect.jvm.internal.components.ReflectKotlinClass$Factory.create(ReflectKotlinClass.kt:57)
	at kotlin.reflect.jvm.internal.components.ReflectKotlinClassFinder.findKotlinClass(ReflectKotlinClassFinder.kt:28)
	at kotlin.reflect.jvm.internal.components.ReflectKotlinClassFinder.findKotlinClassOrContent(ReflectKotlinClassFinder.kt:31)
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaPackageScope$classes$1.invoke(LazyJavaPackageScope.kt:63)
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaPackageScope$classes$1.invoke(LazyJavaPackageScope.kt:43)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:440)
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaPackageScope.findClassifier(LazyJavaPackageScope.kt:145)
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaPackageScope.getContributedClassifier(LazyJavaPackageScope.kt:135)
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.JvmPackageScope.getContributedClassifier(JvmPackageScope.kt:52)
	at kotlin.reflect.jvm.internal.impl.resolve.scopes.ChainedMemberScope.getContributedClassifier(ChainedMemberScope.kt:33)
	at kotlin.reflect.jvm.internal.impl.resolve.scopes.AbstractScopeAdapter.getContributedClassifier(AbstractScopeAdapter.kt:44)
	at kotlin.reflect.jvm.internal.impl.descriptors.FindClassInModuleKt.findClassAcrossModuleDependencies(findClassInModule.kt:25)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:51)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:44)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt)
	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:179)
	at kotlin.reflect.jvm.internal.KClassImpl.isAbstract(KClassImpl.kt:268)
	at org.spekframework.spek2.runtime.JvmDiscoveryContextFactory.create(JvmDiscoveryContextFactory.kt:26)
	at org.spekframework.ide.Spek2ConsoleLauncher.run(console.kt:17)
	at org.spekframework.ide.ConsoleKt$main$1.invoke(console.kt:35)
	at org.spekframework.ide.ConsoleKt$main$1.invoke(console.kt)
	at shadow.com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:74)
	at shadow.com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:72)
	at org.spekframework.ide.ConsoleKt.main(console.kt:33)
Caused by: java.lang.IllegalArgumentException: Wrong type at constant pool index
	at sun.reflect.ConstantPool.getClassAt0(Native Method)
	at sun.reflect.ConstantPool.getClassAt(ConstantPool.java:37)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:244)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	... 30 more
```
3.1.10 and 3.2.1 work without any problems.

**Comment by sksamuel** [comment]
Which JDK?

**Comment by yaroslav-shlapak** [comment]
@sksamuel 
For Android Studio 3.5 Beta 2:
openjdk version "1.8.0_202-release"
OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b39-5509098)
OpenJDK 64-Bit Server VM (build 25.202-b39-5509098, mixed mode)

For  IntelliJ IDEA 2019.1.2:
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

**Comment by sksamuel** [comment]
Your stack trace is from Spek.
This is KotlinTest.

**Comment by LeoColman** [comment]
You're probably trying to execute the tests using Spek plugin. You should use KotlinTest's

**Comment by yaroslav-shlapak** [comment]
The problem is with 3.3.0 update, before that there were no conflicts between test frameworks. I don't use KotlinTest for Test Cases structuring only for the assertion. Is it possible to use KotlinTest only as assertion/matcher library?

**Comment by sksamuel** [comment]
Yes, you just need to include `kotlintest-assertions` module instead of junit5 runner.

Any reason you use Spek and KT together? KT is superior in every way :)

**Comment by LeoColman** [comment]
You may use only the assertions artifact, yes.

**Comment by yaroslav-shlapak** [comment]
@sksamuel  switching to  `kotlintest-assertions`  fixed my issue. Thank you!
As for the usage of both Spek and KT - let's say it is because of historical reasons ;) 
But yes, it looks like the features of Spek are a subset of KT features. I will definitely use it in the future projects both as test organization and assertion framework.

**Comment by sksamuel** [comment]
Yes. Bring in the assertions module only. kotlintest-assertions on maven
central.

Are you going to upgrade fully to kotlintest in the future?

**Comment by yaroslav-shlapak** [comment]
On that particular project, it might be hard to do because it has 1600+ unit tests. But I'm started converting test suite on the small side project from Spek to KT and have several questions.

Suppose we have next test suite
```
class MyTests : FreeSpec({
    val globalFixture = initGlobalFixture()
    "a test group 0" - {
        val group0Fixture = intitGroup0Fixture()
        "test 0" {
            test0Fixture()
            test0Exercise()
            test0Assertion()
        }
        "test 1" {
            tes1Fixture()
            test1Exercise()
            test1Assertion()
        }
    }
....
}
```
Does KT provide some tools to make globalFixture or group0Fixture fresh for every test?

**Comment by yaroslav-shlapak** [comment]
Another question, is it possible to run tests with KT plugin runner for package containing several other packages with tests?

**Comment by sksamuel** [comment]
So like run tests for a parent package only ?

**Comment by yaroslav-shlapak** [comment]
What I mean is the ability to run all tests in a package by clicking the right mouse button on the package and selecting "Run as Kotlin Test". I'm able to run tests with JUnit or Spek runner, but not by KT runner. KT runner is only able to run tests from the corresponding file.

**Comment by sksamuel** [comment]
Ok I understand. We'll add that.

**Comment by yaroslav-shlapak** [comment]
@sksamuel  are there any options to set new fixture for each test? It should work similarly to @BeforeEach annotation but for the variable instead of function. In Spek there is next construction:
`val freshFixture by memoized { initFreshFixture() }` - which means that `freshFixture` will be reinitialized for every downward test in the current scope.
Is there something similar in Kotlin Test?

**Comment by sksamuel** [comment]
In KT you don't need to bother with fixtures. Just make a val in your class and then set the isolation mode. Then KT will create a fresh instance of the test class (and thus the val) for every test.

**Comment by yaroslav-shlapak** [comment]
Got it. So basically what I need is described [here](https://github.com/kotlintest/kotlintest/blob/master/doc/isolation_mode.md)
Thank you @sksamuel !
