### ISSUE TITLE
java.lang.StackOverflowError on First Test Case Using 3.3.3

### ISSUE THREAD

**Issue by gchallen** [kotest/kotest#867]
We have a ~100 test kotlintest suite. After upgrading Kotlintest from 3.3.2 -> 3.3.3 it seems that the _first_ test run in any configuration that uses coroutines—whether running a single test or the entire suite—fails with the following `java.lang.StackOverflow` error:

Our codebase is [here](https://github.com/cs125-illinois/jeed/) if want to try reproducing the problem.

```sh
java.lang.AssertionError: Code should have run: java.lang.StackOverflowError

	at edu.illinois.cs.cs125.jeed.core.TestCompile$1$17.invokeSuspend(TestCompile.kt:201)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:45)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterCompletionInternal(Scopes.kt:32)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:311)
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:277)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:809)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:789)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by sksamuel** [comment]
Thanks, I will take a look.

**Comment by gchallen** [comment]
FWIW upgrading to `kotlin-reflect` 1.3.40 also triggers the same bug. Not sure if you are using that package or not...

**Comment by gchallen** [comment]
Still broken at `kotlin-reflect` 1.3.41. Would be great to see this get addressed since its starting to pin multiple packages at out-of-date revisions. Happy to provide more debugging information if needed.

**Comment by sksamuel** [comment]
Your project doesn't run for me in intellij.
It may be that you have some custom intellij step, as I noticed you checked in your .idea folder.

Running from gradle gives me this:
```
> Task :core:compileKotlin FAILED
e: /Users/ssamuel/development/workspace/jeed/core/src/main/kotlin/Checkstyle.kt: (35, 53): Unresolved reference: packageName
e: /Users/ssamuel/development/workspace/jeed/core/src/main/kotlin/Compile.kt: (126, 44): Unresolved reference: readAllBytes
e: /Users/ssamuel/development/workspace/jeed/core/src/main/kotlin/Compile.kt: (203, 57): Unresolved reference: readAllBytes
```

**Comment by gchallen** [comment]
I was able to reproduce the problem on Java 8. Make sure you are using Java 10. (We have a `.java-version` file checked in but it doesn't work unless you use [`jenv`](https://www.jenv.be/).)

**Comment by sksamuel** [comment]
I'm only using jdk 8 as dokka doesn't work with jdk 10.

**Comment by gchallen** [comment]
Overall things seem to work fine with JDK 10, other than this bug. But does this mean that it won't be addressed?

We need JDK 10 because we want to use the later javax compiler tool that include 10 features. So far `kotlintest` seems to be the only place where this causes a problem.

**Comment by LeoColman** [comment]
Your sample project didn't compile after I imported it in IntelliJ.

I'm doing something wrong maybe?

**Comment by sksamuel** [comment]
This is probably related to #610

**Comment by sksamuel** [comment]
Can you try 4.0.0 beta?

**Comment by sksamuel** [comment]
Closing this. If it can be recreated with 4.0.x please reopen.
