### ISSUE TITLE
Test with SpringListener causes "field cannot have an existing value" with 3.4.0+

### ISSUE THREAD

**Issue by xcq1** [kotest/kotest#982]
I've stumbled on a problem while upgrading kotlintest for running a SpringBoot with WebMvc test like this:
```kotlin
@Service
class SimpleBean {}

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.MOCK)
@AutoConfigureMockMvc
class ExampleTest : DescribeSpec() {

    @Autowired
    private lateinit var mvc: MockMvc

    @MockkBean
    private lateinit var simpleBean: SimpleBean

    override fun listeners() = listOf(SpringListener)

    init {
        describe("example test") {
            it("doesn't throw an unexpected exception") {
                mvc.perform(MockMvcRequestBuilders.get("/"))
                        .andExpect(MockMvcResultMatchers.status().is3xxRedirection)
            }
        }
    }
```

I'm using these gradle dependencies:
```gradle
...
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.3.2")
    testRuntimeOnly("org.junit.vintage:junit-vintage-engine:5.3.2")
    testImplementation('io.kotlintest:kotlintest-runner-junit5:3.4.0')
    testImplementation("io.kotlintest:kotlintest-extensions-spring:3.4.0")
    testImplementation("io.mockk:mockk:1.9.3")
    testImplementation("com.ninja-squad:springmockk:1.1.2")
```

When running with Kotlintest 3.3.3 everything works as expected, but when I run it with 3.4.0+ as stated above, I'm getting this exception when running the test:
```
org.springframework.beans.factory.BeanCreationException: Could not inject field: private com.example.SimpleBean com.example.ExampleTest.simpleBean; nested exception is java.lang.IllegalStateException: The field private com.example.SimpleBean com.example.ExampleTest.simpleBean cannot have an existing value
	at com.ninjasquad.springmockk.MockkPostProcessor.inject(MockkPostProcessor.kt:356)
	at com.ninjasquad.springmockk.MockkPostProcessor.inject$springmockk(MockkPostProcessor.kt:344)
	at com.ninjasquad.springmockk.MockkTestExecutionListener$injectFields$1.invoke(MockkTestExecutionListener.kt:51)
	at com.ninjasquad.springmockk.MockkTestExecutionListener$injectFields$1.invoke(MockkTestExecutionListener.kt:18)
	at com.ninjasquad.springmockk.MockkTestExecutionListener.postProcessFields(MockkTestExecutionListener.kt:84)
	at com.ninjasquad.springmockk.MockkTestExecutionListener.injectFields(MockkTestExecutionListener.kt:50)
	at com.ninjasquad.springmockk.MockkTestExecutionListener.prepareTestInstance(MockkTestExecutionListener.kt:25)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:246)
	at io.kotlintest.spring.SpringListener.beforeTest(SpringListener.kt:31)
	at io.kotlintest.runner.jvm.TestCaseExecutor.before(TestCaseExecutor.kt:183)
	at io.kotlintest.runner.jvm.TestCaseExecutor.access$before(TestCaseExecutor.kt:35)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$3.invokeSuspend(TestCaseExecutor.kt:49)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$3.invoke(TestCaseExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:146)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at io.kotlintest.runner.jvm.TestCaseExecutor.execute(TestCaseExecutor.kt:48)
	at io.kotlintest.runner.jvm.spec.SingleInstanceSpecRunner$Context.registerTestCase(SingleInstanceSpecRunner.kt:44)
	at io.kotlintest.TestContext.registerTestCase(TestContext.kt:52)
	at io.kotlintest.specs.AbstractDescribeSpec$DescribeScope.it(AbstractDescribeSpec.kt:40)
	at com.example.ExampleTest$1.invokeSuspend(ExampleTest.kt:31)
	at com.example.ExampleTest$1.invoke(ExampleTest.kt)
	at io.kotlintest.specs.AbstractDescribeSpec$describe$1.invokeSuspend(AbstractDescribeSpec.kt:50)
	at io.kotlintest.specs.AbstractDescribeSpec$describe$1.invoke(AbstractDescribeSpec.kt)
	at io.kotlintest.runner.jvm.TestCaseExecutor$executeTest$supervisorJob$1$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(TestCaseExecutor.kt:133)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: The field private com.example.SimpleBean com.example.ExampleTest.simpleBean cannot have an existing value
	at com.ninjasquad.springmockk.MockkPostProcessor.inject(MockkPostProcessor.kt:350)
	... 29 more
```

**Comment by LeoColman** [comment]
I'll take a look into it.

We introduced a fix in #950 to some spring issues. The new behaviour might have caused this change.

**Comment by LeoColman** [comment]
I couldn't reproduce this issue with

```
@Service
class SimpleBean {

    fun foo(): String = throw RuntimeException()
}


@SpringBootTest(classes = [SimpleBean::class])
class MockkBeanTest : DescribeSpec() {

    @MockkBean
    private lateinit var simpleBean: SimpleBean

    override fun listeners() = listOf(SpringListener)

    override fun beforeTest(testCase: TestCase) {
        every { simpleBean.foo() } returns "Foo"
    }

    init {
        describe("Should not crash mockk bean") {
            it("First test") {
                simpleBean.foo() shouldBe "Foo"
            }

            it("Second Test") {
                simpleBean.foo() shouldBe "Foo"
            }
        }

        describe("Should not crash mockk bean 2") {
            it("First test") {
                simpleBean.foo() shouldBe "Foo"
            }

            it("Second Test") {
                simpleBean.foo() shouldBe "Foo"
            }
        }

    }
}
```

Could you help me setup the code to cause it?

**Comment by LeoColman** [comment]
I enhanced the test to user MockkMVC as well:
```

@Service
class SimpleBean {

    fun foo(): String = throw RuntimeException()
}

@Controller
class DummyController(
        private val simpleBean: SimpleBean
) {

    @RequestMapping("/")
    @ResponseBody fun foo() = simpleBean.foo()

}


@SpringBootTest(classes = [SimpleBean::class, DummyController::class])
@AutoConfigureMockMvc
class MockkBeanTest : DescribeSpec() {

    @Autowired
    private lateinit var mockMvc: MockMvc

    @MockkBean
    private lateinit var simpleBean: SimpleBean

    override fun listeners() = listOf(SpringListener)

    override fun beforeTest(testCase: TestCase) {
        every { simpleBean.foo() } returns "Foo"
    }

    init {
        describe("Should not crash mockk bean") {
            it("First test") {
                simpleBean.foo() shouldBe "Foo"
            }

            it("Second Test") {
                simpleBean.foo() shouldBe "Foo"
            }
        }

        describe("Should not crash mockk bean 2") {
            it("First test") {
                simpleBean.foo() shouldBe "Foo"
            }

            it("Second Test") {
                simpleBean.foo() shouldBe "Foo"
            }

            it("Third test") {
                mockMvc.perform(MockMvcRequestBuilders.get("/"))
                        .andExpect(MockMvcResultMatchers.content().string("Foo"))
            }
        }

    }
}

```

It passes too

**Comment by xcq1** [comment]
Thanks for looking into this. I have prepared a quick minimal Spring Initializr example project that illustrates my issue: [demo.zip](https://github.com/kotlintest/kotlintest/files/3606134/demo.zip)

Running ExampleTest with the kotlintest plugin, e.g. via the provided launch config results in the test failing with the mentioned exception. I hope this helps you reproduce the issue.

**Comment by LeoColman** [comment]
Could you please test with 3.4.2? I believe it's fixed.

**Comment by xcq1** [comment]
My provided example is passing. However in my real world application I get a strange ByteBuddy exception:
```
java.lang.IllegalStateException: Illegal type name: com.m.a.c.rest.public.SamlControllerTest$ByteBuddy$EoViFUnW for class com.m.a.c.rest.public.SamlControllerTest$ByteBuddy$EoViFUnW
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated(InstrumentedType.java:1197)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:519)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:207)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:198)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3404)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3600)
	at io.kotlintest.spring.SpringListener.getMethod(SpringListener.kt:68)
	at io.kotlintest.spring.SpringListener.beforeTest(SpringListener.kt:36)
	at io.kotlintest.runner.jvm.TestCaseExecutor.before(TestCaseExecutor.kt:183)
	at io.kotlintest.runner.jvm.TestCaseExecutor.access$before(TestCaseExecutor.kt:35)
	at io.kotlintest.runner.jvm.TestCaseExecutor$execute$3.invokeSuspend(TestCaseExecutor.kt:49)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Can you make sense of that? I'm guessing it's some kind of additional library/setting interfering but I don't have the time to look further into it right now.

**Comment by donamk** [comment]
@Kerooker 
When I use an interface for a service, I got the following error.
```
Parameter 0 of constructor in gettingstarted.springkt.DummyController required a bean of type 'gettingstarted.springkt.SimpleBean' that could not be found.
```

The Source code I used (I just added an interface from your code)
```
@SpringBootTest(classes = [SimpleService::class, SimpleBean::class, DummyController::class])
@AutoConfigureMockMvc
class MockkBeanTest : DescribeSpec() {

    @Autowired
    private lateinit var mockMvc: MockMvc

    @MockkBean
    private lateinit var simpleBean: SimpleService

    override fun listeners() = listOf(SpringListener)

    override fun beforeTest(testCase: TestCase) {
        every { simpleBean.foo() } returns "Foo"
    }

    init {
        describe("Should not crash mockk bean") {
            it("First test") {
                simpleBean.foo() shouldBe "Foo"
            }

            it("Second Test") {
                simpleBean.foo() shouldBe "Foo"
            }
        }

        describe("Should not crash mockk bean 2") {
            it("First test") {
                simpleBean.foo() shouldBe "Foo"
            }

            it("Second Test") {
                simpleBean.foo() shouldBe "Foo"
            }

            it("Third test") {
                mockMvc.perform(MockMvcRequestBuilders.get("/"))
                    .andExpect(MockMvcResultMatchers.content().string("Foo"))
            }
        }
    }
}

```

**Comment by LeoColman** [comment]
@donamk I couldn't reproduce it with JUnit Spring, so perhaps that's not supported?
```
@RunWith(SpringRunner::class)
@SpringBootTest(classes = [SimpleService::class, DummyController::class])
@AutoConfigureMockMvc
class Kl {
    
    @Autowired
    private lateinit var mockMvc: MockMvc
    
    @MockkBean
    private lateinit var simpleBean: SimpleService
    
    @Before
    fun before() {
        every { simpleBean.foo() } returns "Foo"
    }
    
    @Test
    fun foo() {
        simpleBean.foo() shouldBe "Foo"
    }

}
```

**Comment by LeoColman** [comment]
I mean, I couldn't get it to work for the same reason

**Comment by LeoColman** [comment]
@donamk I'll ask you to kindly create a new issue for this, as we're going offtopic.

@xcq1 We're using the latest version of bytebuddy
` 'net.bytebuddy:byte-buddy:1.10.1'`
So perhaps a library is overriding that version to a lower one? I believe Spring uses bytebuddy and Mockk uses bytebuddy as well, but I'm not sure about others

**Comment by donamk** [comment]
@Kerooker Thank you. You're right. I should create a seperate issue and I will do it

**Comment by xcq1** [comment]
I debugged a little and found out my remaining issue is that the package name `public` (which worked previously) is disallowed by ByteBuddy. After renaming, everything works as expected so the actual issue is fixed. Thanks for your quick reaction.

**Comment by LeoColman** [comment]
@xcq1 That's an odd issue to come by xD

Glad it's solved!
